### ISSUE TITLE
PayPal - Total missing tax (checkout popup)

### ISSUE THREAD

**Issue by guinsberg** [woocommerce/woocommerce-paypal-payments#2193] opened 2024-04-30 20:31 UTC
## Describe the bug
I noticed during testing that the total showing due in the PayPal popup box during checkout seems to exclude tax. It charges the correct amount so this is just visually wrong when approving the charge. I am seeing this on both staging and production. Below is a screenshot for reference:
![image](https://github.com/avatarnewyork/tuneupfitness/assets/95664809/7498fd4a-cf67-4a76-a817-0108dafc2203)

## To Reproduce
Place and order with an address in a taxable state (CA, WA, MN, IL) begin checking out with PayPal and once you login and the pop-up box appears (to select your payment option) - compare the subtotal shown in the box to what is shown in checkout. You will see the total in the PayPal box matches the total minus tax

## Expected behavior
The total showing what is due in the PayPal payment box matches the total due on our website. 

### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.2
 - Plugin Version 2.6.1

**Comment by SydeKrystian** [comment] 2024-05-16 09:10
Hello @guinsberg 

I'm not sure if it's related to the same plugin, but we've encountered a similar issue with the WooCommerce EU/UK VAT Compliance (Premium) by David Anderson, version 1.29.7.

The core of the issue appears to be that the plugin captures the amount displayed at checkout via woocommerce_checkout_process , rather than the final amount from the WooCommerce order that has been adjusted for VAT exemption. The author of the plugin has already discussed this issue on our GitHub page (https://github.com/woocommerce/woocommerce-paypal-payments/issues/1336), and it appears that the problem does not originate from our plugin.

If you case is about different plugin we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2024-05-16 09:10 UTC

**Comment by DavidAnderson684** [comment] 2024-08-09 21:39
Just to note that I'm not sure what is meant by this paragraph:

> The core of the issue appears to be that the plugin captures the amount displayed at checkout via woocommerce_checkout_process , rather than the final amount from the WooCommerce order that has been adjusted for VAT exemption. 

The VAT plugin doesn't "capture the amount" at all; it's not involved in that side of things, by its nature (marking a WooCommerce customer as VAT exempt doesn't involve anything to do with payment gateways). The problem is that the WooCommerce checkout and the PayPal gateway display different things sometimes when the order is VAT exempt, for reasons as yet unknown. Since the VAT plugin isn't involved in any communication at all with gateways, it appears to be an issue somewhere between WooCommerce core and the PayPal extension. As noted in the other issue, this is the only gateway displaying this issue, but other than that, I have no other information or ideas about the problem. (The PayPal extension has a code structure very unfamiliar to me and I wouldn't be able to investigate further without a lot of time invested in trying to understand it).

**Comment by DavidAnderson684** [comment] 2025-04-26 14:35
The cause of this was eventually tracked down. The PayPal plugin sends an AJAX request on the checkout to the back-end, `?wc-ajax=ppc-create-order`, and the back-end sends an API request to PayPal to create an order. But during this AJAX request, no flags are set inside WooCommerce (e.g. `WOOCOMMERCE_CHECKOUT` or `is_checkout()`) to indicate a check-out context. As such, the VAT plugin, when asked for the VAT country, includes signals which aren't relevant on the checkout. (On the checkout, the only country that matters is the order's taxation country; other things like visitor IP address which matter on ordinary product pages when first seeing the page, shouldn't be consulted).

We've now fixed this in the VAT plugin by adding special detection for the PayPal plugin's AJAX request.
