### ISSUE TITLE
Ecommerce Shop WooPayments Problem after the Update yesterday

### ISSUE THREAD

**Issue by pagranatur** [woocommerce/woocommerce-paypal-payments#1728] opened 2023-09-25 13:35 UTC
We have the problem since we applied your update from the plugin yesterday. With every payment method that the customer chooses, no matter if Amazon Pay, Paypal, Invoice etc., WooPayment is always added as payment method and that is fundamentally wrong. We ask for support. Thank you very much.

Best regards
Mandy Paas

**Comment by pagranatur** [comment] 2023-09-25 13:41
Ahh, I just saw that the payment method is correct when the order is received and only when I set The Order to Completed status is WooPayments inserted as the payment method.

Best regards
Mandy Paas
Our WooPayments Email is: pagranatur@gmail.com

**Comment by Sirvijver** [comment] 2023-09-26 12:33
Hello @pagranatur 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

It sounds like the issue you are describing is caused by the WooPayments plugin, not the PayPal Payments. If you believe the PayPal Payments plugin is causing this issue, please open a support ticket as described above, with the details that we need to verify the same. Please add the system report, logs and any screenshot that will support your findings.

For now, we will close this thread, since this is not a dev item.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-09-26 12:33 UTC
Labels: support
