### ISSUE TITLE
Unable to take payment via the "Debit or Credit Card" button

### ISSUE THREAD

**Issue by dagayveggi** [woocommerce/woocommerce-paypal-payments#1487] opened 2023-07-04 16:07 UTC
### Describe the Bug

I have noticed that there seems to be an issue when making a payment using the "Debit or Credit Card" button on PayPal. After entering the card details, a white box with a spinner appears endlessly. Unfortunately, there is no clear indication of what went wrong or what needs to be done next. All plugins are updated, and there are errors shown in the browser console and network log. However, there are no errors recorded in the hosting error logs.

### To Reproduce

1. Add a product to the cart within WooCommerce
2. Click on the mini cart and then select to checkout
3. Enter billing information such as address and contact info
4. Scroll down to select the black "Debit or Credit Card" button
5. Enter card info
6. Press the blue "Buy Now" button
7. A white box with a spinner appears as an overlay and never stops spinning with no indication of an error

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/5037836/39417e9e-a78f-464e-85dd-fe48fe5c9ee3)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/5037836/8ad4dbca-ec14-4fda-b8c9-f5a5f03366a5)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/5037836/5f205e41-f2dc-41bd-a811-fe871e833905)

Browser Console Logs:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/5037836/f8c362c5-6017-4e93-9b85-6ad58fa20d34)

### Expected Behavior

We would expect the white box to show as an overlay and then to prompt the user to follow through the steps in their banking app if needed.

### Actual Behavior

A white box modal overlay, with a spinner that never stops spinning and no errors, are displayed.

### Environment

 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.8.2
 - Plugin Version: WooCommerce PayPal Payments Version 2.1.0 
 - Browser [e.g. Chrome, Safari] and Version: Brave Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit) && Chrome Browser both desktop and mobile versions
 - Any other plugins installed: FluentSMTP, Google Listings and Ads, HappyFiles Pro, Rank Math SEO, Rank Math SEO PRO, Simple History, WooCommerce Shipping & Tax (Version 2.2.5)

### Additional Details

As mentioned the yellow PayPal button is working fine and as expected, it's only the "Debit or Credit Card" button beneath the yellow button that is not working,

<details><summary>System status</summary>

  ```
N/A
  ```

</details>

**Comment by erick3000** [comment] 2023-07-04 21:59
Same issue here, customer from UK called today stating the never stopping spinning when using his credit card. Any solution for now? or just hide funding credit / debit card?

what i can contribute is i don't have any of the listed plugins on your post.

**Comment by malteze-mangler** [comment] 2023-07-05 10:25
I'm currently having the same issue.

I've contacted PayPal Merchant Technical support as I diligiently looked at the files to see if had done anything code wise.

I recieved a reply from the engineers over there in PayPal land that it is a problem at their end they are trying to solve it, and will contact me when it has been done.

The issue I'm currently having is wanting to remove the "Debit or Credit Card" button as an option. I've tried CSS but I feel I need to look at their SDK and see what variables I need to declare or something to the button doesn't appear.

If anyone has any success in that department, feel free to let me know.

**Comment by Sirvijver** [comment] 2023-07-05 10:39
Hello @dagayveggi, @erick3000 and @malteze-mangler 

This is indeed an issue on PayPal server side and is not caused by our plugin. This (standard) card processing option, IS triggered by our plugin, but it is not controlled by our plugin. The best option to get more information about this outage is indeed by reaching out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport).

@malteze-mangler, did PayPal give you any reference for this outage, and could you share this with us?

From our side, we can only advise you to use the Advanced Card Processing payment option instead (when this is available to you; [these are the allowed countries](https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/)). The Advanced Card Processing payment method is controlled by our plugin and should not be affected by this outage.

I will keep this thread open for now, but be aware that we do not handle support threads via GitHub and instead advise anyone with support requests to open the engagements via [this website](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Kind regards, 
Joost

**Comment by dagayveggi** [comment] 2023-07-05 10:39
This was the reply that our client received from PayPal Merchant support (although we haven't developed this plugin, so it's not something we would look to make changes to directly):

Hi,

Thanks for contacting PayPal,

I see,

Could you please provide the steps to reproduce/replicate a payment?  HTML code of your button? URL of the error page (copy/paste)? Screenshots?

Source code:

https://www.paypal.com/gb/selfhelp/article/how-do-i-view-the-html-source-code-for-a-webpage-ts1464
 
How to get the source code:
 
1.- Use Firefox/Chrome
2.- Login to PayPal.com with your ALIAS and process to the Reporting page.(where the problem is)
3.- Right click on your mouse.
4.- Select "View page source"
5.- Save the file as .txt
6.- Attach it to the email.


Thanks,

Please, don't hesitate to contact us if you have further questions or issues or checkout the MTS forum - [https://www.paypal-community.com/t5/Merchant-Technical-Support/ct-p/mts](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.paypal-community.com%2Ft5%2FMerchant-Technical-Support%2Fct-p%2Fmts&data=04%7C01%7Cgsparano%40paypal.com%7C558cf977bbc7485adfaa08d97208d38c%7Cfb00791460204374977e21bac5f3f4c8%7C0%7C0%7C637666204492181754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hMEzf9kKAfb4wK9VfGRScqkCt2Yw%2FoEL0YNGPlW6fcA%3D&reserved=0)

Regards,
Gabrielle

**Comment by malteze-mangler** [comment] 2023-07-05 10:44
@dagayveggi That wont recreate the problem, as it's the processing part that is falling over. To recreate the issue you simply need to create the steps of carring out a transaction, and when it comes to the part of the lightbox popping up and displaying the circle, using your browser "inspect" the proceess and you will see a list of text thats in red, which is detailing the issue. Send that over to them.

**Comment by Sirvijver** [comment] 2023-07-05 10:49
Additional: if you want to hide the Standard Card Processing option, you can go to the PayPal Payments settings page and find the option "Hide Funding Source(s)" under the tab "Standard Payments". Here, you can add "Credit & debit cards" to hide the payment function until they resolved this issue.

**Comment by dagayveggi** [comment] 2023-07-05 11:19
@malteze-mangler I'll feed that back to our client as it is them that have contacted PayPal merchant support, as we don't use PayPal ourselves. Thank you for the assistance.

**Comment by dagayveggi** [comment] 2023-07-05 11:21
@Sirvijver I will also feedback your suggestion to our client as they only use PayPal for payments, so it may put people off buying in the meantime whilst the issue is being resolved. Thanks again :)

**Comment by dagayveggi** [comment] 2023-07-05 12:05
Seems to be showing on the PayPal Status Tracker now: https://www.paypal-status.com/incident/production

**Comment by darren-glanville** [comment] 2023-07-05 14:40
Great help on this one, thanks guys

**Comment by Sirvijver** [comment] 2023-07-06 07:46
Hello all,

it seems that PayPal has resolved this issue:
Resolved: Our technical teams have resolved the issue. Online checkouts have been restored. Affected Regions: Global

More details on this outage can be found here: https://www.paypal-status.com/history/eventdetails/66022

I will close this thread. Please let us know if you are still experiencing this issue, so we can check with PayPal if any other action should be taken.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-07-06 07:46 UTC
Labels: support

**Comment by darren-glanville** [comment] 2023-07-06 08:10
@Sirvijver Looks like it has now been fixed by Paypal, ran tests and working now. Thanks for the help.
