### ISSUE TITLE
PayPal Payments does not complete

### ISSUE THREAD

**Issue by Liqih** [woocommerce/woocommerce-paypal-payments#1644] opened 2023-08-29 23:44 UTC
### Describe the Bug

When a customer complete a purchase on my website [nusofting.com]  more often than not the order
stay on "Pending Payment" and I have to manually complete it.

### To Reproduce

Not known

### Expected Behavior

Order should be set to Completed after PayPal payment is done

### Actual Behavior

WooCoomerce>>Orders  shows "Pending Payment" 
after customer has paid (PayPal)
![woocommerce_errors](https://github.com/woocommerce/woocommerce-paypal-payments/assets/181779/49d1981d-9e95-430a-be21-25b7a2074235)

### Environment

 - WordPress Version 6.3.1 
 - WooCommerce Version 8.0.3
 - Plugin Version  2.2.2
 - Any other plugins installed

### Additional Details

Seems that the issues started to happen after WooCommerce
updated with WooPayments item in the WP dashboard.

WooPayments is NOT installed

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://nusofting.com
Site address (URL): https://nusofting.com
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 43.83MB
Database Data Size: 34.58MB
Database Index Size: 9.25MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.17MB + Index: 0.15MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.21MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.15MB + Index: 0.07MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_newsletter_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_user_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 5.94MB + Index: 0.08MB + Engine MyISAM
wp_postmeta: Data: 2.13MB + Index: 0.85MB + Engine MyISAM
wp_posts: Data: 0.58MB + Index: 0.10MB + Engine MyISAM
wp_redirection_404: Data: 14.52MB + Index: 5.55MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.97MB + Index: 0.57MB + Engine MyISAM
wp_users: Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp_wc_download_log: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_wc_order_stats: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.21MB + Index: 0.16MB + Engine MyISAM
wp_wfblocks7: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_wfconfig: Data: 3.27MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 0.89MB + Index: 0.08MB + Engine MyISAM
wp_wfhits: Data: 0.54MB + Index: 0.14MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 3.46MB + Index: 0.18MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Data: 0.35MB + Index: 0.07MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_cron: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_ftp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_mapping_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

album: 1
attachment: 308
awl_filter_gallery: 1
bwg_gallery: 1
custom_css: 1
easyimageslider: 1
elementor_library: 1
mgmlp_media_folder: 30
ml-slide: 19
ml-slider: 1
modula-gallery: 1
nav_menu_item: 14
ngg_gallery: 1
ngg_pictures: 12
oembed_cache: 1
page: 16
post: 6
product: 12
revision: 17
rl_gallery: 1
shop_coupon: 1
shop_order: 697
shop_order_refund: 1
shortcoder: 8
um_directory: 1
um_form: 3
wcp_ruleset: 1
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Query Monitor: by John Blackbourn – 3.13.1
Action Scheduler: by Automattic – 3.6.2
Code Snippets: by Code Snippets Pro – 3.4.2
Compact Audio Player: by Tips and Tricks HQ – 1.9.9
Contact Form 7: by Takayuki Miyoshi – 5.8
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.10
Free Downloads WooCommerce: by WP Enhanced – 3.5.5
Email Address Encoder: by Till Krüss – 1.0.22
FileOrganizer: by Softaculous Team – 1.0.2
Font Awesome: by Font Awesome – 4.4.0
MetaSlider: by MetaSlider – 3.36.0
MP3 Audio Player by Sonaar: by Sonaar Music – 4.7
Newsletter: by Stefano Lissa & The Newsletter Team – 7.9.1
Order Export & Order Import for WooCommerce: by WebToffee – 2.3.8
Redirection: by John Godley – 5.3.10
Responsive Lightbox & Gallery: by dFactory – 2.4.5
Safe SVG: by 10up – 2.2.0
Shortcoder: by Aakash Chakravarthy – 6.3
Page Builder by SiteOrigin: by SiteOrigin – 2.25.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.54.0
String Locator: by InstaWP – 2.6.3
Theme My Login: by Theme My Login – 7.1.6
User Menus: by Code Atlantic – 1.3.2
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.4.3
Converter for Media: by matt plugins – 5.9.6
WooCommerce Coupon Shortcodes: by itthinx
proaktion – 2.0.0

WooCommerce Filter Orders by Product: by Kowsar Hossain – 3.3
WooCommerce PayPal Payments: by WooCommerce – 2.2.2
WooCommerce: by Automattic – 8.0.3
Wordfence Security: by Wordfence – 7.10.3
Yoast SEO: by Team Yoast – 21.0
WP Migrate Lite: by WP Engine – 2.6.9
Widget Disable: by required – 3.0.0
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.8.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #113 - /plugins
Cart: #114 - /cart
Checkout: #115 - /checkout
My account: #116 - /my-account
Terms and conditions: #80 - /terms-of-use

### Theme ###

Name: Nusofting (GeneratePress child)
Version: 1.0
Author URL: http://boomtschak.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.3.1
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: ✔
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-30 14:29:39 +00:00
Options: ✔
Notes: 171
Onboarding: completed

### Action Scheduler ###

Complete: 65
Oldest: 2023-07-30 00:24:40 +0000
Newest: 2023-08-29 23:37:30 +0000

Pending: 1
Oldest: 2023-08-30 01:36:53 +0000
Newest: 2023-08-30 01:36:53 +0000

### Status report information ###

Generated at: 2023-08-29 23:41:40 +00:00
`
</details>

**Comment by Sirvijver** [comment] 2023-08-31 09:25
Hello @Liqih 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering is most of the time caused by the webhooks not functioning correctly, so the first thing you should do, is use the "Simulate" and possibly the "Resubscribe" buttons on the "Connection" tab, that are there to help test and fix the webhooks that our plugin uses to communicate with the PayPal server. If that does not help, you might want to disconnect and reconnect your account to the plugin, so that a new API key will be created and any issue with the current API key would be corrected.

If that still does not help you fix the issue, please reach out to our support team as described above, so we can take a closer look. Please include the system report, logs and any detail that could help if you choose to contact our support team.

For now, I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-08-31 09:25 UTC
Labels: support
