### ISSUE TITLE
connection of paypal account not working after entering sms code // did not receive email with instructions 

### ISSUE THREAD

**Issue by puepelinchen** [woocommerce/woocommerce-paypal-payments#1224] opened 2023-03-02 17:56 UTC
### Describe the Bug
After clicking "Activate Paypal" in woocommerce payment settings and identifying via sms code, the popup states "you'll receive an email with further instructions".  However, this email does not arrive. Checked & updated multiple times, gone through the process multiple time, also not in spam folder. 
In Woocommerce settings, I receive the following message: "We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again."

### To Reproduce
see above 

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-03-13 11:48
Hello @puepelinchen 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering can be caused by 2 situations with our plugin:
- Too quickly - It can be caused when you press continue to next page on the onboarding pop-up too quickly. Please try again to onboard the plugin, but don't rush through it and take at least 5 seconds per page before pressing to the next page or completing the process.
- Another plugin - It can be that another plugin is blocking our plugin from sending details to the PayPal server. For excluding this case, you can temporarily deactivate all other plugins (except WooCommerce and PayPal Payments) and try again to onboard.

Another option you have, is to get in contact with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review your account and see if there might be any other cause present on the account for this issue to occur.

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-03-13 11:48 UTC
Labels: support
