### ISSUE TITLE
PayPal buttons crash during filling the checkout form on android mobile with Google Chrome

### ISSUE THREAD

**Issue by titibleh** [woocommerce/woocommerce-paypal-payments#2020] opened 2024-02-08 23:50 UTC
### Describe the Bug

On the checkout page, when you are on an android mobile and use Google Chrome app, sometime if you clic on a text field also PayPal buttons crashs and you cannot pay. 

### To Reproduce

1. Add a product into your basket ;
2. Go to the checkout page ;
3. Click on all text checkout fields one by one (not need to fill it). It should open the keyboard (keep it open) ;
4. See the error by scrolling to payment methods (if you don't see the error, go to the top of the page (don't refresh) and do the step 3 and 4 again and again until you see the error).
_Because the error is random, sometime is showing after 1 clic and sometime it needs lot of clics_

#### PayPal button and Pay Later Message error :

![Screenshot_2024-02-08-22-53-03-531_com android chrome_note_resiz](https://github.com/woocommerce/woocommerce-paypal-payments/assets/142108952/b276097f-f516-4140-b45e-b72f84f643ee)

#### Debugging DevTools Chrome (chrome://inspect) error message when PayPal crashs :

<img width="356" alt="devtools-debug-error" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/142108952/9b85f659-db2a-480e-8e28-8e99c7fa922e">

### Expected Behavior

PayPal shouldn't crash.

### Actual Behavior

PayPal Smart buttons and Pay Later message is down and replaced by a grey bloc and you cannot pay your order.

### Environment

 - WordPress Version : latest
 - WooCommerce Version : latest
 - PayPal Plugin Version : latest
 - Chrome Version : latest
 - Android Version : 8.0+
 - Theme : Twenty Seventeen

### Additional Details

- We tried on other android browsers and the issue is only on Google Chrome browser and Google app (based on Chrome).
- We tried on older Google Chrome version and the issue is still there.
- We tried on many themes and the issue is still there.
- Must be physical tap on screen of the phone (don't use virtual phone)
- Because there is the "Render process gone" error on Devtools it's seems like there is an infinite loop into your code.

**Comment by Sirvijver** [comment] 2024-02-12 13:35
Hello @titibleh 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have followed your instructions on my own vanilla test environment (and using Android/Chrome), but am not able to get the same outcome as you are seeing. This makes me think that other elements on your site are adding to this issue, so I would advise you to first perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help, please open a support thread as advised above, and we can take another look at this situation for you. For now, we will close this GH thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2024-02-12 13:35 UTC
Labels: support

**Comment by TechJadeRoller** [comment] 2024-02-12 13:57
@Sirvijver Hello, we tried with Storefront theme and that's the same issue.  We have only plugins Woocommerce + PayPal activated so the issue is not due to a conflict with other thing. Maybe the issue is only on a specific Android version or smartphone, I use a Xiaomi with Miui 12.5.5 Stable (Xiaomi android overlay) but all my other mates are on iOS I cannot try to other android smartphone. I think you have to make a deeper investigation about this issue.

**Comment by titibleh** [comment] 2024-02-12 16:37
@Sirvijver Hello, we tried with Storefront theme and that's the same issue. We have only plugins Woocommerce + PayPal activated so the issue is not due to a conflict with other thing. Maybe the issue is only on a specific Android version or smartphone, I use a Xiaomi with Miui 12.5.5 Stable (Xiaomi android overlay) but all my other mates are on iOS I cannot try to other android smartphone. I think you have to make a deeper investigation about this issue.

**Comment by titibleh** [comment] 2024-02-12 16:38
@Sirvijver Hello, we tried with Storefront theme and that's the same issue. We have only plugins Woocommerce + PayPal activated so the issue is not due to a conflict with other thing. Maybe the issue is only on a specific Android version or smartphone, I use a Xiaomi with Miui 12.5.5 Stable (Xiaomi android overlay) but all my other mates are on iOS so I cannot try to other android smartphone. I think you have to make a deeper investigation about this issue.

Something interresting I have found: I have only 4go of ram and I just noticed that the problem occurs when I have less than 1.5go of ram available (it's around 3 or more apps open in the background). It seems like this issue is due to an overload of processing due to an issue with the PayPal code which consumes too much memory (maybe something which executes each time you click on a field or when you touch the screen).
