### ISSUE TITLE
WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by frankgadea** [woocommerce/woocommerce-paypal-payments#1648] opened 2023-08-30 22:53 UTC
### Describe the Bug

No option to pay by either credit card or PayPal visible when selecting payment option using WooCommerce PayPal Payments

### To Reproduce

1. Go to '…' https://flyfinz.com/checkout/
2. Click on '…'  Payment Method PayPal or  Debit & Credit Cards
3. Scroll down to …'  bottom of checkout
4. See error No option to pay by either credit card or Paypal visible just a spinning wheel

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/58676388/0ab76289-6041-4dfa-9a88-2c031ebe293b)

### Expected Behavior
A pop up to enable credit card details to be entered

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version Version 8.0.3
 - Plugin Version WooCommerce PayPal Payments Version 2.2.2 
 - Browser [e.g. Chrome, Safari] and Version Chrome
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2023-08-31 06:17
Hello @frankgadea 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2023-08-31 06:17 UTC
Labels: support
