### ISSUE TITLE
Paypal payment sends out error after Checkout

### ISSUE THREAD

**Issue by DerKeanu** [woocommerce/woocommerce-paypal-payments#1222] opened 2023-03-02 09:00 UTC
After completing the order in the checkout, a warning message is displayed and the checkout does not redirect the buyer to Paypal.
However, the buyer gets an email confirmation for the successful purchase. In the wordpress backend the order is also displayed as failed.

In the shopping cart the Paypal payment works without any problems.

![image](https://user-images.githubusercontent.com/40954291/222381054-34f91b4c-caea-44f7-9cf9-9e6e357547c8.png)

**Comment by Sirvijver** [comment] 2023-03-13 12:10
Hello @DerKeanu 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This error is often caused by our PayPal button not being displayed on the checkout page, and you see the original WooCommerce "Place Order" button instead. This often occurs when the JavaScript that is intended to do this, is blocked by another plugin or the theme. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

It could also be that your checkout page is not utilizing the correct short codes. You can test this by creating a test checkout page and only adding the short code [woocommerce_checkout]. When you preview this page, when you have a product in your cart, you should see the correct PayPal button (instead of the default WooCommerce one).

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost

**Closed as completed by Sirvijver** 2023-03-13 12:10 UTC
Labels: support
