### ISSUE TITLE
PayPal issues with subscription payments

### ISSUE THREAD

**Issue by Joethebird** [woocommerce/woocommerce-paypal-payments#1165] opened 2023-02-04 01:28 UTC
### Describe the Bug

**The issue that I am having is that when customers check out with PayPal their transactions get cancelled when they try and use PayPal. The product price is $17.99. When a client uses PayPal to but a single copy at $1.99, PayPal transactions go through just fine. This is an intermittent problem that has been occurring for the last 3 months.**

### To Reproduce

1. Go to the 'annual subscription section to buy a pdf product.'
2. Click on 'purchase to add to cart'
3. Use PayPal 'as your payment type'

### Environment

 - WordPress Version - 6.1.1
 - WooCommerce Version - 7.3.0
 - Plugin Version - WooCommerce PayPal Payments version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version - from users. Seemingly all browsers...
 - Any other plugins installed - We have plenty of other plugins installed. My chief coder has not found any underlying issues except with this plugin.

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
Dont want to change this... Thank you for any help
</details>

**Comment by Sirvijver** [comment] 2023-02-07 12:12
Hello @Joethebird 

You did not provide sufficient details for me to reproduce the issue or check your website on this matter. Since we don't provide plugin support via GitHub (we only do development activities here), I will close this thread and ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Please provide them with the system report and possibly screenshots of what you are seeing (what the issue is) or any other details that can help explain the situation. Thank you.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-02-07 12:12 UTC
Labels: support
