### ISSUE TITLE
WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by fdesignsrl** [woocommerce/woocommerce-paypal-payments#1238] opened 2023-03-09 17:04 UTC
### Describe the Bug

From a couple of weeks the plugin indicate this error:
**Authentication with PayPal failed: Could not create token.
_Please verify your API Credentials and try again to connect your PayPal business account. Visit the [plugin documentation]__(https://docs.woocommerce.com/document/woocommerce-paypal-payments/) for more information about the setup._**

We tried to disconnect and reconnect the account 4 times, using both of automatic and manual setting. Paypal account is active and functioning without restrictions. 

Plugin worked fine until February 26th. No updates on Woocommerce or Wordpress done after that date.

Our client tried to contact Paypal assistance for a check the issue, but for them is a plugin problem...

The website is www.faram-rieti.com, if you need we can activate a Wordpress account for you, so you can do some tests.

### Environment

 - WordPress Version: 5.5.4
 - WooCommerce Version: 4.6.3
 - Plugin Version: 2.0.2
 - Browser [e.g. Chrome, Safari] and Version: Safari and Chrome
 - Any other plugins installed

### Additional Details

Another issue:
Subscribed webhooks | Failed to load webhooks.

Thank you for you attention, best regards.

**Comment by Sirvijver** [comment] 2023-03-13 11:11
Hello @fdesignsrl 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Have you already tried to connect with a sandbox account? This will show if the issue is related to the account or the plugin. If you require more support, you need to open a support request via the link above and provide us more details:
- What is the error you are seeing?
- Are you able to process any payments?
- Please provide the system report and the logs.
- Have you onboarded using the connect wizard (blue button "Activate PayPal"). Onboarding your credentials manually can cause issues and would only be advised to use as a last resort.

For now we will close this support request and advise you to [open a support request with our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-03-13 11:11 UTC
Labels: support
