### ISSUE TITLE
Order with no adress/shipping/build (1896)

### ISSUE THREAD

**Issue by Araxxon** [woocommerce/woocommerce-paypal-payments#1522] opened 2023-07-19 11:19 UTC
Our customers who are guests and do not use a customer login are displayed in WooCommerce without data (no shipping/billing address), everything is completely empty

See Screenshot

We have to log into our PayPal account with the PayPal transaction number that is displayed in the order and from there manually remove and insert the shipping address.

We need help. We thank so much. 
![keine adresse 1](https://github.com/woocommerce/woocommerce-paypal-payments/assets/139972476/31c5b6c6-f5aa-4424-935a-d49a9b5abdb9)

**Comment by Sirvijver** [comment] 2023-07-19 12:04
Hello @Araxxon 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue, you raised here, is a known one that was already raised in this [.org thread](https://wordpress.org/support/topic/details-being-deleted-no-customer-information-on-order/). You can follow the updates via this thread, but we would recommend opening a private engagement with us, so we can possibly review and test your environment if you have a staging site available for us.

The issue seems to be caused by our 2.2.0 release, and we were told that you can correct it be rolling back to version 2.1.0.
I will keep this thread open for possible bug fix on GitHub, but I would advise you to create the private engagement if you want to help us resolve this issue, because so far we have not been able to recreate this issue ourselves on our own testing environment.

Kind regards, 
Joost

**Comment by Araxxon** [comment] 2023-07-19 12:32
Hello @Sirvijver, thank you very much for your quick response. We will for nor be rolling back to version 2.1.0 and also opened a private engagement with you. We will wait for bug fix. Thank you.
Kind Regards, Araxxon

**Comment by riccardodicurti** [comment] 2023-07-25 18:47
I also have the same problem with the following plugin versions: 

WooCommerce PayPal Payments 2.2.0 
WooCommerce 7.9.0

Someone in the WordPress plugin repository forum wrote that he solved it by removing a previously added custom checkbox to the checkout: 

```
add_action( 'woocommerce_review_order_before_submit',  function() {
    woocommerce_form_field( 'privacy_policy', array(
        'type'          => 'checkbox',
        'class'         => array('form-row privacy'),
        'label_class'   => array('woocommerce-form__label woocommerce-form__label-for-checkbox checkbox'),
        'input_class'   => array('woocommerce-form__input woocommerce-form__input-checkbox input-checkbox'),
        'required'      => true,
        'label'         => ''
    ));
}, 20 );
```

**Comment by eddr** [comment] 2023-07-26 11:22
> 

I also had problems with the checkbox. 
Your code doesn't remove the checkboxes, so can you link to the original thread?

**Comment by riccardodicurti** [comment] 2023-07-26 11:42
Try looking at this thread: https://wordpress.org/support/topic/details-being-deleted-no-customer-information-on-order/page/2/

**Comment by InpsydeNiklas** [comment] 2023-07-27 08:36
Hi folks,
Apologies for the trouble.
This issue could be worked around either with a downgrade to the [previous version 2.1.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.1.0/woocommerce-paypal-payments.zip), or you could also give it a try with [this test version](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6) which includes a proposed fix that will be part of the next update.
Feedback is much appreciated if you were to give it a try with the test version.
Thanks!

**Closed as completed** 2023-08-02 14:52 UTC
Labels: bug

**Comment by danielbreves** [comment] 2023-08-05 13:17
@InpsydeNiklas the test version seems to fix the issue for me. Thanks!
