### ISSUE TITLE
Fatal Error WooCommerce PayPal Payments (version 2.7.2)

### ISSUE THREAD

**Issue by jzarowitz** [woocommerce/woocommerce-paypal-payments#2307] opened 2024-06-03 13:10 UTC
### Describe the Bug
When seeking help with this issue, you may be asked for some of the
following information:
WordPress version 6.5.3
Active theme: Salient (version 16.2.2)
Current plugin: WooCommerce PayPal Payments (version 2.7.1)
PHP version 7.4.33

Error Details
=============
An error of type E_ERROR was caused in line 1577 of the file
/home4/hmhskvmy/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php.
Error message: Uncaught Error: Class
'WooCommerce\PayPalCommerce\Axo\Gateway\AxoGateway' not found in
/home4/hmhskvmy/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php:1577
Stack trace:
#0 /home4/hmhskvmy/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117):
WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#1 /home4/hmhskvmy/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56):
WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#2 /home4/hmhskvmy/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(1582):
WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.ppcp-...')
#3 /home4/hmhskvmy/public_html/wp-cont

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

When seeking help with this issue, you may be asked for some of the
following information:

 - WordPress Version -6.5.3
 - WooCommerce Version - 8.9.1
 -  - Plugin Version - WooCommerce PayPal Payments (version 2.7.1)
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed
 - Woo Commerce 8.9.1
 - WC Ship and Tax - 2.5.7
 - Order Export and Order Import for WC - 2.5.2
 - Advanced Order Export for WC - 3.5.2
 - Active theme: Salient (version 16.2.2)
 - PHP version 7.4.33
other plugins too

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-06-04 04:54
Hello @jzarowitz 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Regarding the issue, I recommend reinstalling the plugin. It's possible there was an error during installation, as the stack trace doesn't indicate the cause.

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2024-06-04 04:54 UTC
Labels: support
