### ISSUE TITLE
Payment by credit card begins with the mandatory fields not filled in

### ISSUE THREAD

**Issue by dbello78** [woocommerce/woocommerce-paypal-payments#1161] opened 2023-02-03 09:19 UTC
### Describe the Bug
When "Advanced Card Processing" is enabled, the payment by credit card begins with the mandatory fields not filled in 
After credit card processing (3DS) the required fields notification is displayed.

### To Reproduce

1. Go to 'checkout' page
2. Click on Credid Card payment
3. Fill out the card form only
4. Place the order
5. See error

### Expected Behavior

The notification about mandatory fields should displayed in step 4.

### Environment

 - WordPress Version 6.1.1 
 - WooCommerce Version 7.3.0
 - Plugin Version 2.0.2
 - Browser Chrome, Firefox, Opera, Edge.

**Comment by Sirvijver** [comment] 2023-02-03 12:48
Hello @dbello78 

Thank you for reaching out to us, we are here to help. However, we do not do plugin support via GitHub, so we have to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
The issue you report is not a known issue to us, so I would expect some other element on your site to add to this problem. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
 Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this doesn't help you find the cause of this issue, please open a new support request with us via the instructions linked above. We will close this ticket.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-02-03 12:48 UTC
Labels: support
