### ISSUE TITLE
I can't input the card number on checkout page.

### ISSUE THREAD

**Issue by KolinJohn** [woocommerce/woocommerce-paypal-payments#2085] opened 2024-03-08 01:16 UTC
Hello

https://couchguard.com.au/checkout/
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/122082405/f5055f95-64ec-4b1c-b35f-4e05eef1bd32)
As you can see, Js console issue exists, but I don't know how to debug and fix the issue.
Could you help me please?
Thank in advance.

**Comment by SydeKrystian** [comment] 2024-03-08 10:32
Hello @KolinJohn 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-03-08 10:32 UTC
Labels: support
