### ISSUE TITLE
paypal payments

### ISSUE THREAD

**Issue by aromags** [woocommerce/woocommerce-paypal-payments#2223] opened 2024-05-13 15:17 UTC
### Describe the Bug

 Will not process credit cards on the advance credit card process.  On the check out screen, the processing just spins and never completes the payments.  Paying with paypal works fine.  I have had to temporarily add another processor just to be able to complete orders.  This has been happening about 3 weeks now.

### To Reproduce

to to checkout screen and choose credit card
1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Expected Behavior
process the credit payment

 

### Actual Behavior
screen just spins, never processes

### Environment

 - WordPress Version. 6.5.3
 - WooCommerce Version 8.8.3
 - Plugin Version 2.7.0
 - Browser [e.g. Chrome, Safari] and Version. seems to be all browsers
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-05-16 09:24
Hello @aromags 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-05-16 09:24 UTC
