### ISSUE TITLE
NO FUNCIONA EL BOTÓN 

### ISSUE THREAD

**Issue by NETCARDONAGT** [woocommerce/woocommerce-paypal-payments#1521] opened 2023-07-19 02:08 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-07-19 07:34
Hello @NETCARDONAGT 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Usually when the button is not working it might be that the WooCommerce button (Place Order) is not getting replaced with our generic PayPal button and that will cause the button to fail. This would be caused by the JavaScript being blocked by another plugin. You could try to find out what plugin this is by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If the PayPal button simply does not respond, you might need to take a closer look at the error response in the console (f12) and see what error it is showing. Such a problem could possibly be caused by the theme or other plugins and doing conflict testing could also give you good insights of this (and is the advised way to go).

If this does not help you find the cause/solution, please reach out to our support team as mentioned above. We will close this thread on GitHub now. If you open a support thread, please add the system report and any logs that you have available.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-07-19 07:34 UTC
Labels: support
