### ISSUE TITLE
Plugin version 2.9.2 causes duplicate HTML ID in checkout page

### ISSUE THREAD

**Issue by nirkons** [woocommerce/woocommerce-paypal-payments#2686] opened 2024-10-10 10:56 UTC
### Describe the Bug

after updating to 2.9.2 there are now 2 order buttons on checkout page with the same ID, we had to revert.

### To Reproduce

Update to 2.9.2
Go to checkout page and see console errors

### Screenshots

![Image](https://github.com/user-attachments/assets/672ce9bc-f27a-4163-86f9-774d25549c72)

### Expected Behavior

HTML element IDs should be unique.
there is already a place order button of woocommerce with this same ID

**Comment by SydeKrystian** [comment] 2024-10-15 07:06
Hello @nirkons 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2024-10-15 07:06 UTC
Labels: support

**Comment by nirkons** [comment] 2024-10-15 15:17
@SydeKrystian  - this is not a support request, this is a code issue with the plugin that is adding a duplicate HTML ID in the woocommerce checkout page, HTML DOM should never have duplicate element IDs.

https://github.com/woocommerce/woocommerce-paypal-payments/blob/bbd25f89e852d1c214dba25b9b2d2be3b410957d/modules/ppcp-axo/src/Assets/AxoManager.php#L250

**Comment by SydeKrystian** [comment] 2024-10-15 15:23
Hello @nirkons 

You are correct and it seems that I was too quick in my initial analysis. I thought the request might be related to duplicate "Place Order" buttons, as we've encountered similar issues before. I've now raised this matter with our developers to investigate it further. 

Thank you for your understanding, and I will keep you updated on the progress.

Kind Regards,
Krystian

**Comment by SydeKrystian** [comment] 2024-10-15 15:41
Helo @nirkons 

Regarding the problem; these IDs normally should not be duplicated, but while it introduces this console warning, it is actively solving a potential compatibility issue with certain themes. We had a non-trivial amount of support requests caused by mismatching button styling on the Checkout page. Most often, this was because the theme styled the checkout buttons based on the id, which is not recommended either, but still a practice used in many third-party themes. So we had three options:

1. Each button preserves their unique ID and we continue to get support tickets about mismatching button styles, for which the theme is actually at fault, not the PayPal Payments plugin
2. Add more complexity to conditionally switch/move the id around from button to button, making sure the #place_order  id stays on the visible button
3. Simply use the same id for all buttons, at the cost of introducing a console warning

While it clearly is not the optimal solution, so far we also haven't found any problems caused by this, outside of the console warning. In the near future, we'll work on ensuring that if Advanced Card Processing or Fastlane is not enabled, the message won't appear.

If you are facing any specific logic problems resulting from that, we're happy to re-evaluate as there may be more room to optimize it and preserve best possible theme compatibility without introducing "console noise". 

Kind regards,
Krystian

**Comment by nirkons** [comment] 2024-10-15 18:49
Yes for us it broke the checkout page, since there is code that targets the order button by the ID, it will break for anyone else that is doing that as well. We will have to find a workaround if we want to update the plugin in the future.

However, its not really the issue of the console warning, it just goes against HTML best practice of not having multiple elements on the page with the same ID, I don't think personally that its a correct solution for the issue.

thanks

**Comment by SydeKrystian** [comment] 2024-10-16 06:35
Hello @nirkons 

For now, we recommend reaching out to us directly, as we’ll need to review the system report and gather additional details to investigate further. You can contact our support team through the following link: [WooCommerce PayPal Payments Support](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

We're here to assist you in finding the best solution.

Kind Regards,

Krystian
