### ISSUE TITLE
401 error response on wp-json

### ISSUE THREAD

**Issue by syntaxmedia** [woocommerce/woocommerce-paypal-payments#1857] opened 2023-11-22 16:11 UTC
"POST /wp-json/paypal/v1/incoming HTTP/1.1" 401 479 "-" "PayPal/AUHR-214.0-58228326" 

is called periodically and results in an error 401. Access_log is flooded with these messages. But PayPal payments seems to work in checkout. What is this?

**Comment by michaelrimbach** [comment] 2023-11-23 09:26
We have the same issue but on a larger scale. 

grep 'POST /wp-json/paypal/v1/incoming HTTP/1.1" 401' 20231122-access.log | wc -l
**76516**

Also see
https://wordpress.org/support/topic/401-for-rest-calls-to-wp-json/

**Comment by syntaxmedia** [comment] 2023-11-23 09:36
grep 'POST /wp-json/paypal/v1/incoming HTTP/1.1" 401' access.log | wc -l
**17417**

**Comment by InpsydeNiklas** [comment] 2023-11-24 17:39
These normally should be incoming webhooks from PayPal. If there is a problem with the webhook delivery, PayPal may try again and again to send the webhooks until they were received.
Is the WordPress REST API accessible on your sites? When this is blocked, it would essentially also block the webhook delivery and it could potentially result in multiple webhook events piling up until PayPal received a confirmation.
Beyond these access logs, can you observe any messages in the PayPal Payments plugin log files about failing webhooks or do you notice any sync issues, e.g. when performing actions like refunds on the PayPal website?
In some cases, it can help to [resubscribe there webhooks](https://woocommerce.com/document/woocommerce-paypal-payments/#webhook-status) to ensure the communication with PayPal works both ways.

**Comment by syntaxmedia** [comment] 2023-11-24 17:47
Resubscribing to webhooks does not solve this problem. Sometimes I can see this request having succeeded with status 200, but most times it failes with 401. I believe there is some authentication missing when calling the webhook, or is everyone allowed to make a POST request to this endpoint? 

Now that you mention it, we notice a delayed delivery of paypal confirmation emails. Maybe this is because of the webhook failing? Sometimes it takes half an hour until mails arrive.

**Comment by Sirvijver** [comment] 2023-11-30 14:48
Hello all,

since we heard back from some users that this issue only occurred temporary and did not occur after the 24th of November, we will close this thread. From the PayPal Payments plugin perspective, there was nothing changed, so we cannot explain this issue from our side. I reviewed the PayPal server fault history and saw there was some incident on the 24th, so that could be related. However, we cannot confirm this. If you want to get more information, I suggest you reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and see if they have more information available about this.

I will mark this thread as resolved, since there is nothing more we can do on this matter.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-11-30 14:48 UTC
Labels: support

**Comment by michaelrimbach** [comment] 2023-12-12 07:49
hi @Sirvijver 

bad news, the issue is back since 6.12. Did you got any other complaints / informations in the meantime? 

Yesterday:
56.477

zgrep '/wp-json/paypal/v1/incoming' 20231209-access.log.gz | wc -l
63212

zgrep '/wp-json/paypal/v1/incoming' 20231208-access.log.gz | wc -l
74865

zgrep '/wp-json/paypal/v1/incoming' 20231207-access.log.gz | wc -l
61465

zgrep '/wp-json/paypal/v1/incoming' 20231206-access.log.gz | wc -l
20174

zgrep '/wp-json/paypal/v1/incoming' 20231205-access.log.gz | wc -l
2111

User-Agent: PayPal/AUHR-214.0-58228326

**Comment by syntaxmedia** [comment] 2023-12-12 08:17
@michaelrimbach I can confirm massive calls from PayPal against the webhook, but they all have response code 200 instead of 401. So I can't see a problem there for us.

best wishes
Carsten

**Comment by Sirvijver** [comment] 2023-12-12 08:58
Hello all,

as said before here and on the [.org thread](https://wordpress.org/support/topic/401-for-rest-calls-to-wp-json/) we have opened for this, these calls are coming from the PayPal server and not from our plugin. For this reason, it will be better to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them what is causing these calls and see if they know if there is anything that can be done to resolve this situation. From the plugin's perspective, there is simply not that much we can do.

Kind regards, 
Joost
