### ISSUE TITLE
Problems Taking Payments By Customer Service Reps

### ISSUE THREAD

**Issue by sweberjlm** [woocommerce/woocommerce-paypal-payments#908] opened 2022-10-12 19:08 UTC
### Describe the Bug

We are using our website to also take orders over the phone by our Customer Service Reps (CSRs). These people are seeing problems with the payment. The site is normally reporting problems with messages like "We weren't able to add this card. Check all the details are correct and try again or try a different card." We are seeing messages in the admin site saying "Could not retrieve order. OrderEndpoint.php:459 Order status changed from Pending payment to Failed." There is no evidence of the payment being attempted in our PayPal Payflow Manager, so it doesn't appear that the payment attempt is even being sent to through the gateway.

The theory that I have - I'm a website developer myself - is that there is information in the user's session that is somehow interfering or confusing the PayPal payment plugin.  Remember that these are CSRs who are placing multiple orders for different people throughout the day - this is not what I might consider to be a traditional usage.

Please note that I'm able to take the credit card information that fails on the website directly into the PayPal Payflow manager and process the payment through that interface without issue - so the idea that the card is bad is not a reasonable explanation.  The problem is with the gateway - and I believe with the user session.

### To Reproduce

No outside users are reporting this problem - just our inside CSRs. Place items into the cart and attempt to check out with valid information after doing the same process multiple time (with different information) over the cost of an hour.

### Screenshots

![image](https://user-images.githubusercontent.com/115577594/195425720-ab720069-57cc-4071-8fed-55acae880b7b.png)
![image](https://user-images.githubusercontent.com/115577594/195425808-0a1dbb84-5e0e-4891-938e-279532d69b19.png)

### Expected Behavior

We would expect the site to not store any information in the User Session that would interfere with the ability to place multiple orders.  Once an order is successfully completed, the session should be wiped out.

### Actual Behavior

CSRs are unable to take more than one or two orders before the site stops accepting payments.

### Environment

 - WordPress Version - 6.0.2
 - WooCommerce Version - 7.0.0
 - WooCommerce Paypal Payments Plugin Version - 1.9.4
 - Browser [e.g. Chrome, Safari] and Version - Most of our users are using Chrome - but we have seen this on Edge as well.
 - Any other plugins installed
** We are also running WooCommerce Checkout Field Editor (1.9.4)
** We are also running Order Restrictions for Woo Commerce (2.0)

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://redgranitecorrection.com
Site address (URL): https://redgranitecorrection.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: mm3_8_
Total Database Size: 16.61MB
Database Data Size: 12.61MB
Database Index Size: 4.00MB
mm3_8_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mm3_8_woocommerce_order_items: Data: 0.23MB + Index: 0.08MB + Engine InnoDB
mm3_8_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.97MB + Engine InnoDB
mm3_8_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mm3_8_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mm3_8_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mm3_8_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_actionscheduler_actions: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
mm3_8_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
mm3_8_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
mm3_8_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_options: Data: 8.02MB + Index: 0.14MB + Engine InnoDB
mm3_8_postmeta: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
mm3_8_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
mm3_8_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
mm3_8_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mm3_8_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
mm3_8_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mm3_8_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_8_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
mm3_8_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mm3_8_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_8_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mm3_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mm3_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mm3_sitemeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
mm3_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
mm3_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 62
page: 4
post: 20
product: 48
product_variation: 7
rts_order_rule: 1
rts_payment_rule: 1
shop_order: 296
shop_order_refund: 6
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

WooCommerce: by Automattic – 7.0.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.2
USPS Simple Shipping for Woocommerce: by dangoodman – 1.7.2
WooCommerce Payments: by Automattic – 4.8.1
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
NS Cloner - Site Copier: by Never Settle – 4.2.1
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.4
Order Restrictions for WooCommerce: by FantasticPlugins – 2.0
Really Simple SSL: by Really Simple Plugins – 5.3.5
WooCommerce PayPal Payments: by WooCommerce – 1.9.4

### Inactive Plugins (7) ###

Advatix FEP API Connection: by Advatix – 2.0
Bluehost: by Bluehost – 2.12.8
Bluehost Website Builder: by Newfold Digital – 1.0-2653 : 20220809_085420
Creative Mail by Constant Contact: by Constant Contact – 1.5.4
File Manager Advanced: by modalweb – 4.1.6
Jetpack: by Automattic – 11.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.23

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.2
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://redgranitecorrection.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — Wisconsin

### Payment Gateway Support ###

PayPal: refunds

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-13 18:28:12 -05:00
Options: ✔
Notes: 49
Onboarding: completed

### WooCommerce Payments ###

Version: 4.8.1
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 979
Oldest: 2022-09-28 22:01:12 -0500
Newest: 2022-10-12 11:49:23 -0500

Pending: 1
Oldest: 2022-10-12 14:11:55 -0500
Newest: 2022-10-12 14:11:55 -0500

### Status report information ###

Generated at: 2022-10-12 14:07:28 -05:00

</details>

**Comment by femiyb** [comment] 2022-10-14 09:42
@sweberjlm 

This is a known issue since our 1.9.2 release, with failures for purchases done via older web browsers.

This issue has been resolved with our 1.9.4 release. Please check and confirm if this error still occurs with the latest version (note that this was released two days ago).
For further assistance, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!

**Closed as completed by femiyb** 2022-10-14 09:42 UTC
Labels: support

**Comment by sweberjlm** [comment] 2022-10-14 13:13
@femiyb Except that we're already running 1.9.4 - I posted that in my original ticket.  This is a brand new site that's _always_ been running 1.9.4

**Comment by khizar1556** [comment] 2022-11-07 09:56
@femiyb the issue is still here
