### ISSUE TITLE
Browser console error on the plugin's settings page

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-paypal-payments#930] opened 2022-10-21 16:26 UTC
### Describe the Bug

When loading the plugin's settings page, there's an error in the console saying `Uncaught TypeError: Cannot read properties of null (reading 'style')` coming from `gateway-settings.js:74`.

### To Reproduce

1. Go to the PayPal Payment's settings page `wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-connection`
2. Open the browser console
3. Notice there's an error coming from the plugin's file
```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at HTMLDocument.<anonymous> (gateway-settings.js:74:37)
```

### Screenshots

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/41606954/197243214-3166dba0-d005-4952-8682-e0568975d32f.png">

### Expected Behavior

There must not be console errors on page load.

### Actual Behavior

There's an error in the console on page load.

### Environment

 - WordPress Version: 6.0.3
 - WooCommerce Version: 7.0.0
 - Plugin Version: 1.9.4
 - Any other plugins installed. WooCommerce Payments.

**Comment by InpsydeNiklas** [comment] 2023-03-24 18:23
The plugin settings have been improved since this issue was opened, and while I remember having seen this console error as well, I can no longer reproduce it with the latest WooCommerce and PayPal Payments versions.
I can't pinpoint when it was fixed but think it's ok to close this issue for now. 
But please let us know if the error persists for you. Thanks!

**Closed as completed by InpsydeNiklas** 2023-03-24 18:23 UTC
Labels: bug
