### ISSUE TITLE
Bug with shipping methods and plugin WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by AleBTstudio** [woocommerce/woocommerce-paypal-payments#1805] opened 2023-10-27 10:01 UTC
### To Reproduce

1. Go to vasofashion.it
2. Put a product in the cart
3. Go to shop and put another product
4. see the bug in shipping methos by default (now you don't find courrier but other method)

<img width="696" alt="Screenshot 2023-10-27 alle 11 55 29" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/148642506/cda9bd10-b77f-4d25-bf64-37856a1e1c28">

### Environment

 - WordPress Version 6.3.2
 - WooCommerce Version 8.2.1
 - Plugin Version 2.3.1
 - all browser

### WordPress Environment ###

WordPress address (URL): https://vasofashion.it
Site address (URL): https://vasofashion.it
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.24
PHP Post Max Size: 150 MB
PHP Time Limit: 180
PHP Max Input Vars: 12000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.34
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: wpu7_
Dimensione totale database: 473.51MB
Dimensione dati database: 297.67MB
Dimensione indice database: 175.84MB
wpu7_woocommerce_sessions: Dati: 16.02MB + indice: 0.05MB + motore InnoDB
wpu7_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpu7_woocommerce_order_items: Dati: 3.52MB + indice: 1.52MB + motore InnoDB
wpu7_woocommerce_order_itemmeta: Dati: 42.58MB + indice: 35.11MB + motore InnoDB
wpu7_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpu7_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_actionscheduler_actions: Dati: 17.08MB + indice: 21.30MB + motore InnoDB
wpu7_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_actionscheduler_logs: Dati: 8.52MB + indice: 7.03MB + motore InnoDB
wpu7_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_comments: Dati: 11.52MB + indice: 10.09MB + motore InnoDB
wpu7_fusion_form_entries: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_fusion_form_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_fusion_form_submissions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_fusion_forms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_icl_background_task: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_content_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_core_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_languages: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_icl_languages_translations: Dati: 0.20MB + indice: 0.17MB + motore InnoDB
wpu7_icl_locale_map: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_message_status: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_icl_mo_files_domains: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wpu7_icl_node: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_reminders: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_string_batches: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_string_packages: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_string_pages: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_icl_string_positions: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
wpu7_icl_string_status: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_string_translations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_icl_string_urls: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_strings: Dati: 0.33MB + indice: 0.61MB + motore InnoDB
wpu7_icl_translate: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_translate_job: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_icl_translation_batches: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_translation_downloads: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_icl_translation_status: Dati: 0.14MB + indice: 0.06MB + motore InnoDB
wpu7_icl_translations: Dati: 1.52MB + indice: 3.92MB + motore InnoDB
wpu7_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_mailchimp_carts: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wpu7_mailchimp_jobs: Dati: 13.52MB + indice: 0.00MB + motore InnoDB
wpu7_options: Dati: 27.38MB + indice: 2.50MB + motore InnoDB
wpu7_post_smtp_logmeta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_post_smtp_logs: Dati: 8.02MB + indice: 0.00MB + motore InnoDB
wpu7_postmeta: Dati: 93.64MB + indice: 62.22MB + motore InnoDB
wpu7_posts: Dati: 20.52MB + indice: 6.06MB + motore InnoDB
wpu7_raneri_danea_scheduled: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_sbi_feed_caches: Dati: 0.20MB + indice: 0.02MB + motore InnoDB
wpu7_sbi_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_sbi_instagram_feed_locator: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_sbi_instagram_feeds_posts: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
wpu7_sbi_instagram_posts: Dati: 4.52MB + indice: 0.00MB + motore InnoDB
wpu7_sbi_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_term_relationships: Dati: 0.30MB + indice: 0.27MB + motore InnoDB
wpu7_term_taxonomy: Dati: 0.13MB + indice: 0.16MB + motore InnoDB
wpu7_termmeta: Dati: 0.34MB + indice: 0.48MB + motore InnoDB
wpu7_terms: Dati: 0.11MB + indice: 0.14MB + motore InnoDB
wpu7_usermeta: Dati: 11.52MB + indice: 13.03MB + motore InnoDB
wpu7_users: Dati: 1.52MB + indice: 0.48MB + motore InnoDB
wpu7_wc_admin_note_actions: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wpu7_wc_admin_notes: Dati: 0.11MB + indice: 0.00MB + motore InnoDB
wpu7_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_wc_customer_lookup: Dati: 1.52MB + indice: 0.59MB + motore InnoDB
wpu7_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpu7_wc_order_bundle_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wpu7_wc_order_coupon_lookup: Dati: 0.08MB + indice: 0.11MB + motore InnoDB
wpu7_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_wc_order_product_lookup: Dati: 3.52MB + indice: 5.02MB + motore InnoDB
wpu7_wc_order_stats: Dati: 1.52MB + indice: 1.08MB + motore InnoDB
wpu7_wc_order_tax_lookup: Dati: 1.52MB + indice: 0.75MB + motore InnoDB
wpu7_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wpu7_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_wc_product_attributes_lookup: Dati: 0.23MB + indice: 0.17MB + motore InnoDB
wpu7_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_wc_product_meta_lookup: Dati: 1.52MB + indice: 1.42MB + motore InnoDB
wpu7_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpu7_wdr_order_discounts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_wdr_order_item_discounts: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpu7_wdr_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpu7_woocommerce_bundled_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_woocommerce_bundled_items: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpu7_wpml_mails: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wpu7_ywdpd_exclusion_list_table: Dati: 0.02MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

attachment: 9128
fusion_element: 12
fusion_tb_section: 2
fusion_template: 1
gift_card: 71
koalaapps_psc: 1
nav_menu_item: 28
page: 15
post: 12
product: 440
product_variation: 1510
revision: 741
seedprod: 2
shop_coupon: 15
shop_order: 12589
shop_order_refund: 252
slide: 3
wpcf7_contact_form: 2
yith-wcbm-badge: 3
ywdpd_discount: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.6.7
Conditional Fields for Contact Form 7: by Jules Colle – 2.3.12
Click to Chat: by HoliThemes – 3.30.1
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.15.3
Connects - Mailchimp Addon: by Brainstorm Force – 2.2.4
Contact Form 7 Multilingual: by OnTheGoSystems – 1.2.1
Contact Form 7: by Takayuki Miyoshi – 5.8.2
Convert Plus: by Brainstorm Force – 3.5.24
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Flexible Shipping: by Octolize – 4.23.0
Avada Builder: by ThemeFusion – 3.11.2
Avada Core: by ThemeFusion – 5.11.2
Feed Instagram di Smash Balloon: by Smash Balloon – 6.2.4
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.7.6
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.2.2

Mailchimp for WooCommerce: by Mailchimp – 3.2
Post SMTP: by Post SMTP – 2.7.0
Danea Easyfatt Import/Export: by Riccardo Raneri – 2.35.1
KoalaApps - Size Chart for WooCommerce: by KoalaApps – 1.2.3
W3 Total Cache: by BoldGrid – 2.5.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.2
WooCommerce Checkout Manager: by QuadLayers – 7.2.8
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.2.1
WooCommerce PayPal Payments: by WooCommerce – 2.3.1
WooCommerce Shipping & Tax: by WooCommerce – 2.3.7
WooCommerce Waitlist: by Neil Pie – 2.3.5
WooCommerce: by Automattic – 8.2.1
WPML Media: by OnTheGoSystems – 2.7.3
WPML String Translation: by OnTheGoSystems – 3.2.8
YITH WooCommerce Badge Management: by YITH – 2.22.0
YITH WooCommerce Gift Cards: by YITH – 4.5.0
YITH WooCommerce Product Bundles Premium: by YITH – 2.0.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #145 - /negozio/
Carrello: #146 - /carrello/
Pagamento: #147 - /pagamento/
Il mio account: #148 - /mio-account/
Termini e condizioni: #999 - /termini-e-condizioni/

### Theme ###

Name: Avada
Version: 7.11.2
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Klarna Payments Request Log ###

2023-02-21 17:16:19: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:14:26: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:14:26: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:14:08: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:14:07: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:14:06: KP Place Order
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:13:11: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:10:40: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:10:40: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:10:37: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:10:37: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:09:45: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:09:45: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:09:13: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 17:09:13: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

### Klarna Countries ###

Production Countries: IT
Test Countries: No countries selected

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-27 11:28:19 +02:00
Options: ✔
Notes: 195
Onboarding: completed

### Action Scheduler ###

Operazione annullata: 528
Oldest: 2023-09-26 11:41:07 +0000
Newest: 2023-10-27 09:48:34 +0000

Completato: 48.459
Oldest: 2023-09-26 10:00:29 +0000
Newest: 2023-10-27 09:54:44 +0000

Operazione non riuscita: 49
Oldest: 2022-06-28 14:22:30 +0000
Newest: 2023-10-27 09:47:09 +0000

In attesa: 2
Oldest: 2023-10-27 18:33:56 +0000
Newest: 2023-10-27 18:33:56 +0000

### Status report information ###

Generated at: 2023-10-27 11:58:31 +02:00
`

**Comment by Sirvijver** [comment] 2023-10-30 15:00
Hello @AleBTstudio 

Since we did not receive any response or follow-up questions from you, we will assume you got this working to your requirements. If you still have any more questions for us, please open a new thread, because we will mark this one as resolved.

We did see some reports concerning shipping options that would not behave correctly while using our plugin, but have not yet confirmed any issue with our plugin. It is also not completely clear what the issue is you are reporting, so I would suggest creating a recording of the issue and try again to explain what the problem is you are facing. Testing your site, did not show me the exact issue (or maybe I don't understand what the intended behavior should be). I suggest using Loom to create an explanation.
Also, be sure to do [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/), to be sure this is not related to another plugin.

I will close this thread and wait for your engagement on our support tool.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-10-30 15:00 UTC
Labels: support
