### ISSUE TITLE
Capture not working

### ISSUE THREAD

**Issue by aussiemidwife** [woocommerce/woocommerce-paypal-payments#1309] opened 2023-04-13 22:59 UTC
### Describe the Bug

When processing a payment, you get to the final step after logging into Paypal (click and it wont process and says Invalid Captcha. 

### To Reproduce

1. Go to '…'
2. Click on complete purchase'
3. Scroll down to up to the top of the page'
4. See error - Invalid Captcha

### Screenshots
![image](https://user-images.githubusercontent.com/130710779/231897926-a745d2b9-6b28-4c8f-a5dd-79dbb1bf34c5.png)
![image](https://user-images.githubusercontent.com/130710779/231897614-438cb4cf-f615-41ad-a6e4-4fc6a7bc9cc0.png)
![image](https://user-images.githubusercontent.com/130710779/231897769-056d485a-b607-4dee-a6cc-3e143c5e26a1.png)

### Expected Behavior

payment complete

### Actual Behavior

payment will not process

### Environment

 - WordPress Version 6.2
 - WooCommerce Version 7.6.0
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version Chrome and Firefox
 - Any other plugins installedActiveCampaign Version 8.1.11 
ActiveCampaign for WooCommerce Version 2.1.0 
Akismet Version 5.1 
CleanTalk Version 6.8 
Australia Post WooCommerce Extension PRO 4.9.3 
Custom Product Tabs  5.5.10 
Event Tickets Plus Version 5.6.9 
Select ExtensionWorks Framework Version 2.1.20 
Facebook for WooCommerce Version 2.3.9 
Mastercard Payment Gateway Services Version 1.1
No CAPTCHA reCAPTCHA for WooCommerce Version 1.2.6 
Read More Pro Version 1.62 
reCaptcha for WooCommerce Version 2.38 
Remove Query Strings From Static Resources Version 1.4 
SearchWP Version 4.3.0 
Customizations for SearchWP Version 1.0.0
Integrate SearchWP Version 1.3.11 
The Events Calendar Version 6.0.12 
The Events Calendar Pro Version 6.0.11 
The Events Calendar: Filter Bar Version 5.4.4 
The Events Calendar: Virtual Events Version 1.13.6 
WooCommerce Back In Stock Notifications Version 1.2.0 
WooCommerce Blocks Version 10.0.0 
WooCommerce Brands Version 1.6.25 
WooCommerce Checkout Field Editor	
WooCommerce Checkout Field Editor Version 1.6.2 
WooCommerce Google Product Feed	
WooCommerce extension Version 10.2.0 
WooCommerce PayPal Payments Version 2.0.4 
WooCommerce Print Invoices/Packing Lists Version 3.11.3 
	
WooCommerce Product Bundles Version 6.12.2 
Woocommerce Products Per Page Version 1.2.7 
WooCommerce Shipment Tracking Version 1.6.28 	
Select Woocommerce Simple Storewide Sale Version 1.1.4 
Select WooCommerce Square Version 3.7.0 
Select WooCommerce Wholesale Prices
WooCommerce Extension Version 2.1.6.2 
Select WooSidebars Version 1.4.6 
WP Crontrol Version 1.15.2 
WP File Manager Version 7.1.8 
WPCode Lite Version 2.0.9 
YITH WooCommerce Ajax Search Version 1.29.0 
YITH WooCommerce Cart Messages Version 1.8.0 
YITH WooCommerce Request A Quote Premium Version 4.12.0 
YITH WooCommerce Wishlist Version 3.19.0 
Yoast Duplicate Post Version 4.5 
Yoast SEO Version 20.5 
Select Yoast SEO Premium

**Comment by Sirvijver** [comment] 2023-04-20 10:22
Hello @aussiemidwife 

Thank you for reaching out to us, however, we do not use GitHub for support purposes and I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you encounter seems to be caused by a plugin conflict so I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. 
Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you find the cause of this issue, please engage us via the instructions mentioned above. I will now close this support thread.

**Closed as completed by Sirvijver** 2023-04-20 10:22 UTC
Labels: support
