### ISSUE TITLE
Subscription migration layer - subscriptions with legacy ppec_paypal payment method fail to renew

### ISSUE THREAD

**Issue by giilby** [woocommerce/woocommerce-paypal-payments#2669] opened 2024-10-03 20:27 UTC
### Describe the Bug

The [docs for this plugin](https://woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/#im-using-woocommerce-subscriptions-and-have-customers-paying-via-paypal-standard-and/or-paypal-checkout-will-those-renewals-continue-to-work) indicate that WC subscriptions formerly paid via the old PayPal Checkout plugin should continue to renew successfully after the old plugin is replaced with this one. However, after doing so, our PayPal-paid subscriptions are not renewing, and instead go to the "On Hold" state without any warning or error messages.

I took it upon myself to do a bit of debugging, and I think I see the problem: `RenewalHandler.php:409` should additionally be checking if `$wc_order->get_payment_method() == PPECHelper::PPEC_GATEWAY_ID`. Since it currently doesn't, `process_order()` (which is downstream from `SubscriptionsHandler->process_renewal()`) doesn't even attempt to pay using the billing agreement token.

### To Reproduce

1. Start a subscription using the old "WooCommerce PayPal Checkout Gateway" plugin
2. Activate the newer "WooCommerce PayPal Payments" plugin and deactivate the old one.
3. Attempt to renew the subscription via the Subscription admin page

### Expected Behavior

WooCommerce Subscriptions started with the old PayPal Checkout plugin continue to renew after upgrading to the newer plugin (per https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-checkout-gateway-migration-layer)

### Actual Behavior

WooCommerce Subscriptions fail to renew -- payment is not even attempted -- and the subscriptions move to the "On Hold" state.

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.2
 - Plugin Version: 2.9.2

**Comment by SydeKrystian** [comment] 2024-10-08 05:10
Hello @giilby 

Thank you for reaching out and for the detailed explanation.  

We are aware of the issue regarding subscriptions previously paid via the PPEC plugin not renewing correctly. This has been an open issue for some time, but I can confirm that a developer has now been assigned to resolve it, and it is currently in progress. The fix should be available really soon.

We appreciate your patience and understanding as we work to resolve this.  

Kind Regards,  

Krystian

**Closed as completed by SydeKrystian** 2024-10-08 05:10 UTC
Labels: support

**Comment by croane** [comment] 2024-10-11 13:24
@SydeKrystian We are experiencing this problem on a high volume site as well. Some Paypal subscription orders end up going into status "Pending Payment" but the charge doesn't actually go through. Do we have an expected ETA for this fix? It would be great to have a patch we could apply if that is possible. Thanks!

**Comment by SydeKrystian** [comment] 2024-10-11 13:54
Hello @croane 

Thank you for reaching out.

It looks like you're reporting a different issue, but it’s a valid one, and we are aware of it. We are currently working on several fixes related to PayPal subscriptions, which should be included in the next plugin update.

Kind Regards,  
Krystian

**Comment by croane** [comment] 2024-10-15 18:15
@SydeKrystian Is this fixed in version 2.9.3 that was just released? Thanks for your hard work!

**Comment by croane** [comment] 2024-10-29 15:24
@SydeKrystian Any update on this?

**Comment by SydeKrystian** [comment] 2024-10-30 06:16
Hello @croane 

It looks like we've managed to resolve the issue with migrating subscriptions from the WooCommerce PayPal Checkout Payment Gateway to the PayPal Payments plugin. We've created a package that should fix this problem, and the update will also be included in the upcoming plugin update. 

You can install the package like any other plugin: [Subscription Migration Package](https://drive.google.com/uc?id=1ohYVNKC4T-k_JePrM_uGTla3_N7B62cB).

For more information about the problem you can check the pull request here: [PR #2699](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2699).

Let us know if the issue persists after installing the package. If you have any questions, feel free to reach out.

Kind Regards,
Krystian
