### ISSUE TITLE
"Could not retrieve order" occurring frequently

### ISSUE THREAD

**Issue by TDA-Holdings** [woocommerce/woocommerce-paypal-payments#1879] opened 2023-12-02 19:58 UTC
### Describe the Bug

Payment errors occur frequently since update from 2.4.0 to 2.4.1. The following note is created when a customer uses a credit card through PayPal advanced card processing:

"Could not retrieve order. Maybe it was already completed or this browser is not supported. Please check your email or try again with a different browser. CreditCardGateway.php:393 Order status changed from Pending payment to Failed."

Sometimes PayPal advanced payment gateway credit card entry fields do not appear at all.

### To Reproduce

I have attempted to duplicate the error using both Safari and Chrome, but PayPal advanced payment gateway credit card entry fields do not appear for me. (Different problem).

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version 6.4.1
 - WooCommerce Version 8.3.1
 - Plugin Version 2.4.1
 - Browser [e.g. Chrome, Safari] and Version Safari 17.1, Chrome 118.0.5993.117 (
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
`
### wp-core ###

version: 6.4.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3011
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/customer/www/boundlessoutfitters.com/public_html
wordpress_size: 2.24 GB (2407942498 bytes)
uploads_path: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/uploads
uploads_size: 1.14 GB (1226006457 bytes)
themes_path: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/themes
themes_size: 10.95 MB (11479735 bytes)
plugins_path: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/plugins
plugins_size: 309.16 MB (324175203 bytes)
database_size: 150.80 MB (158121984 bytes)
total_size: 3.84 GB (4127725877 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Storefront Child (storefront-child)
version: 1.0
author: Woo
author_website: http://woocommerce.com
parent_theme: Storefront (storefront)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, custom-logo, menus, html5, custom-background, custom-header, site-logo, title-tag, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-style, responsive-embeds, amp, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, starter-content, widgets, infinite-scroll
theme_path: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/themes/storefront-child
auto_update: Disabled

### wp-parent-theme ###

name: Storefront (storefront)
version: 4.5.3
author: Automattic
author_website: https://woocommerce.com/
theme_path: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/themes/storefront
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.1, author: the WordPress team (latest version: 1.3), Auto-updates disabled

### wp-plugins-active (38) ###

Admin Menu Editor: version: 1.12, author: Janis Elsts, Auto-updates enabled
Advanced AJAX Product Filters for WooCommerce: version: 1.6.4.5, author: BeRocket, Auto-updates enabled
Advanced Coupons for WooCommerce Free: version: 4.5.8.3, author: Rymera Web Co, Auto-updates enabled
Advanced Shipment Tracking for WooCommerce: version: 3.6.2, author: zorem, Auto-updates enabled
Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates enabled
Extra Product Options & Add-Ons for WooCommerce: version: 6.3.2, author: ThemeComplete, Auto-updates enabled
FiboSearch - AJAX Search for WooCommerce (Pro): version: 1.26.1, author: FiboSearch Team, Auto-updates enabled
GA Google Analytics: version: 20231101, author: Jeff Starr, Auto-updates enabled
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 10.2.16, author: HubSpot, Auto-updates enabled
Insert Pages: version: 3.7.7, author: Paul Ryan, Auto-updates enabled
Jetpack: version: 12.8.1, author: Automattic, Auto-updates enabled
Multi-Carrier Shippo Shipping Rates & Address Validation for WooCommerce: version: 1.5.9, author: OneTeamSoftware, Auto-updates enabled
MyRewards: version: 5.2.7, author: Long Watch Studio, Auto-updates enabled
Ninja Tables: version: 5.0.4, author: WPManageNinja LLC, Auto-updates enabled
PDF Invoices & Packing Slips for WooCommerce: version: 3.7.3, author: WP Overnight, Auto-updates enabled
Perfect Images (Optimize, Rebuild, Replace, Thumbnails, Retina): version: 6.4.9, author: Jordy Meow, Auto-updates enabled
Phone Orders for WooCommerce (Pro): version: 3.8.7, author: AlgolPlus, Auto-updates enabled
Pixel Manager for WooCommerce: version: 1.34.0, author: SweetCode, Auto-updates enabled
PublishPress Future: version: 3.1.3, author: PublishPress, Auto-updates enabled
Shippo Shipping PRO for WooCommerce: version: 2.1.13, author: OneTeamSoftware (latest version: 2.1.15), Auto-updates enabled
Speed Optimizer: version: 7.4.4, author: SiteGround, Auto-updates enabled
Storefront Footer Bar: version: 1.0.4, author: WooThemes, Auto-updates enabled
Storefront Hamburger Menu: version: 1.2.2, author: WooCommerce, Auto-updates enabled
Storefront Powerpack: version: 1.6.3, author: WooCommerce, Auto-updates enabled
UPS Live Rates and Access Points: version: 2.1.1, author: Octolize, Auto-updates enabled
USPS Simple Shipping for Woocommerce: version: 1.9.4, author: dangoodman, Auto-updates enabled
WooCommerce: version: 8.3.1, author: Automattic, Auto-updates enabled
WooCommerce Extra Fees Plugin: version: 3.9.5, author: theDotstore, Auto-updates enabled
WooCommerce PayPal Payments: version: 2.4.1, author: WooCommerce, Auto-updates enabled
WooCommerce Shipping & Tax: version: 2.4.2, author: WooCommerce, Auto-updates enabled
WooCommerce Stripe Gateway: version: 7.7.0, author: WooCommerce, Auto-updates enabled
WooCommerce Tiered Price Table: version: 4.0.7, author: u2Code, Auto-updates enabled
Wordfence Security: version: 7.11.0, author: Wordfence, Auto-updates enabled
WPForms Lite: version: 1.8.5.2, author: WPForms, Auto-updates enabled
WP Mail Logging: version: 1.12.0, author: WP Mail Logging Team, Auto-updates enabled
YITH WooCommerce Name Your Price: version: 1.3.0, author: YITH, Auto-updates enabled
Yoast SEO: version: 21.6, author: Team Yoast, Auto-updates enabled
Yoast SEO: WooCommerce: version: 15.8, author: Team Yoast (latest version: 15.9), Auto-updates enabled

### wp-plugins-inactive (2) ###

Storefront Blog Customiser: version: 1.3.0, author: WooCommerce, Auto-updates enabled
Storefront Pricing Tables: version: 1.1.0, author: WooCommerce, Auto-updates disabled

### code-snippets (2) ###

snippet-6: name: Edit Pending Orders in WooCommerce, scope: global, modified: 2021-09-02 21:40:50
snippet-7: name: Add missing countries, scope: global, modified: 2022-03-22 18:39:36

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.56.1

### wp-server ###

server_architecture: Linux 5.15.126-MCIclouder399 x86_64
httpd_software: Apache
php_version: 7.4.33 64bit
php_sapi: apache2handler
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.85.0 OpenSSL/3.0.9
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true
current: 2023-12-02T19:53:47+00:00
utc-time: Saturday, 02-Dec-23 19:53:47 UTC
server-time: 2023-12-02T14:53:45-05:00

### wp-database ###

extension: mysqli
server_version: 5.7.39-42-log
client_version: mysqlnd 7.4.33
max_allowed_packet: 33554432
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/customer/www/boundlessoutfitters.com/public_html/wp-content
WP_PLUGIN_DIR: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 128M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: 186307645
ssl_cert: No
time_diff: undefined
version_option: 12.8.1:1699909309
old_version: 12.8:1699296292
public: Public
master_user: 
is_offline_mode: off
is_offline_mode_constant: off
current_user:
tokens_set: Blog User
blog_token: 
user_token: 
version: 12.8.1
jp_plugin_dir: /home/customer/www/boundlessoutfitters.com/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: false
full_sync: {"started":"Tue, 21 Jun 2022 16:43:50 +0000","finished":"Tue, 21 Jun 2022 16:44:03 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1989"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1989],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/www.boundlessoutfitters.com","siteurl":"https:\/\/www.boundlessoutfitters.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### wpforms ###

version: 1.8.5.2
lite: 01-Dec-2020 at 12:16 pm
upload_dir: Writable
total_forms: 1
total_submissions: 782

`
  ```

</details>

**Comment by SydeKrystian** [comment] 2023-12-04 10:16
Hello @TDA-Holdings 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2023-12-04 10:16 UTC
Labels: support
