### ISSUE TITLE
Advanced card processing –  payment option keeps disappearing

### ISSUE THREAD

**Issue by BenJacobs04** [woocommerce/woocommerce-paypal-payments#1453] opened 2023-06-20 15:17 UTC
### Describe the Bug

credit/debit card option worked initially, then disappeared, leaving just the PayPal option. Going into advanced card processing options and just saving without changing anything brought it back. It has since gone again (noticed after a few weeks), and back again just by saving. Obviously I don't want to have to keep going back in to keep saving. 

### To Reproduce

As of the time of writing, it cant be reproduced as explained above. butikken.co.uk

### Expected Behavior

For two options to b available at checkout - 'PayPal' & 'Credit/Debit Cards', where you can enter your card details on the site.

### Actual Behavior

For no clear reason it disappears from the checkout section.

### Environment

 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.8.0
 - Plugin Version: 2.1.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome version 114.0.5735.133
 - Any other plugins installed: WooCommerce Shipping & Tax, WPBakery, others unrelated

### Additional Details

Using Impreza theme, though the plugin appears to be the issue.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment] 2023-06-20 16:25
Hi @BenJacobs04 
Since your report mentions update 2.1.0, I assume you faced the same issue as reported in #1432 after updating the plugin.
So I'll close this as a duplicate, but please reopen this issue if you find any other way of reproducing the reported behavior. Thanks!

**Closed as completed by InpsydeNiklas** 2023-06-20 16:25 UTC
Labels: duplicate
