### ISSUE TITLE
Many failed transactions with PayPal, starting February 7

### ISSUE THREAD

**Issue by goatcloud** [woocommerce/woocommerce-paypal-payments#1240] opened 2023-03-10 22:49 UTC
Here's what I've told my client:

I've reviewed orders. Since Feb 7 (when the issue appears to have started on the site), you've had 19 PayPal orders. 6 eventually processed. Of those six, only one processed as anticipated. The other 5 first triggered the PayPal error message. 13 failed. That's a horrible rate of success. See https://docs.google.com/spreadsheets/d/11PZSVTeASIh2XYPc8yWxMC3kCom0jWw2vQSWMqjb4ws/edit?usp=sharing

There appear to be no orders attempted to be paid with PayPal between Feb 6 and January 10. I did not check earlier orders.

I've also done some web searching and found that we are not the only ones having the problem. It appears to be an issue with the WooCommerce PayPal Payments plugin, which was last updated on or about January 31.

**Comment by Sirvijver** [comment] 2023-03-13 10:56
Hello @goatcloud 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I did take a look at the document you shared and see 2 possible causes:
1) Could not retrieve order - This failure occurs when the payment is attempted via our plugin, but the WooCommerce "order now" button is not being replaced (this should be done by a JavaScript, but can be blocked). Sometimes the theme or another plugin is blocking our plugin from replacing this action, and we would advise you to do [conflict testing](https://woocommerce.com/document/how-to-test-for-conflicts/) in order to find out if that is the case. 
2) Card payment failure - There seems to have been some issues with the Standard Card Processing payment option since the date you mentioned, but that seems to have improved already. I don't have any details on your site, so I cannot check if you are using the standard or advanced option on our plugin. If this was the cause of your problem, it should already have improved, but item #1 is a more obvious cause for the errors shown in Excel you shared with us.

Hopefully this will help you resolve this issue.

We will now close this support request and advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-03-13 10:56 UTC
Labels: support
