### ISSUE TITLE
customers unable to proceed to PayPal at checkout

### ISSUE THREAD

**Issue by austinucr22** [woocommerce/woocommerce-paypal-payments#1079] opened 2022-12-12 16:24 UTC
### Describe the Bug
customers are unable to proceed to PayPal at checkout when they have selected to "subscribe and save." Buy Once or Subscribe plugin is being used as an extension of woo commerce subscriptions.
Customers are only able to purchase subscriptions via PayPal because it is our only gateway that supports recurring payments. I think it has something to do with PayPal. PayPal support team has informed me that it may have something to do with the theme. I am running a twenty eleven child them. Subscriptions were functioning fine during the beginning of downloading the plugin.

### To Reproduce

1. Go to https://uncommoncoffeeroasters.com/product/holiday-blend/
2. Choose random  "weight" and "grind" option
3. Click "Subscribe and save up to 15%" radio button
4. select random frequency
5. Click "sign up now"
6. "click view cart" at top of page
7. click "proceed to checkout" 
8. scroll down to bottom of page where PayPal section is not working

### Screenshots

<
<img width="1168" alt="Screenshot 2022-12-12 at 11 14 16 AM" src="https://user-images.githubusercontent.com/120401943/207096524-8dfdce73-988e-4117-b954-9a32f8b38f76.png">
>

### Expected Behavior

<A PayPal button should appear to direct them to pay on the PayPal website>

### Actual Behavior

<A loading wheel continues to spin where the PayPal button should be>

### Environment

 - WordPress 6.1.1 
 - WooCommerce Version 7.1.1
 - Plugin Version 7.1.1
 - Chrome
 - Active plugins installed:
 - Acowebs Product Labels For Woocommerce
 - Advanced Local Pickup for WooCommerce
 - All in One SEO
 - Backup Duplicator & Migration - WP STAGING
 - Buy Once or Subscribe for WooCommerce Subscriptions
 - Custom Emails for WooCommerce
 - Facebook Chat Plugin - Live Chat Plugin for WordPress
 - Facebook for WooCommerce
 - Fullwidth Page Templates
 - Google Analytics Dashboard for WP (GADWP)
 - Google XML Sitemaps
 - Gravity Forms
 - Groups
 - Groups Restrict Categories
 - Huge IT Slider
 - Image Slider Block
 - Import and export users and customers
 - Improved Plugin Installation
 - Itthinx Updates
 - Jetpack
 - Mailchimp for WooCommerce
 - NextMove Lite - Thank You Page for WooCommerce
 - Order Delivery Date for WooCommerce (Lite version)
 - PickPlugins Product Slider for WooCommerce
 - Popup Maker
 - Product Import Export for WooCommerce
 - PW WooCommerce Gift Cards
 - Redirection
 - Regenerate Thumbnails
 - Simple Lightbox
 - Smart Coupons For WooCommerce Coupons
 - UpdraftPlus - Backup/Restore
 - Woo - iCheckGateway - Credit Card
 - WooCommerce
 - WooCommerce - Gift Cards
 - WooCommerce - ShipStation Integration
 - WooCommerce Advanced Free Shipping
 - WooCommerce Colors
 - WooCommerce Custom Product Addons (Free)
 - WooCommerce PayPal Payments
 - WooCommerce Shipping & Tax
 - WooCommerce Subscriptions
 - WP Gallery Custom Links
 - WP Responsive Menu
 - WPS Hide Login
 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2022-12-13 09:58
Hello @austinucr22 

Thank you for reaching out to us, we are here to help.
The issue you are encountering is a fairly common issue. Our plugin is trying to display the PayPal button, but something is blocking it from doing. To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

Since we don't actually provide plugin support via GitHub, I will close this thread. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 09:58 UTC
Labels: support
