### ISSUE TITLE
missing_shipping_address the shipping address is required when `shipping_preference=set_provided_address`

### ISSUE THREAD

**Issue by periscopistudio** [woocommerce/woocommerce-paypal-payments#1399] opened 2023-05-22 10:20 UTC
### Describe the Bug

When I go to pay with PayPal I get this error. IT'S ALL COMPLETED
"missing_shipping_address the shipping address is required when `shipping_preference=set_provided_address`"

### To Reproduce

1. Go to 'cart' with a product
2. Click 'Pay with PayPal'
3. Click on accept privacy policy
4.View error

![WhatsApp Image 2023-05-22 at 11 21 56](https://github.com/woocommerce/woocommerce-paypal-payments/assets/126253829/54bf9532-b6ba-4a0f-a445-7c74b812546f)

### Environment

 - WordPress Version - 6.2.2
 - WooCommerce Version - 7.7.0
 - Plugin Version - 2.0.4
 - Browser [e.g. Chrome, Safari] and Version - chrome 113.0.5672.127 
 - Any other plugins installed - Adapta RGPD, Code snippets, divi mini cart, divi shop builder, facebook for woocommerce, pinterest for woocommerce, really simple ssl, scroll to top, seguimiento de envíos en woocommerce, simple custom css and js, smash ballon instagram feed, stock manager for woocommerce, woocommerce, woocomercce advanced free shipping, woocommerce paypal payments, woocommerce stripe gateway, yoast seo, 
 
<body>

</body>
</html>

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-05-22 11:27
Hello @periscopistudio ,

Thank you for reaching out to us, I will provide you with a response, but we would need to ask you to open a support request with out support team, because we don't provide plugin support via GitHub.

We have seen this issue more in the past, but there is not really 1 cause for this error, but it is almost always caused by a plugin conflict.

To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. (Some encountered problematic plugins were the Divi plugin/theme and the Germanized plugin).

Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

If you require additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). We will now close this thread.

Kind regards,
Joost

**Closed as completed by Sirvijver** 2023-05-22 11:27 UTC
Labels: support
