### ISSUE TITLE
The plugin is showing non-working reginal payment methods

### ISSUE THREAD

**Issue by afstudios** [woocommerce/woocommerce-paypal-payments#816] opened 2022-09-02 17:01 UTC
### Describe the Bug

When buyers from some parts of the world want to pay with PayPal, their local services appear under the PayPal checkout button, so when they use it no order is created but the money is taken from their accounts.

### To Reproduce

Use the VPN and set it to Poland, then go to our website: www.dynamix-audio.com, put some products into cart, and there some przelewy24 service will appear.

**Comment by dev-vip** [comment] 2022-09-02 17:13
Same for 'Pay in 3' it shows to customers worldwide, **should be UK only**, tested via vpn from multiple locations..  Seems a particular locale SDK is being set @ Woo?  are you trying to use the geolocate feature to do that or just setting a region?  Seems that it's the plugin itself causing these issues.

I confirmed with PayPal technical support that PayPal are geolocating the services, yet that's not what we see on the front end, seems the SDK locale is being set or forced, when it shouldn't be set, PayPal set it.  (aside the settings in the plugin are all sloppy and don't function since last update so it cant even be disabled.)  

So many open bugs..

**Comment by Sirvijver** [comment] 2022-12-15 08:51
Hello @afstudios 

Alternative payment methods such as iDEAL are push payments, so it will debit the customer's bank account as soon as they have authorized/approved the payment.
If the merchant doesn't capture this payment, it will be refunded automatically after 3 hours. Depending on the bank, the buyer should see the refund in a few days, as SEPA transactions take a day to process.
When no order has been created in WooCommerce, then PayPal Payments will also not have captured the payment and so no funds will be added to the merchant account.
The only scenarios in which I could see this happen are either when the webhooks are not registered, or the buyer did not correctly complete the checkout process as described in this issue: https://github.com/woocommerce/woocommerce-paypal-payments/issues/513

This issue should not occur as much as it did in the past, since we improved our plugin to avoid this with our 2.0.0 release. However, if you still encounter this issue and need additional support, we advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Our team only uses GitHub for development and does not provide plugin support here. This is the reason why we will close this issue.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-15 08:51 UTC
