### ISSUE TITLE
Checkout page paypal button is missing/hide

### ISSUE THREAD

**Issue by Pradeepraj56** [woocommerce/woocommerce-paypal-payments#1474] opened 2023-06-28 17:09 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-06-29 12:56
Hello @Pradeepraj56 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering is most of the time caused by a conflicting plugin or theme that is blocking the JavaScript that is intended to change the button from performing its function. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

Another option is that the checkout page is not using the correct short codes for the page. You can test this by making a 2nd checkout page and only adding the short code [woocommerce_checkout]. If the button shows on this page, then you know the page you are currently using is not codes correctly and this needs to be adjusted.

If you none of this helps you resolve this issue, please open a new support ticket as described above. We will close this ticket.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-06-29 12:56 UTC
Labels: support
