### ISSUE TITLE
Processing PH 222 error failed orders 

### ISSUE THREAD

**Issue by Rainwebdeveloper** [woocommerce/woocommerce-paypal-payments#2216] opened 2024-05-09 22:11 UTC
<img width="307" alt="error message" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/169405779/7dfb5ce2-b3b6-4c2f-977f-a63484a91b38">
### Describe the Bug

2024-05-09T22:06:08+00:00 Critical Uncaught Error: Call to a member function get_tax_price_display_mode() on null in /home/customer/www/raindance.org/public_html/wp-content/plugins/woocommerce-checkout-add-ons/src/Add_Ons/Add_On.php:417 CONTEXT: {"error":{"type":1,"file":"\/home\/customer\/www\/raindance.org\/public_html\/wp-content\/plugins\/woocommerce-checkout-add-ons\/src\/Add_Ons\/Add_On.php","line":417},"backtrace":["","#0 \/home\/customer\/www\/raindance.org\/public_html\/wp-content\/plugins\/woocommerce-checkout-add-ons\/src\/Frontend\/Frontend.php(399): SkyVerge\\WooCommerce\\Checkout_Add_Ons\\Add_Ons\\Add_On->get_cost_html('', '')","#1 \/home\/customer\/www\/raindance.org\/public_html\/wp-includes\/class-wp-hook.php(324): SkyVerge\\WooCommerce\\Checkout_Add_Ons\\Frontend\\Frontend->add_checkout_fields(Array)","#2 \/home\/customer\/www\/raindance.org\/public_html\/wp-includes\/plugin.php(205): WP_Hook->apply_filters(Array, Array)","#3 \/home\/customer\/www\/raindance.org\/public_html\/wp-content\/plugins\/woocommerce-payments\/includes\/admin\/class-wc-rest-payments-settings-controller.php(1112): apply_filters('woocommerce_che...', Array)","#4 \/home\/customer\/www\/raindance.org\/public_html\/wp-content\/plugins\/woocommerce-payments\/includes\/admin\/class-wc-rest-paymen"]}

Possible conflic with plugin

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by ToeiRei** [comment] 2024-05-11 16:45
Looks like a plugin conflict to me.

**Comment by InpsydeNiklas** [comment] 2024-05-13 12:33
Hi @Rainwebdeveloper, the message in the order note comes from the PayPal Payments plugin for sure, but it's not possible to pinpoint the cause of this without more context. In the end, the API call to PayPal was incomplete, but it's not clear why. For example, the stack trace you included points to the `woocommerce-payments` and `woocommerce-checkout-add-ons` which could potentially interfere with the checkout process.
If you can reproduce this error when performing payments via PayPal Payments, I recommend temporarily deactivating both  `woocommerce-payments` and `woocommerce-checkout-add-ons` and trying it again to check if the behavior persists.
You can find advanced troubleshooting steps in the [wiki here](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Advanced-Troubleshooting#test-on-staging). But if you still need assistance with resolving the issue, I recommend contacting the plugin support team from here with additional details about the problem your facing, like for example steps to reproduce: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!

**Closed as completed by InpsydeNiklas** 2024-05-13 12:33 UTC
Labels: support
