### ISSUE TITLE
Payment portal not displaying Credit Card payment button option

### ISSUE THREAD

**Issue by thomwise** [woocommerce/woocommerce-paypal-payments#1359] opened 2023-05-09 05:24 UTC
### Describe the Bug

There is no way to make the credit card payment button display on our website.

### To Reproduce

1. Go to https://www.medministries.org/shop 
2. Click add to cart on any product.
3. Click cart icon in navigation bar.
4. See error that only paypal button is available even though Paypal, Venmo and Credit card buttons should be displayed based on all documentation and criteria.

### Screenshots

Only seeing this:
<img width="600" alt="Screenshot 2023-05-08 at 10 17 14 PM" src="https://user-images.githubusercontent.com/25626786/237000667-d24442da-3850-4c5c-a87b-a0a3e66a3085.png">

### Expected Behavior

Should see this:
<img width="425" alt="Screenshot 2023-05-08 at 10 13 00 PM" src="https://user-images.githubusercontent.com/25626786/237000479-2ef83e24-ccc0-4aeb-bfac-18df0fbaeaa5.png">

### Actual Behavior

There should be multiple button options for payment processing.

### Environment

 - WordPress Version: 6.2
 - WooCommerce Version: 7.6.1
 - Plugin Version: 2.0.4
 - Browser [e.g. Chrome, Safari] and Version: Edge Version 112.0.1722.68 
 - Any other plugins installed:

1.  WooCommerce Shipping & Tax
2. WordPress Importer
3. WP Post Page Clone
4. The Events Calendar
5. Popup Maker
6. Jetpack
7. Gravity Forms
8. Google Listings and Ads
9. Contact Form 7
10. Classic Editor
11. Avada Core
12. Avada Builder
13. Akismet Anti-Spam
14. Add Categories to Pages.

### Additional Details

NA

<details><summary>System status</summary>

NA

</details>

**Comment by Sirvijver** [comment] 2023-05-09 12:21
Hello @thomwise 

Both the Advanced Card Processing and the Standard Card Processing payment methods can only be shown on the checkout page (this is not possible on the product or cart pages). I have taken a look at the shopping process and do see both these card options on the checkout page, so I believe this is working as intended:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/0a2c242d-c7c1-4d2f-af66-7cd22c3ae5d2)

You can only display the Pay Later payment method on the product and cart page next to the PayPal payment method.

We only use GitHub for development activities, so we will close this support request. If you have more questions, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-05-09 12:21 UTC
Labels: support

**Comment by thomwise** [comment] 2023-05-09 18:31
@Sirvijver,

I am a developer and have been working with Woocommerce for the past two years and read through as much documentation on this as I could. No where that I found did it state that the cart page does not have the ability to display a credit card button option. In fact, in the Admin dashboard you can see very clearly it shows a preview of what you should be able to see on the cart page. If this is not the case, it is very confusing for anyone attempting to use the platform and as a programmer myself, I would look into either updating the documentation or creating a "preview" to display what it actually can or cannot do.

<img width="1593" alt="Screenshot 2023-05-09 at 11 24 13 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/25626786/09381b92-67a8-4d79-883f-c0332f887e7a">

I am only trying to help alleviate confusion for users attempting to utilize this feature in the future.

Thank you,
Thomas

**Comment by InpsydeNiklas** [comment] 2023-05-10 10:23
Hi @thomwise 
Thanks for your suggestion.
Details about the button availability may be scattered a bit across the documentation, but it's referenced here: https://woocommerce.com/document/woocommerce-paypal-payments/#APMs-on-non-checkout-pages
and briefly mentioned here: https://woocommerce.com/document/woocommerce-paypal-payments/#default-credit-card-smart-button

Also, while it is not specifically mentioned within the plugin settings, the button previews primarily serve as an indicator for the available styling settings: https://woocommerce.com/document/woocommerce-paypal-payments/#button-on-checkout
These button previews do not necessarily represent the payment methods that may or may not be visible in the respective button location when `Customize smart button style per location` is checked.

The fact that all APM buttons and the Debit or Credit Card button display for all button preview locations is based on a technical limitation. It is not easily achievable to only display certain buttons in certain locations while on the same page.
The same limitation exists in the frontend, e.g. when you enable the Pay Later button for the single product page but not for the Mini Cart (PayPal button is enabled though). While on the single product page, the Mini Cart may also display the Pay Later button, despite not being enabled for this location. Same vice-versa.
The only alternative would be hiding the non-PayPal buttons for _all_ location previews, but that would defeat the purpose of the preview. A description for the previews was tested, but this was cluttering the UI.

In any case, the team is always looking into improving the documentation and plugin settings, and for questions or suggestions about the plugin setup ordocumentation, we recommend [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by sg5web** [comment] 2023-05-11 08:06
Hi @InpsydeNiklas ,
We have the same issue - we would need that button on the cart page. Just to let you know, the old "WooCommerce PayPal Checkout Gateway"-Plugin (https://woocommerce.com/document/paypal-express-checkout/) did show the button on the cart page, so I think it might be technically possible?

**Comment by InpsydeNiklas** [comment] 2023-05-15 10:37
@sg5web In theory, displaying this button on non-Checkout pages is possible, and that's what some other PayPal integration, like the old PayPal Checkout Gateway plugin, may do. 

However, this was often causing user experience problems and with the current PayPal Payments plugin, the button is intentionally designed to appear only on the Checkout page. 
If this button on the Cart page is a deciding factor for you, you might want to consider alternative PayPal integrations that offer this feature. 

Card payments are still possible from the single product page via the PayPal button, provided guest payments are enabled in your PayPal account and/or the landing page is set to `Billing` (`Login` works too, though). However, regular card payment options like the Standard Card Button or Advanced Card Processing are only available from the Checkout page as mentioned in the linked documentation.
