### ISSUE TITLE
Blocked when deactivating

### ISSUE THREAD

**Issue by millerf** [woocommerce/woocommerce-paypal-payments#2848] opened 2024-11-27 16:19 UTC
### Describe the Bug

deactivate window does not scroll down and the plugin cannot be deactivated

### To Reproduce

1. Activate the plugin
2. Deactivate the plugin
3. Do not fill and click deactivate

### Screenshots

![Image](https://github.com/user-attachments/assets/d0168c58-1414-4d72-a966-a56a69dc0938)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-11-28 06:43
Hello @millerf 

Could you please clarify whether this issue is specifically related to the PayPal Payments plugin or WooPayments? Which gateway are you trying to deactivate?

I'm looking forward to your response.

Kind regards,
Krystian

**Comment by millerf** [comment] 2024-11-28 12:05
> Could you please clarify whether this issue is specifically related to the PayPal Payments plugin or WooPayments? Which gateway are you trying to deactivate?

I got this modal when disabling `PayPal Payments`, not WooPayments. Sorry I just noticed the WooPayments logo!

**Comment by InpsydeNiklas** [comment] 2024-12-27 13:35
We are unable to reproduce this behavior. 
This popup modal only appears when disabling the WooPayments plugin, and not when disabling PayPal Payments (while the WooPayments plugin is active). So I will close this issue as not reproducible for now.

**Closed as completed by InpsydeNiklas** 2024-12-27 13:35 UTC
Labels: woo-compatibility, cannot-reproduce
