### ISSUE TITLE
payment error WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by zoltan35nemphys** [woocommerce/woocommerce-paypal-payments#1666] opened 2023-09-05 08:34 UTC
### Describe the Bug
after the latest update of woo commerce and theme update i cant accept payments. The error:
Could not retrieve order. Maybe it was already completed or this browser is not supported. Please check your email or try again with a different browser.
I looked for js conflict but did not find anything. Pls help. 

### To Reproduce

1. Go to 'nemphys.com'
2. Click on 'select product '
3. Scroll down to "try to order'

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/144107844/8f6e335f-84f3-4b99-9f1a-ea0b2320a453)

 - WordPress Version 6.3.1 
 - WooCommerce Version 8.0.3 
 - Plugin Version 8.0.3 
 - Browser all types
 - Any other plugins installed

</details>

**Comment by Sirvijver** [comment] 2023-09-05 11:34
Hello @zoltan35nemphys 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered is caused by the fact that the PayPal button is not being shown on the checkout page. In your checkout page, we are seeing this button:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/fe823d33-e63c-4674-b6f5-85ddb466f163)
Instead we should be seeing this type of button: 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/0b119af4-7cc7-40a9-9d13-7d46a81fc44f)

Often this situation is caused by the theme or some plugin blocking the JavaScript that performs the button replacement. In this situation, I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We will close this thread. If you require additional support, please open a new support thread as advised above.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-09-05 11:34 UTC
Labels: support
