### ISSUE TITLE
Type check error caused by potential plugin conflict (780)

### ISSUE THREAD

**Issue by Narek13** [woocommerce/woocommerce-paypal-payments#730] opened 2022-07-14 15:17 UTC
### Describe the Bug

Recently we have received a report about the following error:

```
Fatal error: Uncaught TypeError: WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRenderer::render_multiselect(): Return value must be of type string, null returned in /var/www/vhosts/stage.gaco.netz.rocks/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/SettingsRenderer.php:178
```

This is because of a conflict with other plugin which is using the same `filter/action`
A decision was made to implement the WPHookProxyTrait to be used as a proxy for WordPress defined callbacks.
The error will not break the site (If WP_DEBUG is false), instead, the fields which are invalid will not be displayed and the error info will be added to logs.

### To Reproduce

1. Put the following filter in active theme’s functions.php file

```
add_filter(
    'woocommerce_form_field',
    static function ( $field, $key, $args, $value ) {
        //var_dump($args['type']);
        if ( 'text' === $args['type'] ) {
            return null;
        }
        return $field;
    },
    1,
    4
);
```
This will trigger the similar conflict described above

2. Check the settings page and see the error

### Expected Behavior

Plugin settings page loaded correctly( missing only the conflicted ones ). The logs are added in WC logs.

### Actual Behavior

Plugin settings page is broken because of the error.

**Comment by sun** [comment] 2022-07-26 14:24
@Narek13 Can you delete the screenshot from this public issue, please?

> This is because of a conflict with other plugin which is using the same `filter/action`

I'm part of the team that reported this bug and I'm not able to confirm this statement.  The Call Stack of the PHP Fatal Error shows that WooCommerce (Core) is calling the payment gateway callback functions of WooCommerce PayPal Payments directly in order to generate the settings page.

PHP is rightfully complaining about a diverging return data type hint.  That's all that needs correcting.

https://github.com/woocommerce/woocommerce-paypal-payments/pull/749 fixes the problem.

**Comment by sun** [comment] 2022-07-26 14:40
Here is the full stack trace for `$field === null`:

```
#0  WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRenderer->render_table(, ppcp[merchant_email_production], Array ([type] => text,[label] => ,[description] => ,[placeholder] => ,[maxlength] => ,[required] => 1,[autocomplete] => ,[id] => ppcp-merchant_email_production,[class] => Array ([0] => validate-required),[label_class] => Array (),[input_class] => Array (),[return] => ,[options] => Array (),[custom_attributes] => Array (),[validate] => Array (),[default] => ,[autofocus] => ,[priority] => ,[title] => Live-E-Mail-Adresse,[classes] => Array ([0] => ,[1] => ppcp-always-shown-element),[desc_tip] => 1,[screens] => Array ([0] => 0,[1] => 8),[requirements] => Array (),[gateway] => paypal), ) called at [/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php:335]
#1  WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(, ppcp[merchant_email_production], Array ([type] => text,[label] => ,[description] => ,[placeholder] => ,[maxlength] => ,[required] => 1,[autocomplete] => ,[id] => ppcp-merchant_email_production,[class] => Array ([0] => validate-required),[label_class] => Array (),[input_class] => Array (),[return] => ,[options] => Array (),[custom_attributes] => Array (),[validate] => Array (),[default] => ,[autofocus] => ,[priority] => ,[title] => Live-E-Mail-Adresse,[classes] => Array ([0] => ,[1] => ppcp-always-shown-element),[desc_tip] => 1,[screens] => Array ([0] => 0,[1] => 8),[requirements] => Array (),[gateway] => paypal), ) called at [/wp-includes/class-wp-hook.php:307]
#2  WP_Hook->apply_filters(, Array ([0] => ,[1] => ppcp[merchant_email_production],[2] => Array ([type] => text,[label] => ,[description] => ,[placeholder] => ,[maxlength] => ,[required] => 1,[autocomplete] => ,[id] => ppcp-merchant_email_production,[class] => Array ([0] => validate-required),[label_class] => Array (),[input_class] => Array (),[return] => ,[options] => Array (),[custom_attributes] => Array (),[validate] => Array (),[default] => ,[autofocus] => ,[priority] => ,[title] => Live-E-Mail-Adresse,[classes] => Array ([0] => ,[1] => ppcp-always-shown-element),[desc_tip] => 1,[screens] => Array ([0] => 0,[1] => 8),[requirements] => Array (),[gateway] => paypal),[3] => )) called at [/wp-includes/plugin.php:191]
#3  apply_filters(woocommerce_form_field, , ppcp[merchant_email_production], Array ([type] => text,[label] => ,[description] => ,[placeholder] => ,[maxlength] => ,[required] => 1,[autocomplete] => ,[id] => ppcp-merchant_email_production,[class] => Array ([0] => validate-required),[label_class] => Array (),[input_class] => Array (),[return] => ,[options] => Array (),[custom_attributes] => Array (),[validate] => Array (),[default] => ,[autofocus] => ,[priority] => ,[title] => Live-E-Mail-Adresse,[classes] => Array ([0] => ,[1] => ppcp-always-shown-element),[desc_tip] => 1,[screens] => Array ([0] => 0,[1] => 8),[requirements] => Array (),[gateway] => paypal), ) called at [/wp-content/plugins/woocommerce/includes/wc-template-functions.php:2968]
#4  woocommerce_form_field(ppcp[merchant_email_production], Array ([type] => text,[label] => ,[description] => ,[placeholder] => ,[maxlength] => ,[required] => 1,[autocomplete] => ,[id] => ppcp-merchant_email_production,[class] => Array ([0] => validate-required),[label_class] => Array (),[input_class] => Array (),[return] => ,[options] => Array (),[custom_attributes] => Array (),[validate] => Array (),[default] => ,[autofocus] => ,[priority] => ,[title] => Live-E-Mail-Adresse,[classes] => Array ([0] => ,[1] => ppcp-always-shown-element),[desc_tip] => 1,[screens] => Array ([0] => 0,[1] => 8),[requirements] => Array (),[gateway] => paypal), ) called at [/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/SettingsRenderer.php:431]
#5  WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRenderer->render() called at [/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayPalGateway.php:334]
#6  WooCommerce\PayPalCommerce\WcGateway\Gateway\PayPalGateway->generate_ppcp_html(ppcp, Array ([type] => ppcp,[default] => )) called at [/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php:333]
#7  WC_Settings_API->generate_settings_html(Array ([ppcp] => Array ([type] => ppcp,[default] => )), ) called at [/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php:87]
#8  WC_Settings_API->admin_options() called at [/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php:195]
#9  WC_Payment_Gateway->admin_options() called at [/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php:105]
#10 WC_Settings_Payment_Gateways->run_gateway_admin_options(WooCommerce\PayPalCommerce\WcGateway\Gateway\PayPalGateway Object ([*settings_renderer] => WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRenderer Object ([*settings_status] => WooCommerce\PayPalCommerce\WcGateway\Helper\SettingsStatus Object ([*settings] => WooCommerce\PayPalCommerce\WcGateway\Settings\Settings Object ([WooCommerce\PayPalCommerce\WcGateway\Settings\Settingssettings] => Array ())),[WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRenderersettings] => WooCommerce\PayPalCommerce\WcGateway\Settings\Settings Object ([WooCommerce\PayPalCommerce\WcGateway\Settings\Settingssettings] => Array ([title] => ,[description] => ,[button_single_product_enabled] => 1,[button_mini-cart_enabled] => ,[button_cart_enabled] => 1,[brand_name] => ,[dcc_gateway_title] => Kreditkarten,[dcc_gateway_description] => Bezahle mit deiner Kreditkarte.,[ppcp-onboarding-pui] => ,[sandbox_on] => 1,[products_dcc_enabled] => ,[products_pui_enabled] => 1,[client_secret_sandbox] => redacted,[client_id_sandbox] => redacted,[client_secret] => redacted,[client_id] => redacted,[disable_funding] => Array (),[merchant_id] => redacted,[merchant_email] => ,[merchant_id_sandbox] => redacted,[merchant_email_sandbox] => ,[merchant_email_production] => ,[merchant_id_production] => ,[client_id_production] => ,[client_secret_production] => ,[intent] => capture,[capture_for_virtual_only] => ,[payee_preferred] => ,[landing_page] => LOGIN,[vault_enabled] => ,[logging_enabled] => ,[prefix] => ,[button_enabled] => 1,[button_layout] => vertical,[button_tagline] => 1,[button_label] => paypal,[button_color] => gold,[button_shape] => rect,[message_enabled] => 1,[message_layout] => text,[message_logo] => primary,[message_position] => left,[message_color] => black,[message_flex_color] => blue,[message_flex_ratio] => 1x1,[button_product_enabled] => 1,[button_product_layout] => horizontal,[button_product_tagline] => 1,[button_product_label] => paypal,[button_product_color] => gold,[button_product_shape] => rect,[message_product_enabled] => 1,[message_product_layout] => text,[message_product_logo] => primary,[message_product_position] => left,[message_product_color] => black,[message_product_flex_color] => blue,[message_product_flex_ratio] => 1x1,[button_cart_layout] => horizontal,[button_cart_tagline] => 1,[button_cart_label] => paypal,[button_cart_color] => gold,[button_cart_shape] => rect,[message_cart_enabled] => 1,[message_cart_layout] => text,[message_cart_logo] => primary,[message_cart_position] => left,[message_cart_color] => black,[message_cart_flex_color] => blue,[message_cart_flex_ratio] => 1x1,[button_mini-cart_layout] => vertical,[button_mini-cart_tagline] => ,[button_mini-cart_label] => paypal,[button_mini-cart_color] => gold,[button_mini-cart_shape] => rect,[button_mini-cart_height] => 35,[enabled] => 1,[dcc_enabled] => 1)),[WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRendererstate] => WooCommerce\PayPalCommerce\Onboarding\State Object ([WooCommerce\PayPalCommerce\Onboarding\Statesettings] => WooCommerce\PayPalCommerce\WcGateway\Settings\Settings Object ([WooCommerce\PayPalCommerce\WcGateway\Settings\Settingssettings] => Array ([title] => ,[description] => ,[button_single_product_enabled] => 1,[button_mini-cart_enabled] => ,[button_cart_enabled] => 1,[brand_name] => ,[dcc_gateway_title] => Kreditkarten,[dcc_gateway_description] => Bezahle mit deiner Kreditkarte.,[ppcp-onboarding-pui] => ,[sandbox_on] => 1,[products_dcc_enabled] => ,[products_pui_enabled] => 1,[client_secret_sandbox] => redacted,[client_id_sandbox] => redacted,[client_secret] => redacted,[client_id] => redacted,[disable_funding] => Array (),[merchant_id] => redacted,[merchant_email] => ,[merchant_id_sandbox] => redacted,[merchant_email_sandbox] => ,[merchant_email_production] => ,[merchant_id_production] => ,[client_id_production] => ,[client_secret_production] => ,[intent] => capture,[capture_for_virtual_only] => ,[payee_preferred] => ,[landing_page] => LOGIN,[vault_enabled] => ,[logging_enabled] => ,[prefix] => ,[button_enabled] => 1,[button_layout] => vertical,[button_tagline] => 1,[button_label] => paypal,[button_color] => gold,[button_shape] => rect,[message_enabled] => 1,[message_layout] => text,[message_logo] => primary,[message_position] => left,[message_color] => black,[message_flex_color] => blue,[message_flex_ratio] => 1x1,[button_product_enabled] => 1,[button_product_layout] => horizontal,[button_product_tagline] => 1,[button_product_label] => paypal,[button_product_color] => gold,[button_product_shape] => rect,[message_product_enabled] => 1,[message_product_layout] => text,[message_product_logo] => primary,[message_product_position] => left,[message_product_color] => black,[message_product_flex_color] => blue,[message_product_flex_ratio] => 1x1,[button_cart_layout] => horizontal,[button_cart_tagline] => 1,[button_cart_label] => paypal,[button_cart_color] => gold,[button_cart_shape] => rect,[message_cart_enabled] => 1,[message_cart_layout] => text,[message_cart_logo] => primary,[message_cart_position] => left,[message_cart_color] => black,[message_cart_flex_color] => blue,[message_cart_flex_ratio] => 1x1,[button_mini-cart_layout] => vertical,[button_mini-cart_tagline] => ,[button_mini-cart_label] => paypal,[button_mini-cart_color] => gold,[button_mini-cart_shape] => rect,[button_mini-cart_height] => 35,[enabled] => 1,[dcc_enabled] => 1))),[WooCommerce\PayPalCommerce\WcGateway\Settings\SettingsRendererfields] => Array ([ppcp_onboarading_header] => Array ([type] => ppcp-text,[classes] => Array ([0] => ppcp-onboarding-element),[text] => 
```

**Comment by AlexP11223** [comment] 2022-07-26 14:54
@sun 

> The Call Stack of the PHP Fatal Error shows that WooCommerce (Core) is calling the payment gateway callback functions of WooCommerce PayPal Payments directly in order to generate the settings page.

Yes, but the error occurs because the `$field` parameter is `null`, which seems quite unusual and probably caused by some plugin/theme. According to the `woocommerce_form_field` [phpdoc](https://github.com/woocommerce/woocommerce/blob/6627fdb5ed52e907b17a3846d1127c9a646a9236/plugins/woocommerce/includes/wc-template-functions.php#L2736) it is not supposed to return `null` and it sets `$field` to empty string by default.

But yeah, I guess we need to apply the #749 solution.

Do you see all settings fields after that? It sounds like some standard inputs (email, checkboxes, ...) may be missing if the `$field` was `null` and not changed by one of our field renderers. Though maybe not if it becomes `null` only for non-standard types.

**Comment by sun** [comment] 2022-07-26 16:27
The settings page appears fine and no form fields seem to be missing, yes.

I posted a stack trace on the corresponding issue. The value appears to be null from the start.

**Comment by sun** [comment] 2022-07-27 08:50
After being able to use the setup wizard, we just identified that there are various settings fields missing on the following regular settings page of the plugin.

**Comment by AlexP11223** [comment] 2022-07-27 08:58
> The value appears to be null from the start.

It could be an empty string, it's unclear in this output. I think usually stacktraces show null and `''` normally https://3v4l.org/kNlV7

If it is null, then maybe it's the result of [another filter before that](https://github.com/woocommerce/woocommerce/blob/6627fdb5ed52e907b17a3846d1127c9a646a9236/plugins/woocommerce/includes/wc-template-functions.php#L2961).

If empty string, then could be another filter handler executed earlier than our handler.

**Comment by sun** [comment] 2022-07-27 10:36
We discovered an implementation of the filter `woocommerce_form_field_text` in another plugin that was early-returning without value.

Interestingly, this only had an effect on the settings of woocommerce-paypal-payments - we did not encounter any other  problems with settings fields elsewhere in the backend.

**Comment by AlexP11223** [comment] 2022-07-27 12:20
> Interestingly, this only had an effect on the settings of woocommerce-paypal-payments - we did not encounter any other problems with settings fields elsewhere in the backend.

`woocommerce_form_field` for settings fields does not seem to be a common approach. WC settings classes do not use it. In our new gateways (PUI, ...) we also switched to a different approach.

But problems could occur in other places.

**Comment by InpsydeNiklas** [comment] 2022-12-29 18:19
There were a couple of Checkout Field Editor plugins which could negatively impact the PayPal Payments settings page, and subsequently the plugin functionality.
This was due to the unconventional use of the `woocommerce_form_field` in PayPal Payments, and was resolved in updated versions of these plugins by only executing in the frontend.
Both linked PRs should no longer be needed then.

**Closed as completed by InpsydeNiklas** 2022-12-29 18:19 UTC
Labels: bug, enhancement
