### ISSUE TITLE
Woocommerce Paypal Payments - Failed order emails

### ISSUE THREAD

**Issue by TS-GITO** [woocommerce/woocommerce-paypal-payments#1877] opened 2023-11-30 10:30 UTC
We're receiving failed order emails for orders paid for via the WooCommerce PayPal Payments plugin Version 2.4.1.

Payments are actually being processed fine but failed order emails are still being sent to the admin email and the customer.

### To Reproduce

Hard to reproduce without making an order via the website. Here's a status report instead:

`
### WordPress Environment ###

WordPress address (URL): https://www.leicadisto.co.uk
Site address (URL): https://www.leicadisto.co.uk
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33.4
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.34-26
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_
Total Database Size: 191.64MB
Database Data Size: 139.07MB
Database Index Size: 52.57MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 8.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 0.41MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.19MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_cache: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.80MB + Engine InnoDB
wp_g_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_g_directions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_g_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_g_markers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_g_polygones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_g_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_icons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_maps: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_marker_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_marker_groups_relation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_markers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_membership_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gmp_options_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_login_fails: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 1.52MB + Index: 1.80MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf_objectmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.39MB + Index: 0.17MB + Engine InnoDB
wp_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_post_smtp_logs: Data: 62.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 35.58MB + Index: 27.08MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 1.27MB + Engine InnoDB
wp_redirection_404: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_supsystic_tbl_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_diagrams: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_rows: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_rows_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_tables: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.50MB + Index: 0.39MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.34MB + Index: 0.28MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.27MB + Index: 0.78MB + Engine InnoDB
wpsm_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 347
blocks: 45
br_labels: 1
br_notice: 2
custom_css: 1
customize_changeset: 2
mailpoet_page: 1
nav_menu_item: 47
nf_sub: 756
onlineworldpay_log: 1
page: 28
post: 9
product: 50
product_variation: 121
restriction: 1
revision: 1
shop_bogof_rule: 2
shop_order: 6169
shop_order_refund: 68
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Advanced Access Manager: by AAM  – 6.9.18
WooCommerce Advanced Product Labels: by BeRocket – 1.2.5.2
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
All in One SEO: by All in One SEO Team – 4.5.1.1
WP Engine Smart Plugin Manager: by WP Engine – 5.17.30
Better Search Replace: by WP Engine – 1.4.3
Cart Notices for WooCommerce: by BeRocket – 3.5.7.8
Christmasify! By Cyber Fox: by Cyber Fox – 1.4.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.13
Data Tables Generator by Supsystic: by supsystic.com – 1.10.30
Disable Comments: by WPDeveloper – 2.4.5
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.2
Easy Google Maps: by supsystic.com – 1.11.10
Site Kit by Google: by Google – 1.114.0
Login No Captcha reCAPTCHA (Google): by Robert Peake and Contributors – 1.7.2
Nextend Social Login: by Nextendweb – 3.1.11
Ninja Forms: by Saturday Drive – 3.7.0
Redirection: by John Godley – 5.3.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Table Maker: by Wpsoul – 1.9.1
TinyPNG - JPEG, PNG & WebP image compression: by TinyPNG – 3.4.3
WPC Custom Related Products for WooCommerce: by WPCodelibrary – 1.3.2
Product Feed PRO for WooCommerce: by AdTribes.io – 13.1.3
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4
WooCommerce Buy One Get One Free: by Oscar Gare – 4.1.5
Custom Product Tabs Lite for WooCommerce: by SkyVerge – 1.8.0
WooCommerce Pay360 (PayPoint) Gateway: by VanboDevelops – 2.2.2
WooCommerce PayPal Payments: by WooCommerce – 2.4.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.3
WooCommerce: by Automattic – 8.3.1
WooSidebars: by WooCommerce – 1.4.6
WordPress Importer: by wordpressdotorg – 0.8.1
WP Instagram Widget: by Scott Evans – 2.0.3
YITH WooCommerce Ajax Search: by YITH – 1.37.0
YITH WooCommerce Wishlist: by YITH – 3.27.0

### Inactive Plugins (1) ###

Snow Flurry: by HTML5andBeyond – 2.14

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Basket: #8 - /basket/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #2956 - /terms-conditions-of-use/

### Theme ###

Name: Flatsome
Version: 3.18.1
Author URL: https://uxthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/mini-cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/order-received.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Buy One Get One Free ###

Display eligible free gift(s) on: 
Disable coupons: no
Custom attributes: no
Rule #10923: title: "FREE Head Torch"; type: "buy_a_get_b"; applies_to: " Product In list ( Leica DISTO D2 BT (837031) ) "; action: "add_to_cart"; free_product_id: "10911"; gift_products: " Product In list ( GP DISCOVERY Motion Sensor Head Torch CH44 (GP-DISCOVERY-CH44) ) "; quantity_rules: "{"1":{"cart_quantity":1,"free_quantity":1,"discount":100,"cart_limit":""},"2":{"cart_quantity":2,"free_quantity":2,"discount":100,"cart_limit":""},"3":{"cart_quantity":3,"free_quantity":3,"discount":100,"cart_limit":""},"4":{"cart_quantity":4,"free_quantity":4,"discount":100,"cart_limit":""},"5":{"cart_quantity":5,"free_quantity":5,"discount":100,"cart_limit":""},"6":{"cart_quantity":6,"free_quantity":6,"discount":100,"cart_limit":""}}"; exclude_coupon_validation: "1"

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-30 13:41:34 +00:00
Options: ✔
Notes: 193
Onboarding: completed

### Action Scheduler ###

Complete: 903
Oldest: 2023-10-31 00:01:52 +0000
Newest: 2023-11-30 10:00:44 +0000

Pending: 4
Oldest: 2023-11-30 10:15:44 +0000
Newest: 2023-12-01 02:59:33 +0000

### Pay360 Gateway ###

Integration type: Pay360 Hosted Cashier
3D Secure: No
Transaction Type: capture
Skin ID: 2
Using iFrame: Yes
Gateway Mode: Live

### Status report information ###

Generated at: 2023-11-30 10:03:14 +00:00
`

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-11-30 14:42
Hello @TS-GITO 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The situation you described sounds to be related to a plugin conflict or an issue with the webhooks. The webhooks can be easily tested via the "Simulate" button in the "Connection" tab.
For the possible plugin conflict, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
.
Since you have a hard time reproducing the issue, you might first want to create a [staging site](https://wordpress.org/plugins/wp-staging/) and onboard our plugin with a [sandbox account](https://developer.paypal.com/), in order to make it easier to try to reproduce this issue.

If you can't find the fix with these instructions, please open a support thread as advised above. We will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-11-30 14:42 UTC
Labels: support
