### ISSUE TITLE
Uncaught Error: Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by joergHX277** [woocommerce/woocommerce-paypal-payments#2345] opened 2024-06-14 11:10 UTC
### Describe the Bug

After updating my WooCommerce PayPal Payments plugin to version 2.8.0, we get the error message "Uncaught Error: Automatic publicPath is not supported in this browser" in all major browser (IE, Chrome, Firefox) when a user tries to access the checkout page and especially when WooCommerce Creditcard payments are enabled. 

This causes the problem that no creditcard data can be entered.

What is the solution here?

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-06-18 10:09
Hello @joergHX277 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-06-18 10:09 UTC
Labels: support
