### ISSUE TITLE
MISSING SHIPPING ADDRESS

### ISSUE THREAD

**Issue by mvauclare** [woocommerce/woocommerce-paypal-payments#925] opened 2022-10-20 20:14 UTC
Hi everyone,
I meet this issue now on my website.
I use last version of Woocommerce and Paypal payments plugin.
When I complete the checkout form and click on Pay with Paypal button : Paypal pop up open ... and close ... and there is this error displaying on my checkout page : 

MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS`.

I don't have this issue if I use woocommerce checkout shortcode to build my page ...

Demo here : https://www.loom.com/share/22967ee028bd4a60a362f72082fba0fb

_Originally posted by @mvauclare in https://github.com/woocommerce/woocommerce-paypal-payments/issues/330#issuecomment-1286086507_

**Comment by Sirvijver** [comment] 2022-12-13 14:28
Hello,

Thank you for reaching out to us. This issue you have encountered has been reported to us before. In that instance it was caused by a conflict our plugin had with the plugin "Germanized for Woocommerce". You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We actually don't provide merchant support via GitHub and will close this thread. If you require additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 14:28 UTC
Labels: support
