### ISSUE TITLE
shipping_preference=SET_PROVIDED_ADDRESS

### ISSUE THREAD

**Issue by postaenzo** [woocommerce/woocommerce-paypal-payments#1138] opened 2023-01-27 17:01 UTC
### Describe the Bug
Hi, I'm using WooCommerce PayPal Payments version  2.0.1  selling regular products. 
Filling all the fields for the invoice ( using the same address for shipping ) but when click on the paypal button to pay the following error appears: 
MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS`.

tried filling the shipping address too, again the same error is coming. 

### To Reproduce

1. Go to shop, add a product to the cart,  fill all the invoice fields, and try to pay using paypal button.

### Environment

 - WordPress Version --> 6.1.1

**Comment by postaenzo** [comment] 2023-01-27 18:06
I find this issue, seems the same 
https://github.com/woocommerce/woocommerce-paypal-payments/issues/1095
hope to get soon a solution.

**Comment by Sirvijver** [comment] 2023-01-30 11:48
Hello @postaenzo 

yes, this is the same and I will link this thread to the bug as well. However, I will also close this thread, since we don't provide support via GH. I will request the bug to be reviewed again on our next backlog meeting, so we can possibly speed up a resolution for this case. However, we have not received many support requests for this, so you might also want to do some conflict testing, just to make sure the issue is not caused by a conflict with another plugin.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-01-30 11:48 UTC
Labels: support
