### ISSUE TITLE
Fatal error message

### ISSUE THREAD

**Issue by jam478** [woocommerce/woocommerce-paypal-payments#1635] opened 2023-08-28 08:29 UTC
### Describe the Bug

When you click the edit button on the CTX Feed plugin you get a fatal error message. There appears to be a conflict with the new Paypal update. Error has been replicated by CTX Feed.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

![Fatal error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/123255820/d305376e-8f57-4806-98b0-7e3e1ed702b2)

### Environment

 - WordPress Version 6.3
 - WooCommerce Version 8.0.2
 - Plugin Version 2.2.1
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed CTX Feed Pro Version 7.0.1

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-08-28 09:05
Hello @Sirvijver ,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We are aware of this issue that was caused by our last release and got a fix for it from our developers. The fix is available in this package for you that you can download here:
https://drive.google.com/uc?export=download&id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP

We think we will try to release this as soon as possible as version 2.2.2, but we are still discussion this. For now, you should be able to use this package as a temporary fix until we do a next release. Any details on this issue/fix you can find on our [GitHub issue here](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1628). 
We will close this thread.

Kind regards,
Joost

**Closed as completed by Sirvijver** 2023-08-28 09:05 UTC
Labels: support

**Comment by jam478** [comment] 2023-08-28 10:11
Joost, thanks for getting back to me.

Fyi: The 'Report a bug' link on Woo directs you to Github ' and not support
- that's the reason I posted the issue there.

Take care.

Jamil
