### ISSUE TITLE
Connecting to PayPal Sandbox consistently fails on first attempt

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-paypal-payments#62] opened 2020-10-15 03:03 UTC
I was testing the Connect to PayPal Sandbox button and I noticed that it was consistently failing to connect on every first attempt after disconnecting the store, then works on the second attempt.

After attempting to connect my store to PayPal Sandbox I get the following error:

![](https://d.pr/i/qpdVWz+)

I had a look in the logs and there's a bunch of logs for:

```
2020-10-15T02:50:10+00:00 WARNING [Error] Unknown error while connecting to PayPal
```

**Steps to reproduce**

I took a screencast which showcases the issues I'm having: https://d.pr/v/Chl736

(apologies for the long video, I wanted to run it through onboarding twice to show it's consistently happening)

0. If your store is connected to PayPal, disconnect it first.
1. Click on the "Connect to PayPal Sandbox" button
3. Complete the onboarding/connection process
4. Once you've returned back to your store, you'll get an error notice.
5. At this point, I noticed all the PayPal Checkout settings are visible as well
6. Retry going through the onboarding/connection process by clicking the "Connect to PayPal Sandbox" button using the same login.
7. Once returned from PayPal onboarding, your store will be connected

**Comment by InpsydeNiklas** [comment] 2021-08-04 12:39
We found that this behavior occurs when the onboarding process is confirmed too quickly. On the last step of the onboarding, you will need to remain for just a few seconds, then the onboarding will complete fine.
![image](https://user-images.githubusercontent.com/70433191/128181104-707d7274-d595-4e9c-a209-4104fd059e8b.png)
If you click the button "Go back to test facilitator's Test Store" as soon as it appears, then the onboarding might fail.
It used to happen to me every time but ever since I started waiting a moment at  the end, I haven't seen the problem since. There is some information being transferred at this stage and I'm not sure what we could do to prevent users from "clicking too fast" through the process before it is finished.

**Comment by InpsydeNiklas** [comment] 2023-09-27 16:08
Onboarding reliability was significantly improved in update 2.2.1+ with https://github.com/woocommerce/woocommerce-paypal-payments/pull/1565.  So, the workaround of waiting a few seconds on the last step (before clicking "Back to WooCommerce") should no longer be needed. It may still be advantageous to wait at least a second or two, though.
In any case, by now, it should work well enough to justify closing the issue.

**Closed by InpsydeNiklas** 2023-09-27 16:08 UTC
Labels: support
