### ISSUE TITLE
cant connect paypal after repeated attempts. no reason given. just go around in circles.

### ISSUE THREAD

**Issue by PSLegaud** [woocommerce/woocommerce-paypal-payments#1064] opened 2022-12-06 03:50 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2022-12-09 12:35
Hello @PSLegaud 

For helping you with this issue, we would need to see some screenshots to understand what you are seeing. We would advise to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, because we only use GitHub for reproduced issues that we know we will release a fix for. This is also why we will close this ticket and continue helping you via the support ticket.

You might also want to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to have them check your account for issues, since this could very well be an issue with that.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-09 12:35 UTC
Labels: support
