### ISSUE TITLE
Paypal Button grey and dont work on Desktop but on mobilphone all works

### ISSUE THREAD

**Issue by admin100903** [woocommerce/woocommerce-paypal-payments#1569] opened 2023-08-01 14:09 UTC
### Describe the Bug
The paypal button is grey and dont work on the desktop version but on the mobilephone it works , also the button is to near on the other buttons.... please look at the pictures... that wasnt on the beginning you can see it all over my page which is in construction:

https://wayofmusic-qcy0gtsa7u.live-website.com
![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/141150550/adec5e43-7481-47a5-805f-13782fb670f9)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/141150550/87c41956-833c-484d-8c9e-b1a15e08439a)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2023-08-02 11:24
Hello @admin100903 

It seems like this thread is the duplicate of #1568, so I'm closing it. The answer has been delivered in the referenced thread.

Kind Regards,

Krystian

**Closed as completed by SydeKrystian** 2023-08-02 11:24 UTC
Labels: duplicate, support, third-party
