### ISSUE TITLE
Google Pay window does not show cart price

### ISSUE THREAD

**Issue by acabrerarey** [woocommerce/woocommerce-paypal-payments#2687] opened 2024-10-10 12:16 UTC
### To Reproduce

1. Go to 'final checkout'
2. Click on google pay'
3. Then a small window opens with the Google Pay information with my card but it does not show the price.
4. I did tests and still paid, to see what happens. And the payment does work, I receive it in my email, but I don't know what I paid because the Google Pay window does not show the price

### Screenshots

![Image](https://github.com/user-attachments/assets/6d99c058-7a5d-4152-b1ea-b96f0696b465)

**Comment by callmeahmedr** [comment] 2024-10-11 00:51
Hey, It sounds like the cart total isn't being passed properly to Google Pay. Here are a few things you can try:

- **Update WooCommerce & PayPal Plugins:** Make sure both WooCommerce and the WooCommerce PayPal Payments plugin are fully updated.
- **Check Console for Errors**: Open your browser's developer tools (F12) and check for any JavaScript errors when you click Google Pay. Errors might indicate missing or incorrect data.
- **Plugin Conflicts**: Try disabling all other plugins and switching to a default theme (like Storefront) to rule out any conflicts.
- **Enable Debug Mode**: Go to WooCommerce > Settings > Payments > PayPal > Manage, enable "Debug Log," and check if there’s any useful info in the logs.

Hopefully, this helps!

**Comment by SydeKrystian** [comment] 2024-10-15 07:08
Hello @acabrerarey 

It seems that your GitHub issue is primarily a support request and I cannot reproduce it on my own staging site. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2024-10-15 07:08 UTC
Labels: support

**Comment by acabrerarey** [comment] 2024-10-15 14:25
Hi Krystain, thank you very much!
Finally the problem solve it with strike pluging.
Paypal plugging has the problem.
Any way thank you again!


*Amaury Cabrera*
*Estrategias MKT Content*
*Fotógrafo, Productor Audiovisual*

*Portfolio B2B: acmedia.es <http://acmedia.es>*
*Portfolio Personal: amaurycabrera.es <http://amaurycabrera.es>*
*Contacto: ***@***.*** ***@***.***>*
*Teléfono: +34 605 080 787*
