### ISSUE TITLE
[RESOURCE_NOT_FOUND] The specified resource does not exist.

### ISSUE THREAD

**Issue by SimBotBiz** [woocommerce/woocommerce-paypal-payments#1123] opened 2023-01-14 11:12 UTC
### Describe the Bug

Hi, after the latest update I am starting to see this error quite often.

```
Failed to process the payment. Please try again or contact the shop admin. [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID PayPalGateway.php:525 [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID OrderEndpoint.php:551 Lo stato dell’ordine è cambiato da In attesa di pagamento a Fallito.
```

```
2023-01-14T10:46:27+00:00 DEBUG POST https://api.paypal.com/v1/oauth2/token?grant_type=client_credentials
Response Debug ID: 5f97737f57c20
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-01-14T10:46:27+00:00 DEBUG PATCH https://api.paypal.com/v2/checkout/orders/XXXXXXXXXXXXX
Request Body: [{"op":"replace","value":{"reference_id":"default","amount":{"currency_code":"EUR","value":"52.23","breakdown":{"item_total":{"currency_code":"EUR","value":"48.62"},"shipping":{"currency_code":"EUR","value":"10.90"},"tax_total":{"currency_code":"EUR","value":"0.00"},"discount":{"currency_code":"EUR","value":"7.29"}}},"description":"","items":[{"name":"Zitronen-honig aus biologischem Anbau - 300g","unit_amount":{"currency_code":"EUR","value":"7.29"},"quantity":1,"description":"Zitronen-honig aus biologischem Anbau von AgriSicilia ist ein typisches Produkt der tyrrhenischen K\u00fcste. Sie ist energetisiere","sku":"MIE007DE","category":"PHYSICAL_GOODS"},{"name":"Bio-Zitrusmarmelade aus Sizilien - 360g","unit_amount":{"currency_code":"EUR","value":"4.19"},"quantity":1,"description":"Bio-Zitrusfruchtmarmelade aus Sizilien - in 360-g-Gl\u00e4sern - ist eine gesunde und nahrhafte Konfit\u00fcre, die mit Rohrzucker ange","sku":"SMA005","category":"PHYSICAL_GOODS"},{"name":"Sizilianisches Pesto - 190g","unit_amount":{"currency_code":"EUR","value":"5.19"},"quantity":1,"description":"Aus dem Herzen Siziliens kommt eine Spezialit\u00e4t, die dieses Land mehr denn je auszeichnet: das sizilianische Pesto. Diese schm","sku":"PSIL","category":"PHYSICAL_GOODS"},{"name":"3-Frucht Zitrusmarmelade aus Sizilien - 240g","unit_amount":{"currency_code":"EUR","value":"3.69"},"quantity":1,"description":"3-Frucht ZitrusMarmelade aus Sizilien ist ein k\u00f6stliches Produkt von AgriSicilia, das aus einer einzigartigen Mischung von siz","sku":"AGR092","category":"PHYSICAL_GOODS"},{"name":"Konfit\u00fcre extra Aprikosen aus Sizilien - 360g","unit_amount":{"currency_code":"EUR","value":"4.59"},"quantity":3,"description":"Die Konfit\u00fcre extra Aprikosen aus Sizilien - erh\u00e4ltlich in praktischen 360-Gramm-Gl\u00e4sern - ist ein Produkt von AgriSicilia, ","sku":"AGR036DE","category":"PHYSICAL_GOODS"},{"name":"Etna bitter - 70cl","unit_amount":{"currency_code":"EUR","value":"14.49"},"quantity":1,"description":"Das Produkt\r\n\r\n \tCharakter: Ohne Konservierungsstoffe oder k\u00fcnstliche Farbstoffe oder Glutenquellen h\u00e4lt Amaro dell'Etna sein","sku":"AMA07029","category":"PHYSICAL_GOODS"}],"payee":{"merchant_id":"8TRSH3543V82E"},"shipping":{"name":{"full_name":"Hannelore Bittner"},"address":{"country_code":"DE","address_line_1":"XXXXXX","address_line_2":"5","admin_area_1":"DE-TH","admin_area_2":"XXXXXX","postal_code":"XXXXX"}},"custom_id":"XXXXXX","invoice_id":"XXXXXXX"},"path":"\/purchase_units\/@reference_id=='default'"}]
Response Debug ID: 480e3cab222be
Response: Array
(
    [code] => 404
    [message] => Not Found
)

Response Body: {"name":"RESOURCE_NOT_FOUND","details":[{"issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"480e3cab222be","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]}

2023-01-14T10:46:27+00:00 WARNING [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID
2023-01-14T10:46:27+00:00 ERROR Payment failed: Failed to process the payment. Please try again or contact the shop admin. [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID PayPalGateway.php:525 [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID OrderEndpoint.php:551
2023-01-14T10:46:43+00:00 DEBUG POST https://api.paypal.com/v1/oauth2/token?grant_type=client_credentials
Response Debug ID: f4eff94a1a1e8
Response: Array
(
    [code] => 200
    [message] => OK
)

```

<details><summary>System status</summary>

  ```
`
### WordPress Environment ###

WordPress address (URL): https://shop.agrisicilia.eu
Site address (URL): https://shop.agrisicilia.eu
WC Version: 7.2.3
REST API Version: ✔ 7.2.3
WC Blocks Version: ✔ 8.9.4
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.83.1
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.3
WC Database Prefix: wp_
Total Database Size: 331.31MB
Database Data Size: 197.39MB
Database Index Size: 133.92MB
wp_woocommerce_sessions: Data: 5.02MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 15.55MB + Index: 12.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 9.02MB + Index: 9.33MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 7.06MB + Index: 6.39MB + Engine InnoDB
wp_awb_critical_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 5.02MB + Index: 7.19MB + Engine InnoDB
wp_fusion_form_entries: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_submissions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 1.27MB + Index: 0.17MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
wp_icl_strings: Data: 7.52MB + Index: 14.09MB + Engine InnoDB
wp_icl_translate: Data: 23.25MB + Index: 1.52MB + Engine InnoDB
wp_icl_translate_job: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 14.06MB + Index: 0.14MB + Engine InnoDB
wp_icl_translations: Data: 1.52MB + Index: 1.47MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 8.08MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 44.56MB + Index: 55.84MB + Engine InnoDB
wp_posts: Data: 23.44MB + Index: 3.11MB + Engine InnoDB
wp_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_lang: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.39MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_termmeta: Data: 0.36MB + Index: 0.44MB + Engine InnoDB
wp_terms: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_usermeta: Data: 6.45MB + Index: 7.91MB + Engine InnoDB
wp_users: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.02MB + Index: 2.17MB + Engine InnoDB
wp_wc_order_stats: Data: 1.02MB + Index: 0.31MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.20MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 7.45MB + Index: 2.70MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.25MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

acf-field: 86
acf-field-group: 16
attachment: 5556
awb_off_canvas: 5
custom_css: 2
customize_changeset: 1
fusion_element: 36
fusion_form: 5
fusion_tb_layout: 9
fusion_tb_section: 57
mt_pp: 10
nav_menu_item: 131
page: 57
post: 561
product: 722
revision: 867
shop_coupon: 45
shop_order: 2737
shop_order_refund: 23
wp_global_styles: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.14
Advanced Custom Fields Multilingual: by OnTheGoSystems – 1.10.4
Advanced Custom Fields PRO: by WP Engine – 6.0.6
Facebook for WooCommerce: by Facebook – 3.0.7
Avada Builder: by ThemeFusion – 3.9.1
Avada Core: by ThemeFusion – 5.9.1
Google Authenticator: by Ivan Kruchkoff – 0.54
Google Listings and Ads: by WooCommerce – 2.3.5
Site Kit by Google: by Google – 1.90.1
Health Check & Troubleshooting: by The WordPress.org community – 1.5.1
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.4.1
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.54
User Profile Picture: by Cozmoslabs – 2.6.0
Trustpilot-reviews: by Trustpilot – 2.5.914
Woo Discount Rules PRO 2.0: by Flycart – 2.5.2
Woo Discount Rules: by Flycart – 2.5.2
WooCommerce Brands: by WooCommerce – 1.6.41
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.19
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.1.2
WooCommerce PayPal Payments: by WooCommerce – 2.0.1
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 3.0.2
WooCommerce Shipment Tracking: by WooCommerce – 2.0.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0
WooCommerce: by Automattic – 7.2.3 (update to version 7.3.0 is available)
WP Super Cache: by Automattic – 1.9.2
WPML Media: by OnTheGoSystems – 2.7.1
WPML String Translation: by OnTheGoSystems – 3.2.3

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
simple (simple)
simple (simple-fr)
simple (simple-de)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-de)
featured (featured-fr)
outofstock (outofstock)
outofstock (outofstock-de)
outofstock (outofstock-fr)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #35 - /negozio/
Cart: #36 - /carrello/
Checkout: #37 - /pagamento/
My account: #38 - /mio-account/
Terms and conditions: #50 - /termini-e-condizioni/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.9.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-14 12:51:44 +01:00
Options: ✔
Notes: 25
Onboarding: completed

### Action Scheduler ###

Complete: 7,129
Oldest: 2022-12-14 12:11:45 +0100
Newest: 2023-01-14 11:47:53 +0100

Failed: 8,642
Oldest: 2022-11-11 17:48:46 +0100
Newest: 2023-01-13 21:00:06 +0100

Pending: 4
Oldest: 2023-01-14 13:05:15 +0100
Newest: 2023-01-15 04:00:00 +0100


### Status report information ###

Generated at: 2023-01-14 12:10:33 +01:00
`
  ```

</details>

**Comment by Sirvijver** [comment] 2023-01-16 11:48
Hello @SimBotBiz 

you have reached out to oper GitHub forum with a support request. We utilize GitHub mainly for development activities so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered does sound like a plugin conflict, so before you do, I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

For now, I will close this thread and wait for you to open a support engagement with our team.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-01-16 11:48 UTC
Labels: support
