### ISSUE TITLE
Paypal checkout button at checkout page is missing when edit the paypal checkout info

### ISSUE THREAD

**Issue by lemonhunag** [woocommerce/woocommerce-paypal-payments#913] opened 2022-10-14 15:23 UTC
### To Reproduce

1. Go to 'edit Paypal checkout Hide Funding Source and choose enable on checkout' 
2. Click on 'saving changes'
3. checkout the front end of checkout page'
4. See Paypal checkout button is missing

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 7.0.0
 - Plugin Version 1.9.4
 - Browser [e.g. Chrome, Safari] and Version  Chrome
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2022-10-19 08:58
Hello @lemonhunag 

Could you explain to me step 1? If you want to share a screenshot, it might be better to handle this as a support issue and create a thread on our support system [here](https://paypal.inpsyde.com/docs/request-support/). We have not heard about this situation before, so I would think it might not be a bug, but possibly a conflict.

Kind regards, 
Joost

**Comment by Sirvijver** [comment] 2022-10-19 12:28
I have read your description and check the backend again, but the field for "Hide Funding source(s)" and the "Enable on Checkout" (related to the button on checkout) are not related to each other. If you disable this option, you will indeed not see the PayPal button, but that is the function of this button.
I would really think this is not the cause of the issue you are seeing. If you want us to take a look on your site, you can contact us privately following [these instructions](https://paypal.inpsyde.com/docs/request-support/).

For now, I will close this thread, since it really should be investigated as a support issue, not as a bug.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-10-19 12:28 UTC
