### ISSUE TITLE
problem on checkout page.

### ISSUE THREAD

**Issue by kashadvertise** [woocommerce/woocommerce-paypal-payments#1978] opened 2024-01-22 22:18 UTC
on the checkout page, I am recing following error. Customers cannot pay via Paypal.

NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance.

**Comment by gunship800** [comment] 2024-01-23 18:54
Same issue here. It's unfortunate I have to manually beta test this plug in every release to ensure the advanced CC processing or the Paypal login is not broken.  

You can rollback to the prior version and paypal will work again

**Comment by Sirvijver** [comment] 2024-01-24 07:02
Hello @kashadvertise 

Thank you for reaching out to us, we are here to help.
We are aware of this issue and working on providing a fix for this problem. Because we don't have one available now and the problem is significant, we decided to revert to 2.4.3 in the form of the 2.5.1 release that was pushed yesterday. I am confident that we will get this issue resolved soon and release it as version 2.5.2.

We will use this [GH thread](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1981) as the main one, to update about any changes in the situation. We will close this thread now.

Kind regards,
Joost

**Closed as completed by Sirvijver** 2024-01-24 07:02 UTC
Labels: support
