### ISSUE TITLE
Cannot purchase Subscription Products with PayPal

### ISSUE THREAD

**Issue by lynnjat7** [woocommerce/woocommerce-paypal-payments#2031] opened 2024-02-14 18:49 UTC
### Describe the Bug

Using version 2.5.3 of PayPal Payments combined with Woo Subscriptions 6.0.0 and WooCommerce 8.5.2, we are seeing the following behaviour:
* no PayPal button shown on the cart/checkout pages for subscription products in cart
* PayPal button IS shown in the cart pop-up window in the header when a subscription product is in the cart --> you can click it, log in, and fill out information, but you are then redirected to the checkout page, which shows "no payment options available" and does not allow the checkout to complete
* if you edit your PayPay settings, and save them, then the behaviour changes - now you see the PayPal buttons on the cart and checkout pages, but they are greyed out and cannot be clicked.

### To Reproduce

1. Need to test this on a site that already has PayPal installed and set up for subs - I am using a sandbox account, but this issue was originally reported by a customer with a live account
2. Update PayPal to latest version, Subs to latest version, Woo to latest version
3. Create a simple subscription product (or use an existing one)
4. Add it to cart
5. On cart and checkout page, PayPal is not offered as a payment method
6. you can try using the PayPal button in the cart pop-out in the menu bar - this allows you to log into your account and approve the payment, but then you are redirected to the checkout page which does not let you complete checkout
7. go into your settings and re-save the PayPal settings
8. now on cart/checkout page, PayPal buttons appear but are greyed out (note that if you are testing with Storefront, you'll see the option still showing on the checkout page, use the cart page to view the greyed out button)

### Screenshots

Subscription product in cart, no PayPal button:

![0lWVgF.png](https://github.com/woocommerce/woocommerce-paypal-payments/assets/109691691/2c5dfbeb-dbcc-4f09-9d88-e977301eb755)

But it is there in the pop out:

![0p7eyN.png](https://github.com/woocommerce/woocommerce-paypal-payments/assets/109691691/cf87e23a-d737-482a-8da0-b682a4762042)

No payment options offered on the checkout page:

![pLPnKQ.png](https://github.com/woocommerce/woocommerce-paypal-payments/assets/109691691/5f0753c7-1caa-40c9-97b7-55e27da9004d)

After re-saving PayPal settings, the button is back in the cart but greyed out:

![wkZj4x.png](https://github.com/woocommerce/woocommerce-paypal-payments/assets/109691691/bc0887eb-9068-4c42-8089-f5ebd19746ff)

### Expected Behavior

You should be able to buy subscriptions with PayPal.

### Additional Details

Original reporting ticket:
7740508-zen

SSR from my test site as I was able to reproduce.

<details><summary>System status</summary>

  ```
 `
### WordPress Environment ###

WordPress address (URL): https://numberthree.mystagingwebsite.com
Site address (URL): https://numberthree.mystagingwebsite.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.4.33-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 52.21MB
Database Data Size: 30.95MB
Database Index Size: 21.26MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.88MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 6.02MB + Index: 7.34MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.08MB + Index: 4.41MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.03MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.03MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 1.47MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.13MB + Index: 0.20MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.30MB + Engine InnoDB
wp_sa_cfw_fbt_temp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_agents_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_framemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_frames: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_wtbp_favorites: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wtbp_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 1
addify_rfq: 1
addify_rfq_fields: 1
afreg_fields: 1
af_atribut_grp_child: 3
af_attributes_group: 1
af_attribute_stock: 1
af_disc_p_rules: 1
af_variation_grp: 3
attachment: 138
bis_price_stock: 1
bis_stock_alert: 2
custom_css: 1
def_reg_fields: 10
elementor_library: 1
global_product_addon: 1
gtc_gift_card: 1
jb_store_css: 4
mail-debug: 68
mailpoet_page: 1
nav_menu_item: 5
order_shipment: 39
page: 34
payment_gateway: 1
post: 11
prl_engine: 3
product: 84
product_variation: 110
revision: 36
shipping_package: 1
shop_coupon: 7
shop_order: 734
shop_order_refund: 3
shop_subscription: 15
user_request: 1
warranty_request: 1
wc_membership_plan: 1
wc_order_status: 8
wc_pickup_location: 1
wc_user_membership: 1
wishlist: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce PayPal Payments: by WooCommerce – 2.5.3
Woo Subscriptions: by WooCommerce – 6.0.0
WooCommerce: by Automattic – 8.5.2

### Inactive Plugins (73) ###

Advanced Gift Card: by Addify – 1.4.1 (update to version 1.5.0 is available)
Affiliate For WooCommerce: by StoreApps – 7.3.0
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Back in Stock and Price Alert: by Addify – 1.0.3 (update to version 1.1.0 is available)
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.4 (update to version 3.1.3 is available)
Classic Editor: by WordPress Contributors – 1.6.3
Code Snippets: by Code Snippets Pro – 3.6.2
Custom User Registration Fields for WooCommerce: by Addify – 1.7.8 (update to version 2.1.1 is available)
Donation For Woocommerce: by wpexpertsio – 3.4.5
Edit Order by Customer: by Addify – 1.0.1 (update to version 1.1.0 is available)
Elementor: by Elementor.com – 3.14.1
Gallery Captions for WooCommerce: by John Beales – 1.8.1
Gift Cards Pro for WooCommerce: by FantasticPlugins – 3.7
Import Export Suite for WooCommerce: by WebToffee – 1.2.3 (update to version 1.2.5 is available)
Invoice Payment Option: by Addify – 1.0.4
Jetpack: by Automattic – 13.1.1
Jetpack Boost: by Automattic - Jetpack Site Speed team – 1.8.0
Lottery for WooCommerce: by Flintop – 8.9.0
Mail Debug for WooCommerce: by Leanza Francesco – 1.3.0
MailPoet: by MailPoet – 4.43.1
MailPoet Premium: by MailPoet – 4.43.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.6.3
Polylang: by WP SYNTEX – 3.5.3
Product Dynamic Pricing and Discounts: by Addify – 1.0.6 (update to version 1.1.0 is available)
Product Options and Fields: by Addify – 1.2.1 (update to version 1.3.0 is available)
Request a Quote for WooCommerce: by Addify – 2.4.9 (update to version 2.6.3 is available)
Sales Agent For WooCommerce: by WPExperts.io – 1.2
Shared Attribute Stock: by Addify – 1.2.0 (update to version 1.4.0 is available)
Spin Wheel For Woocommerce: by wpexpertsio – 1.7.1
User Registration for WooCommerce: by WPExperts – 1.1.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.9
WooCommerce Additional Variation Images: by WooCommerce – 2.3.2
WooCommerce Advanced Notifications: by WooCommerce – 1.4.3 (update to version 1.4.4 is available)
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.11
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.3 (update to version 1.6.8 is available)
WooCommerce Bookings: by WooCommerce – 1.15.54 (update to version 2.0.9 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.10 (update to version 1.7.12 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.15.2 (update to version 1.15.6 is available)
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.12.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.0
WooCommerce Deposits: by WooCommerce – 2.2.1 (update to version 2.2.5 is available)
WooCommerce Disability VAT Exemption: by WooCommerce – 1.6.1 (update to version 1.6.3 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.2.3
WooCommerce FedEx Shipping: by WooCommerce – 3.9.1
WooCommerce Local Pickup Plus: by SkyVerge – 2.11.1 (update to version 2.11.2 is available)
WooCommerce Memberships: by SkyVerge – 1.25.0 (update to version 1.26.2 is available)
WooCommerce Moneris Gateway: by SkyVerge – 3.2.3 (update to version 3.4.0 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.5.2 (update to version 3.5.11 is available)
WooCommerce One Page Checkout: by Automattic – 2.3.0 (update to version 2.8.1 is available)
WooCommerce Order Delivery: by Themesquad – 2.3.2 (update to version 2.6.1 is available)
WooCommerce Order Status Control: by SkyVerge – 1.16.0
WooCommerce Order Status Manager: by SkyVerge – 1.15.2
WooCommerce Payments: by Automattic – 6.0.1 (update to version 7.1.0 is available)
WooCommerce PDF Invoices: by Andrew Benbow – 4.17.2 (update to version 5.0.3 is available)
WooCommerce PDF Watermark: by WooCommerce – 1.5.1 (update to version 1.6.3 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.46 (update to version 1.7.49 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.62 (update to version 1.10.68 is available)
WooCommerce Product Recommendations: by WooCommerce – 2.4.2 (update to version 3.0.6 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 4.0.0
WooCommerce Smart Coupons: by StoreApps – 8.16.0
WooCommerce Square: by WooCommerce – 4.5.0
WooCommerce Stamps.com API integration: by WooCommerce – 1.9.7
WooCommerce Store Credit: by Themesquad – 4.3.0 (update to version 4.5.0 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce Warranty Requests: by WooCommerce – 2.1.7 (update to version 2.4.0 is available)
WooCommerce WishLists: by Element Stark – 2.2.8 (update to version 2.3.0 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.52 (update to version 1.8.4 is available)
Woo Gift Cards: by Woo – 1.16.10
Woo Product Add-ons: by Woo – 6.6.0
Woo Product Bundles: by Woo – 6.22.6
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP STAGING WordPress Backup Plugin - Backup Duplicator & Migration: by WP-STAGING
WPStagingBackup – 3.3.3


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by WP STAGING – 1.5.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
gift_card (gift_card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0 (update to version 4.5.4 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/customer-new-account.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://numberthree.mystagingwebsite.com
Subscriptions-core Library Version: 6.8.0
Subscription Statuses: wc-active: 7
wc-expired: 2
wc-pending: 2
wc-on-hold: 3
wc-cancelled: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Canada — Ontario

### Subscriptions by Payment Gateway ###

other: wc-active: 6
wc-cancelled: 1
wc-expired: 2
wc-pending: 1

PayPal: wc-active: 1
wc-on-hold: 1


### Payment Gateway Support ###

Check payments: products
PayPal: refunds
products
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: PayPal Subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-15 15:45:48 -05:00
Options: ✔
Notes: 154
Onboarding: skipped

### Action Scheduler ###

Complete: 10,676
Oldest: 2024-01-14 13:50:56 -0500
Newest: 2024-02-14 13:47:14 -0500

Failed: 447
Oldest: 2022-11-11 12:37:23 -0500
Newest: 2024-02-14 13:49:15 -0500

Pending: 15
Oldest: 2024-02-14 13:50:35 -0500
Newest: 2024-12-31 22:00:00 -0500


### Status report information ###

Generated at: 2024-02-14 13:49:20 -05:00
`
  ```

</details>

**Comment by Sirvijver** [comment] 2024-02-15 13:34
Hello @lynnjat7 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I was able to reproduce this situation, when I set the PayPal Payments plugin to "PayPal Subscriptions" (from Vaulted Subscriptions) without changing the product to include the Plan Name and connecting it to PayPal. We are not able to verify this situation is happening on your site as well with the information you have provided. Because of this, I would advise you to open a support thread with us, via the link provided above, so we can have a look at the system report in case that is still needed.

Since we don't provide support via GitHub, I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2024-02-15 13:34 UTC
Labels: support

**Comment by jaminNZx** [comment] 2024-11-20 07:25
Hi @lynnjat7 

After hours of searching you're the only person who has detailed the exact issue im now having. 

I had subscriptions working with Paypal (without Vaulting or a Plan Name setup) and signed up multiple subs.
Then I tested a subscription myself, had the same as prompt you had, "You are currently paying with Paypal". 
I selected the link "Choose another payment method", then the Paypal buttons were greyed out and I have not been able to return them to normal. 

I was also able to checkout with other items in the cart. 

Did you manage to fix the issue or get assistance? 

Thank you

**Comment by lynnjat7** [comment] 2024-11-20 12:59
HI @jaminNZx - I'm just seeing now that my report of this issue does not look like it was properly addressed by the support team.

They responded to me here as if I were a customer using PayPal but actually I am an Automattic employee that was reporting a potential bug. @Sirvijver 

I'm not sure what happened to this issue but I will follow up on it internally. For now, can you verify that you are running the latest versions of Subscriptions, WooCommerce, and PayPal? Sharing your SSR would be helpful.

Also, if you have an open support request with our support team that would help as I can use that to track any new information - please share the ticket number here (or at least the email address you use for support and I can track it down).

Lastly, I will note that Joost said this above:
> I was able to reproduce this situation, when I set the PayPal Payments plugin to "PayPal Subscriptions" (from Vaulted Subscriptions) without changing the product to include the Plan Name and connecting it to PayPal.

So please double check your PayPal settings and make sure the product settings match, as it seems this might be the source of the issue.
