### ISSUE TITLE
Paypal & Venmo Errors on Single Product Page

### ISSUE THREAD

**Issue by YuletideMedia** [woocommerce/woocommerce-paypal-payments#1236] opened 2023-03-07 23:20 UTC
### To Reproduce

1. Navigate to a product: https://yuletidemedia.com/product/legendary-2021/
2. Select your option, for example "Digital File (on USB)"
3. Select PayPal when the button appears.
4. It looks like it tries to load the PayPal window, but it quickly disappears and this error shows up at the top of the page: "Something went wrong. Please try again or choose another payment source."

### Screenshots
![image](https://user-images.githubusercontent.com/81788536/223574585-957ff68f-e072-4263-a8d9-1010b88c1fb8.png)

Error:
![image](https://user-images.githubusercontent.com/81788536/223574859-306a43d8-df48-4e8f-b367-c47b13191698.png)

### Expected Behavior
PayPal checkout opens and the user is able to checkout from the single product page.

### Actual Behavior
It looks like it tries to load the PayPal window, but it quickly disappears and this error shows up at the top of the page: "Something went wrong. Please try again or choose another payment source."

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.4.1
 - Plugin Version
![image](https://user-images.githubusercontent.com/81788536/223575459-b3e38030-daa4-4cb9-b5b3-870a799fc6ab.png)
 - Browser [e.g. Chrome, Safari] and Version: Windows 10 PC using Google Chrome Version 110.0.5481.178 (Official Build) (32-bit)
 - Any other plugins installed
 
![image](https://user-images.githubusercontent.com/81788536/223576911-0e555fd0-95cc-42e7-9b6a-6c2a11b510ff.png)

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-03-13 11:20
Hello @YuletideMedia 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have checked your site and for me this seems to be working as intended. The only issue I see (using Chrome) is there no name shows up for our payment method (as the screenshot shows):
![image](https://user-images.githubusercontent.com/78153894/224687058-b55b9627-b88c-413b-9f51-67ab111c768a.png)

If you constantly encounter this issue, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/),

For now, I will close this thread. If you still need support, please open an engagement with our support team as advised in the top of this comment.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-03-13 11:20 UTC
Labels: support
