### ISSUE TITLE
Paypal not loading the checkout screen

### ISSUE THREAD

**Issue by jessicaseath1** [woocommerce/woocommerce-paypal-payments#1136] opened 2023-01-26 11:27 UTC
### Describe the Bug

I have loaded and activated the paypal plugin and have successfully connected my paypal account. I want the paypal checkout to be an option for my international customers. It is now given as an option on my checkout page, however when checking it, it just loads and the checkout button does not actually appear.

### To Reproduce

1. Go to https://helenwalne.com/checkout/
2. Click on Paypal
3. Scroll down to Pay via Paypal

### Screenshots

What it looks like: ![image](https://user-images.githubusercontent.com/123636059/214824158-b1c45977-d7d7-48f9-a53c-e9facbddc6a6.png)

What it should look like: 
![image](https://user-images.githubusercontent.com/123636059/214824287-040993f8-2374-4205-bc60-c9def4e7c362.png)

### Expected Behavior

The 'Place Order' button should appear.

### Actual Behavior

It just keeps loading and the button never appears.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed
**The above are all updated to the latest available versions.**

  ```

</details>

**Comment by Sirvijver** [comment] 2023-01-26 13:43
Hello @jessicaseath1 

Thank you for reaching out to us. This platform is intended mainly for development. If support requests that are opened here, they should be given a hint of what could cause the issue and advised to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you experience is most likely caused by a plugin conflict. To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

Please open a new engagement with our support team as instructed above, if you require additional support. I will now close this GitHub thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-01-26 13:43 UTC
