### ISSUE TITLE
plugin 2.0.0 Unexpected token 'T', "This email"... is not valid JSON paypal checkout

### ISSUE THREAD

**Issue by gunship800** [woocommerce/woocommerce-paypal-payments#1015] opened 2022-11-23 07:33 UTC
Upgrading to paypal payments 2.0.0 advanced credit card payments / direct card entry no longer works. 

Error: Unexpected token 'T', "This email"... is not valid JSON paypal checkout

I rollback to 1.9.4 and everything works again.  

How do I resolve?

**Comment by Sirvijver** [comment] 2022-12-13 11:06
Hello @gunship800 

Thank you for reaching out to us. The rollback is so far the only solution we have heard about. We had this reported one time before, but didn't get too much troubleshooting because the solution was where the communication ended with this merchant. We have not been able to reproduce this issue before, so if you want to check with us if we can find the cause for this issue, we want to ask you the following:
1) please open a ticket with our support team, we ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
2) Create a [staging site](https://wordpress.org/plugins/wp-staging/), so we can test with the 2.0.0 version of our plugin and see if we can find out what is causing the issue by performing conflict testing.
To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

Please reach out to us via the link provided before if you want to help us isolate the cause of this issue. I will close this thread and wait for a new thread to be opened with our support team.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 11:06 UTC
Labels: support
