### ISSUE TITLE
Something went wrong. Please try again or choose another payment source. (Paypal Payment Issue)

### ISSUE THREAD

**Issue by Asim848-tech** [woocommerce/woocommerce-paypal-payments#1055] opened 2022-12-01 06:44 UTC
We’re using the plugin called Woocommerce PayPal Payment in our WordPress site, however, We are getting an error while paying through Paypal: “Something went wrong. Please try again or choose another payment source”

I’ve checked our API credentials and all 4 boxes are populated and connected to our PayPal account, sandbox mode is disabled.

Not sure what is causing the error?

Thanks

**Comment by Sirvijver** [comment] 2022-12-02 12:38
Hello @Asim848-tech 
this issue can be caused by many things, but is most of the time not caused by a bug, but a conflict or misconfiguration. The best option to find out what is causing this is to perform [conflict testing](https://woocommerce.com/document/how-to-test-for-conflicts/). 
Because this is a support request, I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
We use GitHub as a developer's tool, not as a support tool. That is why I will close this thread.

Kind regards, 
Joost

**Closed as completed** 2022-12-02 12:40 UTC
Labels: support
