### ISSUE TITLE
wp-json/wc/store/cart/update-customer returns error 401: woocommerce_rest_missing_nonce

### ISSUE THREAD

**Issue by alorbach** [woocommerce/woocommerce-paypal-payments#2952] opened 2024-12-23 23:04 UTC
I maintain a woocommerce shop that is about 5-6 years old and all plugins are updated to their latest versions.
Since the last updates, the paypal plugin stopped working. 

I tracked it down to a failed request during the payment request which is being made to:
%website%/wp-json/wc/store/cart/update-customer

Request Method: POST
Status Code: 401 Unauthorized

The response is 
{
    "code": "woocommerce_rest_missing_nonce",
    "message": "Nonce-Header fehlt. Dieser Endpunkt erfordert eine g\u00fcltige Nonce.",
    "data": {
        "status": 401
    }
}

I added a workarround in my functions.php but this should only be a temporary workarround:
`add_filter( 'woocommerce_store_api_disable_nonce_check', '__return_true' );`

Please help me with this issue

**Comment by SydeKrystian** [comment] 2024-12-24 04:20
Hello @alorbach 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-12-24 04:20 UTC
Labels: support

**Comment by alorbach** [comment] 2024-12-24 06:46
I created a support case, and will wait for their response. Will get back here if necessary, Wish wish you a merry xmas ;)

**Comment by SydeKrystian** [comment] 2024-12-24 08:55
Hello @alorbach 

I appreciate you letting us know, and I wish you a Merry Christmas as well, filled with joy, family, and friends.  

Kind Regards,  
Krystian

**Comment by alorbach** [comment] 2025-01-03 12:31
I am afraid I think this is a Software BUG!
This Check was disabled by default:
![Image](https://github.com/user-attachments/assets/823919dc-9e14-43c8-9937-1d29c4ddc014)

It means orders are processed directly, and mandatory Invoice Address was not checked before the order was placed inside Woocommerce overt the Paypal plugin. Once I enabled this option, the user is taken to the Payment page where Invoice Name and Address is properly checked and confirmed.
