### ISSUE TITLE
Is not posible buy from paypal on my website

### ISSUE THREAD

**Issue by elynroe** [woocommerce/woocommerce-paypal-payments#1080] opened 2022-12-12 18:09 UTC
### Describe the Bug

Today a customer tried to make a purchase via paypal and was unable to do so. He got a message "The order could not be retrieved". From my woocommerce I can't do anything to solve this either.

### To Reproduce

1. Go to '…' Cart
2. Click on '…' Buy with Paypal
3. Scroll down to …' -
4. See error "The order could not be retrieved"

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2022-12-13 09:51
Hello @elynroe 

Thank you for reaching out to us, we are here to help.
This is a known issue, where most of the time the PayPal button is not being replaced instead of the WooCommerce button that is being used by other payment options (by default). Without using the PayPal button, the PayPal payment cannot succeed.

This issue can be caused by a conflicting plugin, theme or even an older browser from the customer itself. You can test this by doing [conflict testing](https://woocommerce.com/document/how-to-test-for-conflicts/). We could look into this, but we want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, because we only use GitHub for development activities, not support activities.

For now, I will close this thread and wait for the support ticket in case you need additional support from us.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 09:51 UTC
Labels: support
