### ISSUE TITLE
The / in the expiry date is being removed and therefore not validating.

### ISSUE THREAD

**Issue by marbleagency** [woocommerce/woocommerce-paypal-payments#2087] opened 2024-03-11 08:51 UTC
We have had several people know all come to us with the same issue. They say that when the browser is autofilling their card details, it is removing the '/' in the expiry but it also does not give them the option to click this to rectify it.  The issue appears to be mobile only.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by marbleagency** [comment] 2024-03-12 09:51
Lots of people saying 'card is not valid' when details are correct.

**Comment by SydeKrystian** [comment] 2024-03-13 07:01
Hello @marbleagency 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

At first glance, it looks like the issue is with your theme and the implementation of the new hosted card fields. The solution might be to update your theme or switch back to the old hosted card fields. I'll be able to provide more details after reviewing the system report.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-03-13 07:01 UTC
Labels: support

**Comment by marbleagency** [comment] 2024-03-13 07:24
It's not the theme as it still happens without any theme enabled. On top of that, the theme is fully updated and all fine on the status report. This is also happening on our second website using advanced card hosting.On 13 Mar 2024 07:01, Krystian Kep ***@***.***> wrote:
Hello @marbleagency
It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our support team.
When you contact our support team, please include a copy of your WooComnmerce system report. This will help us get to the bottom of your issue more quickly.
At first glance, it looks like the issue is with your theme and the implementation of the new hosted card fields. The solution might be to update your theme or switch back to the old hosted card fields. I'll be able to provide more details after reviewing the system report.
We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!
Kind regards,
Krystian

**Comment by SydeKrystian** [comment] 2024-03-13 08:03
Hello @marbleagency

To further investigate, we need the system report and your site's URL. Please contact our support team to help us analyze this issue.

Kind regards,
Krystian
