### ISSUE TITLE
Can't get any payment options to show

### ISSUE THREAD

**Issue by dwilliss** [woocommerce/woocommerce-paypal-payments#1499] opened 2023-07-09 23:12 UTC
### Describe the Bug

After setting up the woocommerce paypal payments, I go to the checkout page and get the message "Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements."

My state is Nebraska (United States) and I know PayPal operates here.

I believe everything to be setup correctly

### To Reproduce

Setup Woocommercte paypal payments plugin See screenshots below

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/a5e4f4cc-1990-457d-8ee1-0c693283c3e3)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/f84600c1-021e-4e0f-b618-5ccee5ad67dc)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/b90d7789-b047-424f-a123-883dd0038b6d)

### Expected Behavior

I expect to see payment options

### Actual Behavior

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/b1000a97-e677-4b2f-a46b-77922169d186)

### Environment

 - WordPress Version 6.2.2 running Astra theme.
 - WooCommerce Version  7.8.2 
 - Plugin Version  Version 2.1.0 
 - Browser [e.g. Chrome, Safari] and Version  Chrome Version 2.1.0 
 - Any other plugins installed

-  -   Contact Form 7
-  -   Woocommerce
-  -   Elementor
-  -   Elementor Pro

 - 

### Additional Details

The System Status says that the Checkout Page and Cart Page do not have the woocommerce widgets on them, but they do.  here's the checkout page in the Elementor editor.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/7d701cc7-5d77-443d-8068-22072190fa37)

<details><summary>System status</summary>

  ```
`
### WordPress Environment ###

WordPress address (URL): https://bookmumbles.com
Site address (URL): https://bookmumbles.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Debian)
PHP Version: 7.4.23
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB-1:10.6.4+maria~focal
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 15.47MB
Database Data Size: 12.53MB
Database Index Size: 2.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 3.22MB + Index: 0.39MB + Engine InnoDB
wp_posts: Data: 2.48MB + Index: 0.09MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxg_ccontact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vxg_ccontact_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vxg_ccontact_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 14
custom_css: 1
customize_changeset: 8
elementor_library: 10
nav_menu_item: 7
page: 21
post: 3
product: 3
revision: 482
wp_global_styles: 1
wpcf7_contact_form: 1
wpcf7r_action: 4
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Contact Form 7: by Takayuki Miyoshi – 5.7.7
Elementor Pro: by Elementor.com – 3.14.1
Elementor: by Elementor.com – 3.14.1
WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.8.2
WP Mail SMTP: by WP Mail SMTP – 3.8.0
Redirection for Contact Form 7: by Qube One – 2.9.0
WPForms Lite: by WPForms – 1.8.2.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Jetpack: by Automattic – 12.3
QR Code Woocommerce: by Gangesh Matta – 2.0.5
WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free ): by WebToffee – 1.7.9
WooCommerce Payments: by Automattic – 6.1.1
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WP PayPal: by naa986 – 1.2.3.20

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 4.1.6
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-10 04:51:53 -05:00
Options: ✔
Notes: 56
Onboarding: completed

### Action Scheduler ###

Complete: 94
Oldest: 2023-06-23 23:53:03 -0500
Newest: 2023-07-09 17:50:53 -0500

Failed: 358
Oldest: 2023-06-24 00:59:32 -0500
Newest: 2023-07-09 17:24:53 -0500

Pending: 9
Oldest: 2023-07-09 18:24:53 -0500
Newest: 2023-07-13 23:01:53 -0500


### Status report information ###

Generated at: 2023-07-09 18:06:52 -05:00

  ```

</details>

**Comment by Sirvijver** [comment] 2023-07-10 10:53
Hello @dwilliss 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering is usually caused by a WooCommerce setting or a 3rd party plugin. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

You will need to do this conflict testing and possibly play around with the WooCommerce settings in order to find out the cause for this issue. I would suggest you create a [staging site](https://wordpress.org/plugins/wp-staging/), so you can freely do this and not cause any harm to your live site. If you are not able to isolate what is causing this issue, I would advise you to engage our support team via the link above for additional support. They will be able to use this staging site and see if they are able to find the cause. We will close this GitHub thread now.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-07-10 10:53 UTC
Labels: support

**Comment by dwilliss** [comment] 2023-07-10 23:22
I disabled all plugins except WooCommerce and WooCommerce PayPal Payments, and switched to the 2019 Theme.
This is what I still get on the checkout page.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/a3d63950-6886-4809-87ed-4860ae0cb2ab)

I did notice that the PHP Soap client wasn't installed so I installed that but it didn't change anything.
Here's the latest status:

`
### WordPress Environment ###

WordPress address (URL): https://bookmumbles.com
Site address (URL): https://bookmumbles.com
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Debian)
PHP Version: 7.4.23
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB-1:10.6.4+maria~focal
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 15.54MB
Database Data Size: 12.55MB
Database Index Size: 2.99MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 3.20MB + Index: 0.39MB + Engine InnoDB
wp_posts: Data: 2.48MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vxg_ccontact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vxg_ccontact_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vxg_ccontact_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 16
custom_css: 1
customize_changeset: 16
elementor_library: 10
nav_menu_item: 6
page: 26
post: 3
product: 3
revision: 524
shop_order: 1
wp_global_styles: 1
wpcf7_contact_form: 1
wpcf7r_action: 4
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.8.2

### Inactive Plugins (12) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Contact Form 7: by Takayuki Miyoshi – 5.7.7
Elementor: by Elementor.com – 3.14.1
Elementor Pro: by Elementor.com – 3.14.1
Jetpack: by Automattic – 12.3
QR Code Woocommerce: by Gangesh Matta – 2.0.5
Redirection for Contact Form 7: by Qube One – 2.9.2
WooCommerce Payments: by Automattic – 6.1.1
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WPForms Lite: by WPForms – 1.8.2.2
WP Mail SMTP: by WP Mail SMTP – 3.8.0
WP PayPal: by naa986 – 1.2.3.20

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #590 - /merch-shop/
Cart: #755 - /minimal-cart/
Checkout: #753 - /minimal-checkout-form/
My account: ❌ Page visibility should be public
Terms and conditions: #464 - /deposit-policy/

### Theme ###

Name: Twenty Nineteen
Version: 2.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-11 04:51:53 -05:00
Options: ✔
Notes: 56
Onboarding: completed

### Action Scheduler ###

Complete: 101
Oldest: 2023-06-23 23:53:03 -0500
Newest: 2023-07-10 18:20:53 -0500

Failed: 384
Oldest: 2023-06-24 00:59:32 -0500
Newest: 2023-07-10 17:26:44 -0500

Pending: 4
Oldest: 2023-07-10 18:26:44 -0500
Newest: 2023-07-11 12:25:53 -0500


### Status report information ###

Generated at: 2023-07-10 18:22:39 -05:00
`

**Comment by InpsydeNiklas** [comment] 2023-07-11 11:18
@dwilliss The new Block Checkout page is not yet supported: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-does-paypal-payments-support-blocks
The PayPal buttons not loading on the Elementor Pro pages is a problem caused by the Elementor plugin. It will work using the regular `[woocommerce_checkout]` shortcode for your Checkout page instead of the Elementor editor.

Please [contact the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need additional guidance, as this GitHub repo is used for issue tracking and not for support requests. Thanks!

**Comment by dwilliss** [comment] 2023-07-12 06:02
That gives me this
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/bb5635b3-98cc-40c4-a64b-3d77eb735597)
I will contact support

**Comment by dwilliss** [comment] 2023-07-13 01:22
It turns out that you have to have the PayPal Smart Buttons configured to show up on the Checkout form.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1755696/86a7b190-6dcb-4375-8779-7f52e513b8ba)
