### ISSUE TITLE
no shipping/billing address transferred to PayPal for virtual products (245)

### ISSUE THREAD

**Issue by isabellainpsyde** [woocommerce/woocommerce-paypal-payments#282] opened 2021-09-27 12:37 UTC
**The problem**
Buying a virtual product will result in no “postal information” being shared from WooCommerce to PayPal.
This is the expected behavior for regular PayPal accounts, 

PayPal does not return billing address unless a setting is toggled on by PayPal support. In this case, it should be consumed and added to the order

**Steps to reproduce**
-ensure billing address feature is enabled for PayPal account (via PayPal support)
- buy a virtual product
- log into merchant dashboard
- order will not display any billing/shipping information
![image](https://user-images.githubusercontent.com/70694460/134909154-779ce2c6-6d26-4184-9576-e9559a20d77a.png)

**Expected behaviour**
Since virtual products are usually not accompanied by a shipping address, the billing address of the customer would at least be expected. 
But only when the PayPal account is enabled for the Billing Address feature.
Previous PayPal integrations such as PayPal Checkout Gateway displayed the billing address here for virtual products.

**Comment by mjpaulus** [comment] 2022-09-28 01:19
This same issue is happening to me now but with Non Virtual products.

**Comment by InpsydeNiklas** [comment] 2023-09-27 16:02
This is working as intended, so I'll close this. For now, the rule of thumb is that products should not be virtual if shipping address data is desired in PayPal. For non-virtual products, address data should always be shared with PayPal.
If anything is unclear, we advise reaching out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!

**Closed as completed by InpsydeNiklas** 2023-09-27 16:02 UTC
