### ISSUE TITLE
Woocommerce Paypal payment error Unexpected token '<', "

### ISSUE THREAD

**Issue by ChillandChew** [woocommerce/woocommerce-paypal-payments#2785] opened 2024-11-12 11:39 UTC
### Describe the Bug

An error occur when I make a payment by Paypal from Woocommerce. The error is: Unexpected token '<', "

### To Reproduce

1. Go to 'https://chillandchew.com.au'
2. Scroll down to 'Menus' section
3. Click on product image, a button Add to Cart appears, and click on it.
4. Click to Cart button on the top of the page.
5. Scroll down, and click on 'Proceed to checkout'
6. Click on Paypal button to pay.
7. See the error.

### Screenshots

![Image](https://github.com/user-attachments/assets/c9396476-e825-415f-a98d-695d348ff1d5)

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.2
 - Plugin (Paypal) Version 2.9.4
 - Browser Chrome and Version 130.0.6723.117 (Official Build) (x86_64)

### Additional Details

<details><summary>System status</summary>

  ```
  `
### WordPress Environment ###

WordPress address (URL): https://chillandchew.com.au
Site address (URL): https://chillandchew.com.au
WC Version: 9.3.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.27-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.2
WC Database Prefix: wpnn_
Total Database Size: 88.93MB
Database Data Size: 85.85MB
Database Index Size: 3.08MB
wpnn_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpnn_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpnn_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpnn_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpnn_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpnn_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wpnn_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpnn_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpnn_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wpnn_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpnn_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpnn_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpnn_options: Data: 5.06MB + Index: 0.14MB + Engine InnoDB
wpnn_postmeta: Data: 50.38MB + Index: 0.52MB + Engine InnoDB
wpnn_posts: Data: 29.16MB + Index: 0.25MB + Engine InnoDB
wpnn_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpnn_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpnn_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpnn_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpnn_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpnn_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpnn_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpnn_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpnn_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpnn_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpnn_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpnn_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpnn_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 513
custom_css: 1
customize_changeset: 12
elementor_library: 30
nav_menu_item: 9
page: 29
post: 14
product: 45
revision: 548
shop_order_placehold: 6
wdt_footers: 8
wdt_headers: 5
wdt_mega_menus: 1
wp_navigation: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.18.5
Contact Form 7: by Takayuki Miyoshi – 5.9.8
Duplicate Page: by mndpsingh287 – 4.5.4
Elementor Pro: by Elementor.com – 3.23.3
Elementor: by Elementor.com – 3.24.3
Faryita Plus: by the WeDesignTech team – 1.0.0
Faryita Pro: by the WeDesignTech team – 1.0.0
Faryita Shop: by the WeDesignTech team – 1.0.0
LiteSpeed Cache: by LiteSpeed Technologies – 6.5.1
One Click Demo Import: by OCDI – 3.2.1
WeDesignTech Elementor Addon: by the WeDesignTech team – 1.0.0
WooPayments: by WooCommerce – 8.4.0
WooCommerce PayPal Payments: by WooCommerce – 2.9.4
WooCommerce Shipping & Tax: by WooCommerce – 2.8.3
WooCommerce: by Automattic – 9.3.2 (update to version 9.3.3 is available)
WP Headers And Footers: by WPBrigade – 3.0.0
YITH WooCommerce Compare: by YITH – 2.43.0
YITH WooCommerce Quick View: by YITH – 1.43.0

### Inactive Plugins (1) ###

FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.2.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 602 B

### WC Pages ###

Shop base: #13 - /shop/
Cart: #33 - /cart-3/ -  Contains the [woocommerce_cart] shortcode
Checkout: #15 - /checkout/ -  Contains the woocommerce/checkout block
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Faryita
Version: 1.0.0
Author URL: https://wedesignthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.4.0
Connected to WPCOM: Yes
WPCOM Blog ID: 238926411
Account ID: acct_1QKATeCA8oU5wWns
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-11-13 04:41:03 +09:30
Options: ✔
Notes: 69
Onboarding: skipped

### Action Scheduler ###

Complete: 63
Oldest: 2024-10-12 13:43:57 +0000
Newest: 2024-11-12 11:32:27 +0000

Failed: 3
Oldest: 2024-09-20 04:50:26 +0000
Newest: 2024-11-12 04:31:46 +0000

Pending: 1
Oldest: 2024-11-12 16:45:26 +0000
Newest: 2024-11-12 16:45:26 +0000


### Status report information ###

Generated at: 2024-11-12 21:09:08 +09:30
`
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-11-14 07:44
Hello @ChillandChew 


It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin.  You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Closed as completed by SydeKrystian** 2024-11-14 07:44 UTC
Labels: support
