### ISSUE TITLE
WooCommerce PayPal Payments - Advanced Card Processing

### ISSUE THREAD

**Issue by areawebtrovaweb** [woocommerce/woocommerce-paypal-payments#2352] opened 2024-06-17 17:15 UTC
### Describe the Bug

I enabled the Advanced Card Processing, as you can see from the first screen. But for some reason, in the Checkout Page, it doesn't show the card's logos that I chosed, and it doesn't even let me put the card's info, so when I click on the button to Complete the Order, it doesn't even work

I enabled it on my website https://giuseppemonticaffe.com/
Sorry if it will be a bit slow, but it's still under development and optimizations must be done

### To Reproduce

1. Go to the shop. 
2. Add any product to the cart and go to the Checkout Page
3. Scroll down to Payment Options and the "Credit Card" option

### Screenshots

![Screenshot 2024-06-17 190447](https://github.com/woocommerce/woocommerce-paypal-payments/assets/101572231/7d107eed-1794-4b05-a38a-2f8ea8a0e763)
![Screenshot 2024-06-17 190456](https://github.com/woocommerce/woocommerce-paypal-payments/assets/101572231/2e5083ab-3824-4444-915a-6135a8845b23)

### Expected Behavior

It should show the fields to insert all the card's info

### Actual Behavior
It doesn't show anything and the button to complete the order doesn't do nothing

### Environment

 - WordPress Version: 6.5.4
 - WooCommerce Version: 8.9.3
 - Plugin Version: 2.8.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome 126.0.6478.61
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-06-18 10:12
Hello @areawebtrovaweb 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-06-18 10:12 UTC
Labels: support
