### ISSUE TITLE
i am unable to enable pay later, the checkboxes seem disabled. not clickable.

### ISSUE THREAD

**Issue by shanzawaheed** [woocommerce/woocommerce-paypal-payments#1349] opened 2023-05-01 00:17 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-05-09 10:45
Hello @shanzawaheed 

This platform is intended mainly for development, and we would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing is most likely caused by the "Vaulting" feature being turned on. It is not possible to use the vaulting feature and any Alternative Payment Method at the same time (thus the Pay Later feature will be greyed out if you have vaulting activated).

I will close this ticket now. Please reach out to our support team if you have additional questions.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-05-09 10:45 UTC
Labels: support
