### ISSUE TITLE
Fatal error: Paypal Payments

### ISSUE THREAD

**Issue by acolmery** [woocommerce/woocommerce-paypal-payments#2913] opened 2024-12-12 19:44 UTC
### Describe the Bug

PHP Fatal error: Uncaught LogicException: No PPCP container, probably
called too early when the plugin is not initialized yet. in
/home/nicavps/[nicawsc.com/wp-content/plugins/woocommerce-paypal-payments/src/PPCP.php:35](http://nicawsc.com/wp-content/plugins/woocommerce-paypal-payments/src/PPCP.php:35)
This error indicates the plugin might be malfunctioning or interacting
improperly with WooCommerce. When we skip this plugin during profiling,
load times improve by approximately 2 seconds.

### To Reproduce

1. Go to 'nicawsc.com'
2. Page takes several minutes to load
 When we skip this plugin during profiling,
load times improve by approximately 2 seconds.

### Expected Behavior

I expected the page to load within a few seconds.

### Actual Behavior

Intermittently, the site takes over 4 minutes to load.

### Environment

 - WordPress Version 6.7.1
 - WooCommerce Version Version 9.4.3
 - Plugin Version 2.9.5
 - Browser [e.g. Chrome, Safari] and Version Brave 1.73.97, Firefox 133.0.3
 - Any other plugins installed - Askimet Anti Spam, Bold Grid Easy SEO, Bold Grid Gallery, Bold Grid Inpsirations, Health Chek & Troubleshooting, Image Optimization by Optimole, Jetpack Boost, Page links to, Post & Page Builder, Printful Integration for WooCommerce, Remove Footer & Credit, Total Upkeep, Total Upkeep Premium, WooCommerce, WooCommerce Legacy REST API, WooCommerce PayPal Payments, WooCommerce Shipping & Tax, WooPayments, WP Menu Cart, WP Super Cache

### Additional Details

Using Neve Theme

**Comment by SydeKrystian** [comment] 2024-12-13 06:57
Hello @acolmery 

We are not currently aware of any widespread issue of this kind. To help resolve this, I recommend performing a full conflict test to rule out potential conflicts with your theme or another plugin. Here’s how to proceed:

1. Temporarily activate the default theme Storefront.
2. Disable all other plugins except for WooCommerce and PayPal Payments.

If the issue is resolved, re-enable the plugins one by one. Please let us know which plugin triggers the fatal error, as identifying the conflicting plugin will help us guide you further. 

 If issue persist after these steps we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind Regards,
Krystian

**Closed as completed by SydeKrystian** 2024-12-13 06:57 UTC
Labels: support

**Comment by jrthib** [comment] 2024-12-16 16:05
Also happening to my site as well

**Comment by erikdemarco** [comment] 2025-06-10 07:33
any update about this? affecting my site as well

**Comment by SydeKrystian** [comment] 2025-06-10 08:21
Hello @erikdemarco 

Please follow the steps outlined in this post: [https://github.com/woocommerce/woocommerce-paypal-payments/issues/2913#issuecomment-2540689826](https://github.com/woocommerce/woocommerce-paypal-payments/issues/2913#issuecomment-2540689826) and contact us directly so we can help you further.

At this point, we don’t know the exact cause of the issue, as we haven’t received enough details from you.

Kind regards,
Krystian
