### ISSUE TITLE
Checkout with PayPal possible without accepting terms and conditions

### ISSUE THREAD

**Issue by Jule1608** [woocommerce/woocommerce-paypal-payments#1618] opened 2023-08-23 10:54 UTC
### To Reproduce

1. Go to (https://excursions-lamallorca.com/ausfluege/cala-ratjada-express/)
2. Click on 'Calender a date, choose a person, click book now, after directed to checkout click PayPal without accepting terms''
3. See error

### Expected Behavior

<!No direkting to PayPal without accepting terms.-->

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-08-24 13:05
Hello @Jule1608 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you described (and I confirmed by checking your site) was an issue that was caused by a plugin conflict with the 3rd party plugin: WooCommerce Checkout Manager by QuadLayers. 
Since you did not provide the system report, I cannot check what version of our plugin you are running. I will close this thread and suggest you open a support request via the link provided above and include the system report, so we can take a closer look at this.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-08-24 13:05 UTC
Labels: support
