### ISSUE TITLE
Paypay error from Instagram link

### ISSUE THREAD

**Issue by lauremipsum46** [woocommerce/woocommerce-paypal-payments#1334] opened 2023-04-18 19:49 UTC
Hello, 

I encontre an issue with paypal paiement only from the link from instagram. An error message appear when someone try to pay : 

All is working fine from anywhere instead of insta link... MISSING SHIPPING ADDRESS The shipping address is required when 'shipping8preference=SET_PROVIDED_ADRESS'

All the fiels are ful... 

### To Reproduce

1. Go to any instagram account
2. Search nature_et_sens.eu (cosmetique bio)
3. Click on the weblink on the bio
4. Add a product in the cart
5. Go to the checkout page
6. Try to pay with Paypal

### Expected Behavior

Just to could pay with paypal from the instagram link

### Environment

 - WordPress Version : 6.2
 - WooCommerce Version : 7.6
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed : themify, price by countrie

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-04-20 10:39
Hello @lauremipsum46 

We have had more reports of this, but unfortunately the cause was not 1 specific situation, and we can't tell you what you exactly need to do in order to resolve this.
It seems this issue is most of the time caused by 3rd party plugins or the theme that is affecting the billing details before they are sent to PayPal. PayPal seems to think that the shipping address is not sent and returns this failure.
The first thing I would advise you to do is to find out what is triggering this issue and see if you can reproduce this issue. For this purpose you should create a staging site and see if you can recreate an order, using a sandbox account, that generates the same errors that you saw from the customers. Please create a backup of the site first before proceeding.

Once you have found out how you can reproduce the issue, you should do conflict testing to rule out eventual issues with the theme or a different plugin.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp


Some causes we encountered in the past:
We saw that the Divi theme caused this issue as well, and since you are using this.
The use of incorrect [WooCommerce short codes](https://woocommerce.com/document/woocommerce-shortcodes/)
One merchant told us that the Germanized plugin caused the issue on a single page checkout. When he encounters the issue, he was able to resolve it on the checkout page, by switching the box “Send delivery to a different address” and then uncheck it again.


Because we only use this site for development activities (and not support requests), I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance, as the team is happy to look into this for you. For now, we will close this thread as a support thread. Thanks!

**Closed as completed by Sirvijver** 2023-04-20 10:39 UTC
Labels: support
