### ISSUE TITLE
woocommerce

### ISSUE THREAD

**Issue by keekee360** [woocommerce/woocommerce-paypal-payments#1421] opened 2023-06-05 18:54 UTC
When I connect the paypal payments to my client site,  it say successful go back to woocommerce I get an error.

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@mrcool.ushvacservices.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

### Environment

 - WordPress Version 6.62 
 - WooCommerce Version 7.72 
 - Plugin Version 2.05
 - Browser [e.g. Chrome, Safari] and Version firefox and chrome

`
status

WordPress address (URL): http://mrcoolminisplitdiy.com
Site address (URL): http://mrcoolminisplitdiy.com
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.42-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.2
WC Database Prefix: wp_
Total Database Size: 49.88MB
Database Data Size: 47.63MB
Database Index Size: 2.25MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.25MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 14.52MB + Index: 0.42MB + Engine InnoDB
wp_posts: Data: 28.52MB + Index: 0.13MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 121
customize_changeset: 33
elementor_library: 1
es_slider: 1
nav_menu_item: 8
page: 9
post: 3
product: 4
revision: 498
wpcf7_contact_form: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Contact Form 7: by Takayuki Miyoshi – 5.7.7
Elementor: by Elementor.com – 3.13.4
Essential Addons for Elementor: by WPDeveloper – 5.7.4
WooCommerce PayPal Payments: by WooCommerce – 2.0.5
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce: by Automattic – 7.7.2

### Inactive Plugins (6) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Easy Slider Revolution: by  – 1.0.0
Jetpack: by Automattic – 12.1.1
LayerSlider: by Kreatura Media – 7.1.4
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.25.18
MetaSlider: by MetaSlider – 3.31.0

### Must Use Plugins (1) ###

WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #73 - /shop/
Cart: #74 - /cart/
Checkout: #75 - /checkout/
My account: #76 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kenta Inspire
Version: 1.0.1
Author URL: https://www.wpmoose.com
Child Theme: ✔
Parent Theme Name: Kenta
Parent Theme Version: 1.2.0
Parent Theme Author URL: https://www.wpmoose.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-06 14:30:05 +00:00
Options: ✔
Notes: 77
Onboarding: skipped

### Action Scheduler ###

Complete: 36
Oldest: 2023-05-18 14:30:26 +0000
Newest: 2023-06-05 18:49:11 +0000

Failed: 2
Oldest: 2023-05-22 21:12:11 +0000
Newest: 2023-06-01 11:27:20 +0000

Pending: 1
Oldest: 2023-06-05 22:33:38 +0000
Newest: 2023-06-05 22:33:38 +0000

### Status report information ###

Generated at: 2023-06-05 18:52:24 +00:00
`

**Comment by Sirvijver** [comment] 2023-06-06 10:46
Hello,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

For now, I see in the system report that onboarding was not performed successfully, so I would try this again while deactivating all other plugins and possibly replacing your current theme with the [default storefront theme](https://wordpress.org/themes/storefront/), to verify if this issue might be caused by a plugin conflict.

It might also help to take your time when onboarding. Sometimes the onboarding process when the last step of the process is rushed and the process does not get the time to perform all activities that are running in the background.

Please try these option and open a support request with our team if needed. For now, we will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-06-06 10:46 UTC
Labels: support
