### ISSUE TITLE
PayPal Express Button ISSUE On Single Product Page

### ISSUE THREAD

**Issue by noman-work** [woocommerce/woocommerce-paypal-payments#1333] opened 2023-04-18 14:25 UTC
### Describe the Bug

PayPal Express Button ISSUE On Single Product Page - When there are 2 variables on the product if one is Selected the button show but it's required to select both variables in order to purchase the product.

![Issue](https://www.nakmuaywholesale.com/wp-content/uploads/2023/04/Screenshot-2023-04-18-at-8.14.32-PM.png)

**Comment by Sirvijver** [comment] 2023-04-19 06:22
Hello @noman-work 
We have responded to the support thread you have opened with us via WooCommerce. I will close this thread because we only use GH for development activities (not support) and continue the support via the WooCommerce support thread. 

We do not see this behavior in our own testing environment, so believe this is caused by a plugin conflict (pending your tests). Thanks

**Closed as completed by Sirvijver** 2023-04-19 06:22 UTC
Labels: support
