### ISSUE TITLE
"Detected container element removed from DOM" error in console after address update

### ISSUE THREAD

**Issue by stfn00** [woocommerce/woocommerce-paypal-payments#973] opened 2022-11-09 10:13 UTC
### Describe the Bug

Hi, when the shipping address is updated the PayPal API returns an error regarding removed items in the DOM, is this an error that may actually cause problems in the future?

### To Reproduce

1. Update Shipping address on checkout
2. Error show in console

### Screenshots

<img width="505" alt="image" src="https://user-images.githubusercontent.com/36002130/200801548-542276dc-b274-4585-98b7-b0e131a03ed1.png">

### Environment

 - WordPress Version: 6.1
 - WooCommerce Version: 7.1.0
 - Plugin Version: 1.9.5
 - Browser: Chrome
 - Other plugins of WC:
 - - WooCommerce Conditional Shipping and Payments
 - - WooCommerce Stripe Gateway

**Comment by Sirvijver** [comment] 2022-12-13 11:43
Hello @stfn00 

we have encountered this issue before and with this merchant the issue was caused by the theme they were using, so you might want to test with a different theme and see if the issue still persists. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We actually don't do support via GitHub and use this platform only for development activities, so if you require additional support I advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. For now I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 11:43 UTC
Labels: support
