### ISSUE TITLE
Undefined property: stdClass::$pay_upon_invoice in ppcp-wc-gateway/src/Gateway/PayUponInvoice

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-paypal-payments#889] opened 2022-10-06 16:37 UTC
I am getting these Warnings in my log file:
```
[06-Oct-2022 07:54:24 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 07:54:24 UTC] PHP Warning:  Attempt to read property "payment_reference" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 07:54:24 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
[06-Oct-2022 07:54:24 UTC] PHP Warning:  Attempt to read property "deposit_bank_details" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
[06-Oct-2022 08:18:55 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 08:18:55 UTC] PHP Warning:  Attempt to read property "payment_reference" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 08:18:55 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
[06-Oct-2022 08:18:55 UTC] PHP Warning:  Attempt to read property "deposit_bank_details" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
[06-Oct-2022 08:30:49 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 08:30:49 UTC] PHP Warning:  Attempt to read property "payment_reference" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 234
[06-Oct-2022 08:30:49 UTC] PHP Warning:  Undefined property: stdClass::$pay_upon_invoice in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
[06-Oct-2022 08:30:49 UTC] PHP Warning:  Attempt to read property "deposit_bank_details" on null in /srv/data/web/vhosts/www.mysite.de/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php on line 235
```

While these might not cause harm, they pollute my log files. Not sure what exactly causes them.

### Environment

 - WordPress Version: 6.0.2
 - WooCommerce Version: 6.9.4
 - Plugin Version: 1.9.3
 - PHP Version: 8.1.0

**Comment by InpsydeNiklas** [comment] 2022-12-16 10:37
These warnings were caused by PHP 8.1 and have been resolved in update 2.0 and newer.

**Closed as completed by InpsydeNiklas** 2022-12-16 10:37 UTC
Labels: bug
