### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Khalid111a** [woocommerce/woocommerce-paypal-payments#1457] opened 2023-06-21 09:37 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-06-21 09:44
Hello @Khalid111a 

since you left no details I will close this thread. If you have a support request, I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The GitHub forum only handles development activities that have been proven to be caused by our plugin. I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-06-21 09:44 UTC
