### ISSUE TITLE
Woocommerce Paypal Payments

### ISSUE THREAD

**Issue by hereisGiacomo** [woocommerce/woocommerce-paypal-payments#1095] opened 2022-12-21 08:39 UTC
### Describe the Bug

Hello. No matter what I do if "Italy" is the country selected at the checkout when I choose "paypal" the website gives the error "MISSIN_SHIPPING_ADDRESS The shipping address is required when 'shipping_preferences="SET_PROVIDED_ADDRESS"

### To Reproduce

the website is under mantainance mode to avoid problems, the address is thesciusconcept.it

### Environment

 - Latest WordPress Version
 - Latest WooCommerce Version
 - Latest Plugin Version
 - On every browser and devices Browser [e.g. Chrome, Safari] and Version
 - It does not work with every plugin disabled Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-01-13 13:27
Hello @hereisGiacomo 

This issue was believed to be resolved with a previous release, but I just saw the bug we had was reopened. It seems the failure is caused by a conflict with the Divi theme and/or the Germanized plugin. However, we were told that the issue can also be caused without the use of this plugin (this by:  create a new WordPress user from the my-account page (must be enabled in WooCommerce settings), visit checkout page, provide billing data, shipping address was automatically checked (must be configured in WooCommerce settings), I unchecked shipping address, provided Advanced Card Processing details and confirmed the payment --> error).

However, we are still investigating this and don't have a fix available for you at the moment. If you want to be made aware of any fix becoming available, I would need to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly, because we do not provide support via the GitHub interface (only used for development activities). I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-01-13 13:27 UTC
Labels: support
