### ISSUE TITLE
The payment Methond not showing on checkout

### ISSUE THREAD

**Issue by shanzawaheed** [woocommerce/woocommerce-paypal-payments#1350] opened 2023-05-02 14:44 UTC
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-05-09 10:50
Hello @shanzawaheed 

Thank you for reaching out to us, we are here to help.
This issue can be caused by many aspects of a WordPress website, so in order to give you a good response, we would need to have much more information, like the system report and logs. However, we don't provide plugin support via GitHub, since we only do development activities on this platform, if you need more support we would advise you to [reach out to our support team via this interface](https://paypal.inpsyde.com/docs/request-support/).

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). 

We will close this thread now and wait for you to open a new thread with our support team in case needed.
Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-05-09 10:50 UTC
Labels: support
