### ISSUE TITLE
Since version > 2.2.0 the PayPal Checkout button on single product pages does not redirect anymore

### ISSUE THREAD

**Issue by CppClown** [woocommerce/woocommerce-paypal-payments#1664] opened 2023-09-04 19:15 UTC
### Describe the Bug

Since updating the plugin from v2.2.0 to v2.2.1, PayPal checkout button no longer work on single product pages: When trying to redirect to PayPal, it loads endlessly and the icon does not stop spinning. An update to version 2.2.2 does not change this.

### To Reproduce

1. Go to a single product page.
2. Click on the 'PayPal Checkout' button.
3. After 3 minutes it still tries to load the PayPal page.

### Expected Behavior

1. Go to a single product page.
2. Click on the 'PayPal Checkout' button.
3. After some seconds the PayPal login site appears.

![RedirectToPayPal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/128615365/a1a8f45b-72b2-40eb-b47a-8195b97997ea)

### Actual Behavior

1. Go to a single product page.
2. Click on the 'PayPal Checkout' button.
3. When trying to redirect to PayPal, it loads endlessly and the icon does not stop spinning.

![RedirectToPayPalBroken](https://github.com/woocommerce/woocommerce-paypal-payments/assets/128615365/f31a068f-7ddb-49db-8fba-a50e91f60ead)

### Environment

 - WordPress Version: 6.3.1
 - WooCommerce Version: 8.0.3
 - Plugin Version: 2.2.2
 - Browser [e.g. Chrome, Safari] and Version
     - Chrome version 116.0.5845.141
     - Firefox version 117.0
     - Edge version 116.0.1938.69
     - No other browsers were tested.
 - Any other plugins installed: None

### Additional Details

- Occurs for example with theme "Twenty Twenty-Three"

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment] 2023-09-05 08:39
Hi @CppClown 
Thanks for reporting this issue. Can you please give it a try with [this version](https://drive.google.com/uc?export=download&id=19vYtY2wYGt13Ru6d72iKKADAKy0O2HPB) and let us know how this works for you? Thank you!

**Comment by beninverse** [comment] 2023-09-05 12:27
@InpsydeNiklas 

I was just looking for this issue and came across your post. That version that you provided does solve my issue, thanks for your post. 

With that being said, I looked at the changelog and it still says the plugin you provided is 2.2.2 (which was installed but not functioning correctly). Is what you provided a beta for the next version or something else? I'd like to know what the deal is with what you provided before sending to a production environment. A diffcheck of the two shows substantial changes.

Thanks

**Comment by InpsydeNiklas** [comment] 2023-09-05 13:25
@beninverse The linked package is based on version 2.2.2 but contains the changes from #1655 and also [four more commits](https://github.com/woocommerce/woocommerce-paypal-payments/commits/PCP-1971-product-page-pp-button-keep-loading-popup-wc-add-to-cart-params-is-not-defined-error-in-woo-commerce) that were made since the 2.2.2 update. 
So yes, these changes will be part of the next update and have gone through initial testing but have not yet completed all release tests. While we don't anticipate any issues with this package, we can't rule them out. In any case, any feedback is highly appreciated, even when only briefly testing it. In the meantime, another way to work around this issue may be a downgrade to a previous plugin version such as [2.2.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.2.0) or [2.1.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0).

**Comment by beninverse** [comment] 2023-09-05 15:21
thanks @InpsydeNiklas , so are you confirming that this issue does not exist in 2.2.0 and 2.1.0? 

we are looking to send it to prod soon. while i'm confident that updates are fine, rolling the dice isn't something we can do here.

i appreciate your response, thanks

**Comment by CppClown** [comment] 2023-09-05 15:33
@InpsydeNiklas

Thank you for the quick reply. I can confirm that the [version ](https://drive.google.com/uc?export=download&id=19vYtY2wYGt13Ru6d72iKKADAKy0O2HPB )you provided solves this issue.

Can you estimate when the new update will be released?

**Comment by InpsydeNiklas** [comment] 2023-09-05 15:53
Thanks for the feedback! There are a few reports about this problem, but they only started after the 2.2.1 update. This update made some specific tweaks to the single product page behavior, so earlier versions are unlikely to be affected by this specific issue.

Updates are released in a three-week cycle, and the next one is expected to be released in about two weeks. A few days before the official release, there will be a [release candidate version available to test from here](https://github.com/woocommerce/woocommerce-paypal-payments/releases). This version will be identical to the release as long as no major issues are reported.

**Closed as completed** 2023-09-07 07:39 UTC
Labels: bug

**Comment by hamadgill** [comment] 2023-09-12 01:21
The updated version you provided seemed to fix the issue ! Thank you

**Comment by hamadgill** [comment] 2023-12-06 16:53
Seems to be an issue with the single product PayPal button again, when pressed it loads then exits and gives this error message **** - Something Went Wrong. Please Try Again Or Choose Another Payment Source.****

Once added to the cart or page refreshed after the error and then tested again on a single product page works fine, so there might be a cache issue. But seems the button loads separately since it displays different buttons depending on location for Example countries without pay later will show one big button and countries with pay later will show two buttons one with pay later


The issue is recent before it was working fine even when the page was cached. Maybe since the new WooCommerce updates something changed.
