### ISSUE TITLE
 CANNOT_BE_ZERO_OR_NEGATIVE When Applying %100 Coupons Code 

### ISSUE THREAD

**Issue by PineappleProduction** [woocommerce/woocommerce-paypal-payments#941] opened 2022-10-26 09:33 UTC
### Describe the Bug

We created a coupon that when applied the overall sum becomes 0.00 €

We can create a subscription & finalize the checkout process using Stripe, but when selecting PayPal as a payment method this error appears: 

CANNOT_BE_ZERO_OR_NEGATIVE Must be greater than zero. If the currency supports decimals, only two decimal place precision is supported.

### To Reproduce

1. Go to 'Checkout page'
2. Add a coupon
3. Select PayPal as Payment Method
4. Click on "Pay with Paypal button" 
5. Error appears on the top of the page and can't finalize payment: CANNOT_BE_ZERO_OR_NEGATIVE Must be greater than zero. If the currency supports decimals, only two decimal place precision is supported.

<details><summary>System status</summary>

  ```
`
### WordPress Environment ###

WordPress address (URL): https://www.siteadress.com
Site address (URL): https://www.siteadress.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.24
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.5.15-MariaDB-0+deb11u1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_sfx_
Datenbank-Gesamtgröße: 815.40MB
Datenbank-Datengröße: 736.80MB
Datenbank-Indexgröße: 78.60MB
wp_sfx_woocommerce_sessions: Daten: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_sfx_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sfx_woocommerce_order_items: Daten: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_sfx_woocommerce_order_itemmeta: Daten: 1.52MB + Index: 0.81MB + Engine InnoDB
wp_sfx_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sfx_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_actionscheduler_actions: Daten: 2.09MB + Index: 1.14MB + Engine InnoDB
wp_sfx_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_actionscheduler_logs: Daten: 2.33MB + Index: 0.53MB + Engine InnoDB
wp_sfx_automatewoo_abandoned_carts: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_sfx_automatewoo_customers: Daten: 0.09MB + Index: 0.27MB + Engine InnoDB
wp_sfx_automatewoo_customer_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_automatewoo_events: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_automatewoo_guests: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sfx_automatewoo_guest_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_automatewoo_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_automatewoo_log_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_automatewoo_queue: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_automatewoo_queue_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_comments: Daten: 1.52MB + Index: 0.95MB + Engine InnoDB
wp_sfx_ctf_feed_locator: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_depicter_documents: Daten: 2.03MB + Index: 0.03MB + Engine InnoDB
wp_sfx_depicter_options: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_e_notes: Daten: 0.03MB + Index: 0.17MB + Engine InnoDB
wp_sfx_e_notes_users_relations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_e_submissions: Daten: 0.03MB + Index: 0.27MB + Engine InnoDB
wp_sfx_e_submissions_actions_log: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_sfx_e_submissions_values: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_ff_scheduled_actions: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_coupons: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_draft_submissions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_entry_details: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_forms: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_form_analytics: Daten: 1.48MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_form_meta: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_order_items: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_submissions: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_submission_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_subscriptions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_fluentform_transactions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_hfcm_scripts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_mailpoet_log: Daten: 3.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_newsletters: Daten: 1.41MB + Index: 0.03MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_links: Daten: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_newsletter_templates: Daten: 12.06MB + Index: 0.00MB + Engine InnoDB
wp_sfx_mailpoet_scheduled_tasks: Daten: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_sfx_mailpoet_scheduled_task_subscribers: Daten: 3.52MB + Index: 1.50MB + Engine InnoDB
wp_sfx_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_mailpoet_sending_queues: Daten: 2.52MB + Index: 0.03MB + Engine InnoDB
wp_sfx_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_mailpoet_statistics_clicks: Daten: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_sfx_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_statistics_newsletters: Daten: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_sfx_mailpoet_statistics_opens: Daten: 0.13MB + Index: 0.33MB + Engine InnoDB
wp_sfx_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sfx_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_mailpoet_subscribers: Daten: 0.27MB + Index: 0.34MB + Engine InnoDB
wp_sfx_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_subscriber_segment: Daten: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_sfx_mailpoet_subscriber_tag: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_mailpoet_tags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_user_agents: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_sfx_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_options: Daten: 12.05MB + Index: 0.17MB + Engine InnoDB
wp_sfx_payone_api_log: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_sfx_payone_transaction_log: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_sfx_postmeta: Daten: 396.55MB + Index: 13.88MB + Engine InnoDB
wp_sfx_posts: Daten: 198.33MB + Index: 3.70MB + Engine InnoDB
wp_sfx_pum_subscribers: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_sfx_redirection_404: Daten: 1.02MB + Index: 0.11MB + Engine InnoDB
wp_sfx_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_sfx_redirection_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfx_revslider_css: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_css_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_revslider_layer_animations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_revslider_navigations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_revslider_navigations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_revslider_sliders: Daten: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_sliders_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_slides: Daten: 0.38MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_slides_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_static_slides: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_revslider_static_slides_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_simple_history: Daten: 19.05MB + Index: 6.27MB + Engine InnoDB
wp_sfx_simple_history_contexts: Daten: 63.09MB + Index: 39.20MB + Engine InnoDB
wp_sfx_tec_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_tec_occurrences: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_term_relationships: Daten: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_sfx_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_usermeta: Daten: 3.36MB + Index: 2.84MB + Engine InnoDB
wp_sfx_users: Daten: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_sfx_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_sfx_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_wc_customer_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_sfx_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_wc_order_product_lookup: Daten: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_sfx_wc_order_stats: Daten: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_sfx_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfx_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_sfx_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_wpstg_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfx_yoast_indexable: Daten: 3.45MB + Index: 1.52MB + Engine InnoDB
wp_sfx_yoast_indexable_hierarchy: Daten: 0.34MB + Index: 0.34MB + Engine InnoDB
wp_sfx_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sfx_yoast_primary_term: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_sfx_yoast_seo_links: Daten: 0.47MB + Index: 0.27MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 6
attachment: 1428
aw_workflow: 1
clients: 5
course: 83
custom_css: 2
elementor_icons: 1
elementor_library: 58
elementskit_content: 12
flamingo_contact: 6
flamingo_inbound: 4
forum: 1
glossar: 227
learning-hack: 12
lesson: 9
mailpoet_page: 1
nav_menu_item: 50
oembed_cache: 1
page: 127
partner: 1
popup: 7
popup_theme: 8
post: 26
postman_sent_mail: 250
product: 18
question: 4
quiz: 6
reply: 3
revision: 8560
shop_coupon: 9
shop_order: 849
shop_order_refund: 2
shop_subscription: 344
synchronous-learning: 6
tec_tc_attendee: 5
tec_tc_order: 42
tec_tc_ticket: 5
testimonials: 7
ticket-meta-fieldset: 9
topic: 3
tribe_events: 72
tribe_organizer: 8
tribe_rsvp_attendees: 1482
tribe_rsvp_tickets: 59
tribe_venue: 7
viwec_template: 21
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Advanced Custom Fields PRO: von WP Engine – 6.0.3
bbPress: von Die Mitwirkenden von bbPress – 2.6.9
Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.5
GTM4WP: von Thomas Geiger – 1.16.1
Elementor Pro: von Elementor.com – 3.7.7
Elementor: von Elementor.com – 3.7.8
ElementsKit Lite: von Wpmet – 2.7.3
Email Template Customizer for WooCommerce: von VillaTheme – 1.1.16
Emeritus Core: von Qode Interactive – 1.0
Emeritus Membership: von Qode Interactive – 1.0
SBS Emeritus Integration: von Step-Byte-Service GmbH – 1.0.0
Envato Market: von Envato – 2.0.7
Event Tickets Plus: von The Events Calendar – 5.6.1
Event Tickets: von Der Veranstaltungskalender – 5.5.2
Fluent Forms Connector for MailPoet: von WPManageNinja LLC – 1.0.1
Fluent Forms: von Contact Form - WPManageNinja LLC – 4.3.20
Fluent Forms Pro Add-On-Paket: von Fluent Forms – 4.3.19
Header Footer Code Manager: von 99robots – 1.1.29
Loco Translate: von Tim Whitlock – 2.6.3
MailPoet Premium: von MailPoet – 3.101.0
MailPoet: von MailPoet – 3.101.1
Post SMTP: von Post SMTP – 2.1.10
Qi Addons For Elementor: von Qode Interactive – 1.5.4
Qode Framework: von Qode Interactive – 1.1.4
Redirection: von John Godley – 5.3.4
SBS Wordpress Basis Plugin: von Step-Byte-Service GmbH – 1.0.0
Simple History: von Pär Thernström – 3.3.0
The Events Calendar: von The Events Calendar – 6.0.2
Converter for Media: von Image Optimization Team by matt plugins – 5.3.1
Advanced Order Export For WooCommerce: von AlgolPlus – 3.3.3
WooCommerce Stripe Gateway: von WooCommerce – 6.9.0
German Market: von MarketPress – 3.17
WooCommerce PayPal Payments: von WooCommerce – 1.9.4
WooCommerce Subscriptions: von WooCommerce – 4.0.2
WooCommerce: von Automattic – 7.0.0
Yoast SEO: von Team Yoast – 19.9
WP Rollback: von GiveWP.com – 1.7.2

### Inactive Plugins (3) ###

Depicter: von Averta – 1.3.5
ElementsKit Pro: von Wpmet – 2.8.0
PAYONE Payment for WooCommerce: von PAYONE GmbH – 2.3.0

### Must Use Plugins (1) ###

Elementor Safe Mode: von Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop-Basis: ❌ Die Sichtbarkeit der Seite sollte  öffentlich sein
Warenkorb: #11 - /warenkorb/
Kasse: #12 - /kasse/
Mein Konto: #13 - /mein-konto/
Allgemeine Geschäftsbedingungen: #12620 - /allgemeine_geschaeftsbedingungen/

### Theme ###

Name: Emeritus Child
Version: 1.1
Author URL: https://qodeinteractive.com
Child Theme: ✔
Parent Theme Name: Emeritus
Parent Theme Version: 1.1
Parent Theme Author URL: https://qodeinteractive.com
WooCommerce Support: ✔

### Templates ###

Overrides: emeritus-child/woocommerce/cart/cart-empty.php
emeritus-child/woocommerce/cart/cart.php
emeritus-child/woocommerce/cart/proceed-to-checkout-button.php
emeritus-child/woocommerce/checkout/payment.php
emeritus-child/woocommerce/checkout/thankyou.php
emeritus/inc/woocommerce/templates/content-widget-product.php
emeritus-child/woocommerce/global/form-login.php
emeritus/inc/woocommerce/templates/global/quantity-input.php
emeritus-child/woocommerce/myaccount/dashboard.php
emeritus-child/woocommerce/myaccount/form-edit-account.php
emeritus-child/woocommerce/myaccount/form-login.php Version 4.1.0 ist veraltet. Die Hauptversion ist 6.0.0
emeritus-child/woocommerce/myaccount/form-lost-password.php
emeritus-child/woocommerce/myaccount/form-reset-password.php
emeritus-child/woocommerce/myaccount/lost-password-confirmation.php
emeritus-child/woocommerce/myaccount/navigation.php

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst


### Abonnements ###

WCS_DEBUG: ✔ Nein
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.siteadress.com/
Subscriptions Template Theme Overrides: emeritus-child/woocommerce/myaccount/subscription-details.php
emeritus-child/woocommerce/single-product/add-to-cart/subscription.php

Subscription Statuses: trash: 1
wc-active: 266
wc-expired: 1
wc-pending: 7
wc-on-hold: 36
wc-cancelled: 33

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Ja
Cache Update Failures: ✔ 0 Fehler

### Shop-Einrichtung ###

Country / State: Deutschland — Nordrhein-Westfalen

### Abonnements nach Zahlungs-Gateway ###

other: wc-cancelled: 3
wc-on-hold: 13

PayPal: wc-active: 13
wc-cancelled: 7
wc-on-hold: 6
wc-pending: 2

Stripe: wc-active: 6
wc-cancelled: 1
wc-on-hold: 1
wc-pending: 1


### Zahlungs-Gateway-Unterstützung ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal: refunds
products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-26 10:30:53 +02:00
Options: ✔
Notes: 84
Onboarding: completed

### Action Scheduler ###

Complete: 2.940
Oldest: 2022-10-06 16:38:51 +0200
Newest: 2022-10-26 11:03:47 +0200

Failed: 39
Oldest: 2022-05-07 09:08:53 +0200
Newest: 2022-05-09 12:34:46 +0200

Pending: 272
Oldest: 2022-10-26 11:49:36 +0200
Newest: 2023-10-12 17:05:36 +0200


### Status report information ###

Generated at: 2022-10-26 11:27:41 +02:00
`
  ```

</details>

**Comment by Sirvijver** [comment] 2022-12-14 11:41
Hello @PineappleProduction

Thank you for reaching out to us, we are here to help.
We are aware of this issue and have a bug open for it. Normally I would link your support request to the bug, and you would be updated when we get a fix in place for such an issue, but we don't use GitHub for support requests.

If you want to get an update when we get a fix in place for this, I suggest you [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) and ask the support team to link your support request to the internal bug "PCP-812".

The problem is caused by the fact that the payment method is not getting saved/vaulted when there is no payment being made. This is an issue for PayPal, since subscriptions cannot be sold if the payment method is not stored. If you added a 1 cent payment, the issue would not occur, but I expect this is not the solution you are looking for.

At the moment, I cannot tell you what the timeline is for this bug to get resolved, so I would still advise you to open a new support request in order to get updated on this matter.
I will close this support request.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-14 11:41 UTC
