### ISSUE TITLE
the buttons do not appear on the checkout page

### ISSUE THREAD

**Issue by pucitos** [woocommerce/woocommerce-paypal-payments#1068] opened 2022-12-07 14:23 UTC
### Describe the Bug

I'm implementing the new paypal buttons on a woocommerce site.
The buttons appear on the cart page but do not appear on the checkout page
there seems to be a problem in the button.js file that buttonsSpinner.block(); 
error: 
Uncaught TypeError: jQuery(...).block is not a function
    at e.value (button.js?ver=2.0.0:formatted:7675:41)
    at t (button.js?ver=2.0.0:formatted:7828:36)
    at HTMLDocument.<anonymous> (button.js?ver=2.0.0:formatted:7837:21)
### Environment

 - WordPress Version 6.0.3
 - WooCommerce Version 6.7.0
 - Plugin Version 2.2.0

**Comment by Sirvijver** [comment] 2022-12-09 12:52
Hello @pucitos ,

I would like to ask you to open any support request you have for us on our WooCommerce support forum. You can [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are raising here, sounds like an issue with the short codes used on the checkout page. You can verify this, by creating a test checkout page and simply adding the [WooCommerce short code](https://woocommerce.com/document/woocommerce-shortcodes/) for the checkout page [woocommerce_checkout]. If the issue is with the short code, this page will show the buttons.

If this does not clarify the issue, and you need additional support, please open the support request as suggested. We will close this thread for now.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-09 12:52 UTC
Labels: support
