### ISSUE TITLE
Payment window is not connecting to PayPal / not showing PayPal login page

### ISSUE THREAD

**Issue by hanneskannes1988** [woocommerce/woocommerce-paypal-payments#2922] opened 2024-12-17 07:17 UTC
### Describe the Bug

On cart or checkout page, when I click any PayPal Button (Pay now / Pay Later), the small PayPal window is opened for a few seconds and then closed again. After that, a message is shown which says 'Something went wrong. Please try again or choose another payment source.'

### To Reproduce

1. Go to cart or checkout page
2. Click on PayPal button
3. See error 'Something went wrong. Please try again or choose another payment source.!'
4. Console is showing the error 'Landingpage not correct', but I'm not shure if this is realted to that issue

### Screenshots

![Image](https://github.com/user-attachments/assets/dba9276b-e5b6-4196-ba77-0fdfe4273608)
![Image](https://github.com/user-attachments/assets/3f072c29-29d8-443d-9931-dad2b559e632)
https://github.com/user-attachments/assets/fef8ae42-911a-44b6-9c49-09d35ffb15e7

### Expected Behavior

I expect that the window connects to PayPal and let the customer proceed to checkout.

### Actual Behavior

Payment window is closes without showing the PayPal login page

### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.4.3
 - Plugin Version: 2.9.5
 - Browser: Chrome 131.0.6778.140 / Edge 131.0.2903.99

### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.3
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.3.14
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.40-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

astra-advanced-hook: 15
attachment: 31669
clever_menu: 3
clever_menu_theme: 1
custom_css: 3
customer_groups: 5
customize_changeset: 4
elementor_font: 3
elementor_library: 221
elementor_snippet: 5
frontslider: 1
fts: 2
gfw_report: 2
izettle_purchase: 2
motor_content: 5
motor_header: 40
nav_menu_item: 1430
oembed_cache: 16
page: 124
post: 113
product: 460
product_variation: 385
product-feed: 2
rcb-banner-link: 10
rcb-blocker: 10
rcb-cookie: 65
revision: 2776
seopress_404: 8742
seopress_schemas: 3
shop_order_placehold: 12192
um_directory: 1
um_form: 3
user_registration: 2
wp_block: 15
wp_global_styles: 2
wp_navigation: 15
wp_template: 10
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Advanced Access Manager: von AAM  – 6.9.43
Advanced Database Cleaner PRO: von Younes JFR. – 3.2.10
FiboSearch - AJAX Search for WooCommerce: von FiboSearch Team – 1.29.0
Astra Pro: von Brainstorm Force – 4.8.8
Premium-Starter-Vorlagen: von Brainstorm Force – 4.4.10
B2B Market: von MarketPress – 2.1.7
Fluent Snippets: von Fluent Snippets – 10.34
Elementor Pro: von Elementor.com – 3.25.5
Elementor: von Elementor.com – 3.25.11
Folders Pro: von Premio – 3.0.6
WP Armour - Honeypot Anti Spam: von Dnesscarkey – 2.2.05
Innozilla Conditional Shipping and Payments for WooCommerce FREE: von Innozilla – 4.0.0
Kadence WooCommerce Email Designer: von Kadence WP – 1.5.14
Perfmatters: von forgemedia – 2.3.6
Real Cookie Banner: von devowl.io – 5.0.6
Say What? Pro: von Ademti Software Ltd. – 6.0.10
ShortPixel Image Optimizer: von ShortPixel - Convert WebP/AVIF & Optimize Images – 6.0.4
WPML Multilingual CMS: von OnTheGoSystems – 4.6.15
Spectra Pro: von Brainstorm Force – 1.1.9
Category Order and Taxonomy Terms Order: von Nsp-Code – 1.8.7
Spectra: von Brainstorm Force – 2.18.0
Ultimate Addons for Elementor Pro: von Brainstorm Force – 1.37.3
WPC Frequently Bought Together for WooCommerce (Premium): von WPClever – 7.5.2
WooCommerce JTL-Connector: von JTL-Software GmbH – 2.2.0
Product Feed ELITE for WooCommerce: von AdTribes.io – 4.8.4
German Market: von MarketPress – 3.44
WooCommerce Multilingual & Multicurrency: von OnTheGoSystems – 5.3.9
WooCommerce PayPal Payments: von WooCommerce – 2.9.5
WooCommerce: von Automattic – 9.4.3
WP Cerber Security, Anti-spam & Malware Scan: von Cerber Tech Inc. – 9.6.4
WP Rocket | Exclude CSS files from Remove Unused CSS: von WP Rocket Support Team –
WP Rocket: von WP Media – 3.17.3.1
WPML SEO: von OnTheGoSystems – 2.1.0.1
SEOPress PRO: von The SEO Guys at SEOPress – 8.4
SEOPress: von The SEO Guys at SEOPress – 8.4
WPML Media Translation: von OnTheGoSystems – 2.7.5
WPML Sticky Links: von OnTheGoSystems – 1.5.4
WPML String Translation: von OnTheGoSystems – 3.2.17
Custom Product Tabs for WooCommerce: von Code Parrots – 1.8.5

### Inactive Plugins (1) ###

WooCommerce Zettle Integration: von BjornTech AB – 7.9.5

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (2) ###

aaa-wp-cerber.php: von Cerber Tech Inc. – 1.0
Perfmatters MU: von forgemedia – 2.3.6

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
product_variation (product_variation)
simple (simple)
variable (variable)
woosb (woosb)
woosg (woosg)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 506 kB

### WC Pages ###

Shop-Basis: #50558 - /shop/
Warenkorb: #50559 - /warenkorb/ -  Enthält den [woocommerce_cart]-Shortcode
Kasse: #50560 - /kasse/ -  Enthält den [woocommerce_checkout]-Shortcode
Mein Konto: #50579 - /mein-konto/
Allgemeine Geschäftsbedingungen: #50562 - /agb/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.8.8
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: ✔
Google Pay: ✔
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-12-17 13:17:27 +01:00
Options: ✔
Notes: 40
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 2.945
Oldest: 2024-11-16 09:16:58 +0100
Newest: 2024-12-17 07:57:24 +0100

Fehlgeschlagen: 2.449
Oldest: 2022-11-25 07:59:59 +0100
Newest: 2024-12-16 09:24:27 +0100

Ausstehend: 29
Oldest: 2024-12-17 07:55:39 +0100
Newest: 2024-12-18 00:30:16 +0100

### Status report information ###

Generated at: 2024-12-17 07:57:42 +01:00
```
</details>
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-12-18 07:57
Hello @hanneskannes1988 


It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-12-18 07:57 UTC
Labels: support
