### ISSUE TITLE
For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend (627)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-paypal-payments#129] opened 2021-02-26 21:35 UTC
This issue was originally filed in the WooCommerce Core repository by @gglobalstep: https://github.com/woocommerce/woocommerce/issues/29216 while testing WooCommerce 5.1 pre-release. 

The following testing instructions had been followed in order to reproduce the issue:

https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.1#enhancement-use-the-new-paypal-payments-plugin-for-onboarding-6261

Please note that I did not triage this issue and simply copy-pasting the original issue as I am not able to transfer the issue to this repo from Core for some reason. 

## Bug Description:
For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Go to frontend
1. Click/View on any "product".
1. Observe that for Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Actual Result:
For Twenty Twenty- One theme "PayPal" payment button appears misaligned on the frontend.

## Expected Result:
For Twenty Twenty- One theme "PayPal" payment button should display correctly on the frontend..

## Screenshot:
![#29216_1](https://user-images.githubusercontent.com/41110392/109032329-8a9eff00-76eb-11eb-9337-a0d58571acd0.png)
![#29216_2](https://user-images.githubusercontent.com/41110392/109032344-925ea380-76eb-11eb-891a-cecb6ec068cb.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by InpsydeNiklas** [comment] 2022-06-21 09:48
We can't do anything here. Every theme can apply their own style for `Proceed to checkout` which would break our styles. Themes like Storefront add the margin in their own CSS file.

For example, on “TwentyTwentyOne“  the `float: left;` is applied for Proceed to checkout button so in order to fix the margin I have to add some additional styles, not just `margin-top`

![image](https://user-images.githubusercontent.com/70433191/174614363-e7105691-a100-4229-9e68-057c207531cf.png)
![image](https://user-images.githubusercontent.com/70433191/174614417-7f04a088-b857-45fc-8d87-22db7423ce87.png)

I can also apply style on Proceed to checkout button like `margin-bottom` but that wouldn't be right, the plugin should not apply styles for the default WooCommerce button. Either the theme or Woo itself should do it.
So we'll close this as it works as intended. A user can manually add a margin if the theme doesn't provide it.

**Closed as completed by InpsydeNiklas** 2022-06-21 09:48 UTC
Labels: enhancement
