### ISSUE TITLE
REST API encountered an error

### ISSUE THREAD

**Issue by jeffhuen** [woocommerce/woocommerce-paypal-payments#1215] opened 2023-02-27 19:22 UTC
### Describe the Bug

Activating the plugin now causes a conflict, and produces a REST API error.  I noticed this when my other plugins that rely on the REST API could not function.  

The error message in the Site Health Status produces:

**The REST API encountered an error**

The REST API is one way that WordPress and other applications communicate with the server. For example, the block editor screen relies on the REST API to display and save your posts and pages.

When testing the REST API, an error was encountered:
REST API Endpoint: https://www.revwatches.com/wp-json/wp/v2/types/post?context=edit
REST API Response: (http_request_failed) cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received

### To Reproduce

1. Install Plugin
2. Activate Plugin
3. Go to Site Health

### Screenshots

<img width="850" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/32542276/221661901-cf7d33dd-d92a-4f23-8c29-3bec9d9ed09c.png">

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version 7.4
 - Plugin Version 2.0.2
 - Browser [e.g. Chrome, Safari] and Version: not relevant
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment] 2023-03-14 17:28
Hi @jeffhuen,
The cause for this compatibility issue was resolved in the latest update, 2.0.3.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if any issues persist for you with the latest version. Thanks!

**Closed as completed by InpsydeNiklas** 2023-03-14 17:28 UTC
Labels: bug, support
