### ISSUE TITLE
Connection PayPal not possible

### ISSUE THREAD

**Issue by Digi30** [woocommerce/woocommerce-paypal-payments#1523] opened 2023-07-19 14:16 UTC
### To Reproduce

1. Go to 'WooCommerce Payments'
2. Click on 'connect your account'
3. Scroll down to …' Loading
4. See nothing

### Environment

 - WordPress Version: 6.2.2.
 - WooCommerce Version 7.9.0
 - WooCommerce PayPal Payments Version 2.2.0
 - Plugin Version
 - Browser [Microsoft Edge
Version 114.0.1823.82 (Offizielles Build) (x86_64)
 - Any other plugins installed
Antispam Bee | Version 2.11.3 von pluginkollektiv \| 
Custom Fonts | Version 2.0.2 von Brainstorm Force \| 
Easy Footnotes | Version 1.1.6 von Jason Yingling \| 
Germanized for WooCommerce | Version 3.13.3 von vendidero \| 
Germanized for WooCommerce Pro | Version 3.7.1 von vendidero \| 
Google Listings and Ads | Version 2.5.0 von WooCommerce \| 
Jetpack | Version 12.3 von Automattic \| 
One Stop Shop for WooCommerce | Version 1.3.9 von vendidero \| 
Pinterest for WooCommerce | Version 1.3.5 von WooCommerce \| 
Rank Math SEO | Version 1.0.119.1 von Rank Math \| 
Thrive Architect | Version 3.22.2 von <a href="http://www.thrivethemes.com">Thrive Themes</a> \|
Thrive Leads | Version 3.20.2 von <a href="https://thrivethemes.com">Thrive Themes</a> \| 
Thrive Optimize | Version 2.20 von Thrive Themes \| 
Thrive Product Manager | Version 1.12 von Thrive Themes \| 
WooCommerce | Version 7.9.0 von Automattic \| 
WooCommerce Payments | Version 6.2.0 von Automattic \| 
WooCommerce PayPal Payments | Version 2.2.0 von WooCommerce \| 
WooCommerce Payrexx Gateway | Version 2.0.8 von Payrexx \| 
WP Mail SMTP | Version 3.8.2 von WP Mail SMTP \| 

### Additional Details

<details><summary>System status</summary> 
`
### WordPress Environment ###

WordPress address (URL): https://swissoganic.com
Site address (URL): https://swissoganic.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.81.0
GnuTLS/3.7.3

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB-0ubuntu0.22.04.1-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: kbwbl_
Datenbank-Gesamtgröße: 27.28MB
Datenbank-Datengröße: 22.37MB
Datenbank-Indexgröße: 4.91MB
kbwbl_woocommerce_sessions: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_actionscheduler_actions: Daten: 1.76MB + Index: 0.48MB + Engine MyISAM
kbwbl_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
kbwbl_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
kbwbl_actionscheduler_logs: Daten: 0.75MB + Index: 0.59MB + Engine MyISAM
kbwbl_commentmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
kbwbl_comments: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
kbwbl_gla_attribute_mapping_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_gla_budget_recommendations: Daten: 0.22MB + Index: 0.14MB + Engine InnoDB
kbwbl_gla_merchant_issues: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_gla_shipping_rates: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_gla_shipping_times: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
kbwbl_mailpoet_automations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_automation_runs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_automation_run_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_automation_run_subjects: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_automation_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_automation_versions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_newsletter_templates: Daten: 3.28MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
kbwbl_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_subscribers: Daten: 0.02MB + Index: 0.23MB + Engine InnoDB
kbwbl_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_subscriber_tag: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_mailpoet_tags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_options: Daten: 3.61MB + Index: 0.12MB + Engine MyISAM
kbwbl_postmeta: Daten: 9.44MB + Index: 0.18MB + Engine MyISAM
kbwbl_posts: Daten: 0.75MB + Index: 0.05MB + Engine MyISAM
kbwbl_rank_math_internal_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_rank_math_redirections: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_rank_math_redirections_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_storeabill_documentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_storeabill_document_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_tab_event_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_tab_tests: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_tab_test_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_tcb_api_error_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_td_fields: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
kbwbl_td_groups: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_termmeta: Daten: 0.03MB + Index: 0.02MB + Engine MyISAM
kbwbl_terms: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
kbwbl_term_relationships: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
kbwbl_term_taxonomy: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
kbwbl_thrive_reporting_logs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
kbwbl_tve_leads_contacts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_tve_leads_contact_download: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_tve_leads_event_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_tve_leads_form_summary: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_tve_leads_form_variations: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_tve_leads_group_options: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_tve_leads_saved_group_options: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_tve_leads_split_test: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_tve_leads_split_test_items: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_usermeta: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
kbwbl_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
kbwbl_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
kbwbl_wc_admin_note_actions: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
kbwbl_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
kbwbl_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
kbwbl_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbwbl_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbwbl_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbwbl_wpmailsmtp_tasks_meta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

_tcb_form_settings: 5
attachment: 114
bsf_custom_fonts: 17
customize_changeset: 1
document_template: 5
mailpoet_page: 1
nav_menu_item: 62
page: 21
post: 3
product: 2
revision: 54
tcb_content_template: 22
tcb_symbol: 19
thrive_demo_page: 1
thrive_demo_post: 1
thrive_layout: 10
thrive_section: 3
thrive_template: 24
thrive_typography: 2
tve_menu_settings: 12
tve_notifications: 1
tve_user_template: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Antispam Bee: von pluginkollektiv – 2.11.3
Custom Fonts: von Brainstorm Force – 2.0.2
Easy Footnotes: von Jason Yingling – 1.1.6
Google Listings and Ads: von WooCommerce – 2.5.0
Jetpack: von Automattic – 12.3
One Stop Shop für WooCommerce: von vendidero – 1.3.9
Pinterest für WooCommerce: von WooCommerce – 1.3.5
Rank Math SEO: von Rank Math – 1.0.119.1
Thrive Optimize: von Thrive Themes – 2.20
Thrive Leads: von <a href="https://thrivethemes.com">Thrive Themes</a> – 3.20.2
Thrive Product Manager: von Thrive Themes – 1.12
Thrive Architect: von <a href="http://www.thrivethemes.com">Thrive Themes</a> – 3.22.2
WooCommerce Payrexx Gateway: von Payrexx – 2.0.8
Germanized für WooCommerce Pro: von vendidero – 3.7.1
Germanized für WooCommerce: von vendidero – 3.13.3
WooCommerce-Zahlungen: von Automattic – 6.2.0
WooCommerce PayPal Payments: von WooCommerce – 2.2.0
WooCommerce: von Automattic – 7.9.0
WP Mail SMTP: von WP Mail SMTP – 3.8.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: von Automattic - Anti Spam Team – 5.2
MailPoet: von MailPoet – 4.21.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #40 - /shop/
Warenkorb: #41 - /warenkorb/
Kasse: #42 - /kasse/
Mein Konto: #43 - /mein-konto/
Allgemeine Geschäftsbedingungen: #51 - /agb/

### Theme ###

Name: Thrive Theme Builder
Version: 3.20.2
Author URL: 
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Archive Template: Dein Theme hat eine woocommerce.php-Datei
was dazu führt
dass du das Template woocommerce/archive-product.php nicht überschreiben kannst
da woocommerce.php höher gewichtet wird als archive-product.php. Das ist beabsichtigt
um Darstellungsprobleme zu verhindern.

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: CH
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-19 20:02:56 +02:00
Options: ✔
Notes: 78
Onboarding: completed

### WooCommerce Payments ###

Version: 6.2.0
Connected to WPCOM: Ja
Blog ID: 220503175
Account ID: acct_1NVZsyC01C7Fzblz

### Action Scheduler ###

Complete: 4.638
Oldest: 2023-06-23 20:57:29 +0200
Newest: 2023-07-19 18:16:46 +0200

Failed: 3
Oldest: 2023-06-23 22:28:42 +0200
Newest: 2023-07-13 05:04:44 +0200

Pending: 12
Oldest: 2023-07-19 19:16:46 +0200
Newest: 2023-08-03 02:04:51 +0200

### Status report information ###

Generated at: 2023-07-19 19:00:40 +02:00
`

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment] 2023-07-20 11:23
Hello @Digi30 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There were some outages with PayPal this week, so it could have been a temporary issue.

However, if that is not the cause, here are some things you can do to try to get your account onboarded successfully:
- Take your time. When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.
- Another plugin can be blocking the onboarding process. You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.
- The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input).

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost

**Closed as completed by Sirvijver** 2023-07-20 11:23 UTC
Labels: support
