### ISSUE TITLE
The message at the chek out on safari : MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS`.

### ISSUE THREAD

**Issue by lauremipsum46** [woocommerce/woocommerce-paypal-payments#1440] opened 2023-06-15 19:58 UTC
### Describe the Bug

An issue occured at the checkout only on Safari... A message say : MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS`. And it's impossible to proceed.

### Screenshots

[](https://www.nature-et-sens.eu/commander/)

 - WordPress Version 
 - WooCommerce Version 7.8
 - Plugin Version : 2.1
 - Browser [e.g. Chrome, Safari] and Version : Safari 16.5
 - Plugin aren't in cause, cause it's only a problem from Safari or when the customer arrive from the link on the instagram bio

</details>

**Comment by Sirvijver** [comment] 2023-06-19 11:12
Hello @lauremipsum46 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered has been seen before, and we do have a bug open for it, but we have not yet been able to fully identify the cause for it. In certain instances we saw that the Divi Theme could cause the problem and another merchant informed us that the Germanized plugin caused the problem. However, we have not been able to find a solution from our end, so at this moment the best way forward would be to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
 Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).  

The issue you might encounter here, is that you will first need to find a way to reproduce the issue and for this we also advise you to create a staging site and generate some sandbox accounts on the [PayPal Developer Site](https://developer.paypal.com/). We will close this thread and advise you once more to open a support request in case you require additional support.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-06-19 11:12 UTC
Labels: support
