### ISSUE TITLE
Paypal button not shwoing in the checkout page (it shows in the cart)

### ISSUE THREAD

**Issue by oualidch** [woocommerce/woocommerce-paypal-payments#1889] opened 2023-12-05 17:37 UTC
### Hi, the paypal button is not showing on the checkout page on my website, but showing on the cart page
I'm using the latest versions of Wordpress and woocommerce
My website: https://lingualid.com/checkout
Please see the screenshot
How can we solve that? thank you
### Screenshots

![img963](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153011437/00c36a62-798c-4f6c-8f45-aba8d9bd9205)

**Comment by Sirvijver** [comment] 2023-12-07 08:48
Hello @oualidch 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I did review your checkout page, but it seems that also the "Debit & Credit Cards" does not show any button on your site, so something is blocking the function of button display function. There are 2 things I would advise you to do:
- Check if this is caused by the page (build), by creating a new page and only add the short code [woocommerce_checkout] and see if the build of the page is causing this problem.
- Perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). 
- Try our last release (version 2.4.2, if you are not already using this), this release includes a backup solution for the checkout buttons. Before, it was not possible to use the default WooCommerce button on the checkout, but since the last release this is allowed.

If none of this helps you resolve the issue, please open a new support thread with our team, so we can take a closer look. I will now close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-12-07 08:48 UTC
Labels: support
