### ISSUE TITLE
PayLaterBlockModule Not Found Error

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#2048] opened 2024-02-22 10:24 UTC
### Describe the Bug

PHP Fatal error: Uncaught Error: Class ‘WooCommerce\PayPalCommerce\PayLaterBlock\PayLaterBlockModule’ not found in ../public_html/wp-content/plugins/woocommerce-paypal-payments/modules.php:70

Stack trace: 0 ../public_html/wp-content/plugins/woocommerce-paypal-payments/bootstrap.php(27): {closure}(‘…’)

1 ../public_html/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(75): {closure}(‘../…’)

2 ../public_html/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(90): WooCommerce\PayPalCommerce\init()

3 ../public_html/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce{closure}(”)

4 ../public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)

5 ../public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)

6 ../public_html/wp-settings.php(506): do_action(‘plugins_loaded’)

7 ../public_htm in ../public_html/wp-content/plugins/woocommerce-paypal-payments/modules.php on line 70

### To Reproduce

All plugin are ok, no conflit, all update, this bug is always since December 2023.

### Expected Behavior

Button GooglePay and PayPal classic are ok
Button CB are ok

Country where i'm accept the PayLater and all was ok and since December 2023 no Paylater visible

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1
 - Php version 8.3.0
 - Theme Astra Pro 4.6.5
 - WooCommerce PayPal Payments 2.5.3
 - Plugin Version
 - Browser [e.g. Chrome, Safari] Vivaldi, Firefox, Opera, Brave

Not the same to have this bug : 

https://wordpress.org/support/topic/paylaterblockmodule-not-found-error/

**Comment by SydeKrystian** [comment] 2024-02-23 08:17
Hello @NicolasErnult 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

This looks like a conflict with another plugin. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-02-23 08:17 UTC
Labels: support

**Comment by ghost** [comment] 2024-02-23 08:20
I have no conflit with other plugin and i use theme Astra
All was fine but since December 2023, Paylater not appear, and it's the pluging do problems.
Please be serious and don't report fault other and obligate to use a other themes. The problems and bug comes from PayLater

**Comment by SydeKrystian** [comment] 2024-02-23 12:37
Hello @NicolasErnult 

To assist you successfully, we would appreciate it if you would contact our support team directly, as mentioned in our previous message. Providing a system report will greatly help us to diagnose and resolve the problem quickly.

Kind regards,
Krystian

**Comment by ghost** [comment] 2024-02-23 13:02
I already do on Woocommerce Support and Brainstormforce (theme Astra) and for Brainstorm it's a bug from the plugin Paypal Payments
