### ISSUE TITLE
Bug open new tab about:bank after click button paid with paypal

### ISSUE THREAD

**Issue by agence-banso** [woocommerce/woocommerce-paypal-payments#2696] opened 2024-10-13 09:47 UTC
### Describe the Bug

Bug open new tab about:bank after click button paid with paypal

### To Reproduce

1. Go to 'https://shop.banso.mc/commande/' after add product in cart
2. Click on 'Pay with Paypal'
3. See error

### Screenshots

![Image](https://github.com/user-attachments/assets/36d55f7b-2243-4731-8e1c-a6e2c75e7e96)

### Expected Behavior

The paypal popup opens fine I just want the about:bank not to appear

### Actual Behavior

Suddenly an about:blank page opens in front of the paypal popup

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.3
 - Plugin Version 2.9.2
 - Browser all browser

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment] 2024-10-15 07:13
Hello @agence-banso 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

Regarding the issue this looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Closed as completed by SydeKrystian** 2024-10-15 07:13 UTC
Labels: support
