### ISSUE TITLE
2.5.0 Upgrade "not enabled to vault payment source"

### ISSUE THREAD

**Issue by gunship800** [woocommerce/woocommerce-paypal-payments#1981] opened 2024-01-23 15:56 UTC
Customers unable to log into Paypal and pay at checkout.

Error message "NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance."

Cause: Updated to 2.5.0

Solved: Rolled back to prior version

**Comment by Sirvijver** [comment] 2024-01-24 06:34
Hello @gunship800 

Thank you for reaching out to us, we are here to help.
We are aware of this issue and working on providing a fix for this problem. Because we don't have one available now and the problem is significant, we decided to revert to 2.4.3 in the form of the 2.5.1 release that was pushed yesterday. I am confident that we will get this issue resolved soon and release it as version 2.5.2.

We have also gotten this reported in our support forum [here](https://wordpress.org/support/topic/latest-update-2-5-0-causing-error-not_enabled_to_vault_payment_source/) and we will try to update these 2 threads when any details become available.

Kind regards, 
Joost

**Comment by InpsydeNiklas** [comment] 2024-02-01 11:04
The cause for the issue was resolved in the latest version 2.5.2. It now includes an extra check to ensure Vaulting is not enabled for merchants without Reference Transactions.

**Closed as completed by InpsydeNiklas** 2024-02-01 11:04 UTC
Labels: bug
