### ISSUE TITLE
Error With Payments after updating 2.0.0

### ISSUE THREAD

**Issue by adaptia** [woocommerce/woocommerce-paypal-payments#1014] opened 2022-11-23 02:49 UTC
Hi Team,

###### I updated the plugin to 2.0.0 and every time I click the PayPal button or debit/credit card option it returned me with error message:

SOMETHING WENT WRONG. PLEASE TRY AGAIN OR CHOOSE ANOTHER PAYMENT SOURCE

###### when I inspected I found this in the console
<img width="733" alt="Screenshot 2022-11-23 at 8 02 34 AM" src="https://user-images.githubusercontent.com/61680582/203460463-d49de0de-158c-4468-a509-be67fc21d2cc.png">

**Comment by web4studio** [comment] 2022-11-23 09:31
Yes. We can confirm this issue as well.

**Comment by Sirvijver** [comment] 2022-12-13 11:10
Hello,

Thank you for reaching out to us, we are here to help. 
However, we don't perform support via GitHub, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue has been seen before, and I believe you can resolve it (temporarily) by rolling back to version 1.9.5. We would like to check with you what is causing the issue, because we have not been able to reproduce this on our own testing environment. We would expect this to be caused by a plugin conflict. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If you want to do this or require additional support, please [reach out to our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

For now, I will close this thread.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2022-12-13 11:10 UTC
Labels: support
