### ISSUE TITLE
Lost order after failed PayPal payment attempt

### ISSUE THREAD

**Issue by RalitzaBrestnichka** [woocommerce/woocommerce-paypal-payments#1812] opened 2023-10-31 07:55 UTC
### Describe the Bug

If the PayPal gateway fails for some reason and the customer gets back to the website this error is thrown so they cannot proceed with another payment method and need to start the process again.

 CRITICAL Uncaught Error: Call to a member function id() on null in /home/onebedco/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayPalGateway.php:598

### Expected Behavior

After a failed payment via PayPal, the customer to be able to 

### Environment
woocommerce website

 - WordPress Version 6.3.2
 - WooCommerce Version 8.2.1 
 - Plugin Version 2.3.1

**Comment by Sirvijver** [comment] 2023-10-31 08:21
Hello @RalitzaBrestnichka 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error you have shared is the error you probably see in the logs, but we would need to see more details on this issue. For example, the system report, order notes and the front end error would be pieces of information that could explain to us what this is related to. We always advise performing [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to be performed by the merchants to exclude a conflict from being the cause for such an issue, so we would advise that. If that does not show you any indicator for what is causing this, please open a support thread as advised above and provide the additionally requested details, so we can take another look.

We will close this thread and wait for you to open a new support ticket.

Kind regards, 
Joost

**Closed as completed by Sirvijver** 2023-10-31 08:21 UTC
Labels: support
