### ISSUE TITLE
New version 2.9.5 breaks Wordpress

### ISSUE THREAD

**Issue by jjmoody** [woocommerce/woocommerce-paypal-payments#2914] opened 2024-12-13 06:03 UTC
### Describe the Bug

Not sure what is causing the issue, but simply updating causes WordPress to crash

### Screenshots

https://ibb.co/9HDC2gL

### Expected Behavior

For the update to go smoothly

### Actual Behavior

The update takes down the entire website.

### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.4.3
 - Plugin Version: 2.9.5
 - Browser [e.g. Chrome, Safari] and Version: Every browser I've tried
 - Any other plugins installed: 
 - AliDropship Woo Plugin 1.6.73.2
 - Asset CleanUp Pro: Page Speed Booster 1.2.6.0
 - Contact Form 7 6.0.1
 - Email Address Obfuscation 1.1.0
 - Flo Forms 1.0.43
 - Google for WooCommerce 2.1.2
 - Header Footer Code Manager Pro 1.0.20
 - Login Logo 0.10.3
 - Maintenance PRO 5.2.6
 - MC4WP: Mailchimp for WordPress 4.9.19
 - Nextend Social Login 3.1.16
 - Nextend Social Login Pro Addon 3.1.16
 - Onea Core 1.5
 - Onea Instagram Feed 2.0.1
 - Onea Twitter Feed 1.0.4
 - Pinterest for WooCommerce 1.4.13
 - PW WooCommerce Gift Cards 2.10
 - Security Optimizer 1.5.7
 - Slider Revolution 6.7.23
 - Slider Revolution FilmStrip Add-On 6.7.3
 - Slider Revolution Particles Effect 6.7.4
 - Slider Revolution The Cluster AddOn 6.7.2
 - Slider Revolution Transitionpack Add-On 6.7.5
 - Speed Optimizer 7.7.2
 - TablePress (Premium) 3.0.1
 - Tawk.to Live Chat 0.8.7
 - Thank You Page for WooCommerce PRO 4.1.9
 - TikTok 1.3.0
 - User Registration ( Pro ) 4.3.5.2
 - User Registration WooCommerce 1.5.6
 - Video Gallery for WooCommerce 1.34
 - WooCommerce Amazon Pay 2.5.3
 - WooCommerce Product Tabs 2.1.2
 - WooCommerce Shipping 1.3.0
 - WooCommerce Shipping & Tax 2.8.5
 - WooCommerce.com Update Manager 1.0.3
 - WooPayments 8.6.0
 - WP Mail SMTP 4.3.0
 - WPBakery Page Builder 8.0.1
 - WPLoyalty - WooCommerce Loyalty Points, Rewards and Referral Pro 1.2.14
 - YITH Stripe Connect for WooCommerce 2.40.0
 - YITH WooCommerce Affiliates Premium 3.13.0
 - YITH WooCommerce Wishlist 4.0.1
 - Yoast SEO 24.0

### Additional Details

I have nothing else at this time as I have not had time to create a copy and test yet. I will update when I do if you can't fix the problem with an update.

**Comment by jjmoody** [comment] 2024-12-13 06:13
Found the reason for the error... I hope it helps fix the problem with this version:

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 58 of the file /home/customer/www/[mydomain.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php](http://mydomain.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php). Error message: Declaration of WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\LoggerTrait::log($level, Stringable|string $message, array $context = []): void

**Comment by SydeKrystian** [comment] 2024-12-13 06:55
Hello @jjmoody 

Thanks for reaching out to us, we're here to help.

Most likely, some other plugin on your site implements the library psr/log in [version 3.0.0](https://packagist.org/packages/psr/log#3.0.0) which is not compatible with the version used in PayPal Payments.

The first step would be to isolate the cause of the conflict, so you may want to perform a full conflict test to understand which other plugin may be involved. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments, and then enabling other plugins one by one to see when the error occurs. Once you know which other plugin implements this version of the dependency, you could potentially ask the other plugin developer to consider downgrading the dependency version.

For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind Regards,
Krystian

**Closed as completed by SydeKrystian** 2024-12-13 06:55 UTC
Labels: support
